# EVE Online SDE: Anomaly Detection for Game Health

## **GOAL**
To analyze the EVE Online Static Data Export (SDE) to identify statistical anomalies in game items. The primary use case is monitoring "game health" by finding items (like ships) that are statistically imbalanced in their cost-vs-stat ratios.

## **Workflow Overview**

**ETL (Extract, Transform, Load):** The raw SDE (.zip) is downloaded from the official developer link, unzipped, and all 52 .jsonl files are uploaded to a Google Cloud Storage (GCS) bucket using a shell script.

**Data Wrangling (Pandas):** The core of this project involves loading the data from GCS into pandas DataFrames. This is a complex task, as key data (stats, materials, map positions) is nested in JSON columns. We use explode() and json_normalize() to flatten this data into usable tables.

**Visualization (Plotly):** We use interactive visualizations to understand the dataset's structure:

  
  **Treemaps:** To show the item hierarchy (Categories ->  Groups -> Types).

  **Network Graphs:** To show ownership (Factions -> Corporations -> Stations).
  
  **Bar Charts:** To count items by Race.
  
  **3D Scatter Plots:** To build a fully interactive 3D map of the EVE universe.

**Feature Engineering:** We build a "master feature vector" for all Ships. This table has one row per ship and columns for all its features, derived from joining 7 different files (e.g., types, groups, dogmaAttributes, blueprints, etc.).

# Configuration

In [ ]:
import os
from google.colab import auth

# 1. Authenticate the user
print("Authenticating to Google Cloud...")
auth.authenticate_user()
print("Authentication complete.")

# 2. Set your project id
PROJECT_ID = "cloud-sa-ml"  # @param {type:"string"}
os.environ["GOOGLE_CLOUD_PROJECT"] = PROJECT_ID

print(f"Set project to: {PROJECT_ID}")

# 3. Install the GCS library for pandas
print("Installing gcsfs...")
!pip install -q gcsfs
print("Installation complete.")

# 4. Set your Static data Bucket Name
BUCKET_NAME = "eve-online-foundation-data" # @param {type:"string"}
os.environ["EVE_DATA_BUCKET"] = BUCKET_NAME

BUCKET_PATH = f"gs://{BUCKET_NAME}"
print(f"Using GCS Bucket: {BUCKET_PATH}")

Authenticating to Google Cloud...
Authentication complete.
Set project to: cloud-sa-ml
Installing gcsfs...
Installation complete.
Using GCS Bucket: gs://eve-online-foundation-data

# Static Data Ingestion (Run onetime)

In [ ]:
%%bash

# --- 1. Script Setup ---
# Exit immediately if a command exits with a non-zero status.
set -e
# Treat unset variables as an error
set -u
# Ensure pipeline failures are captured
set -o pipefail

# --- 2. Configuration ---
ZIP_URL="https://developers.eveonline.com/static-data/eve-online-static-data-latest-jsonl.zip"
TEMP_DIR="eve_sde_data_temp"
ZIP_FILE="eve_sde.zip"

# --- 3. Cleanup Function ---
# This 'trap' will run the 'cleanup' function on script EXIT (whether success or failure)
function cleanup {
  echo "--- Running cleanup ---"
  rm -f "$ZIP_FILE"
  # Check if directory exists before trying to remove it
  if [ -d "$TEMP_DIR" ]; then
    rm -rf "$TEMP_DIR"
    echo "Removed $TEMP_DIR."
  fi
  echo "Cleanup complete."
}
trap cleanup EXIT

# --- 4. Main Execution ---

# Check for required tools
if ! command -v wget &> /dev/null || ! command -v unzip &> /dev/null || ! command -v gsutil &> /dev/null; then
  echo "Error: Required command (wget, unzip, or gsutil) not found."
  exit 1
fi

# Check if bucket exists and create if not
echo "Checking if bucket $BUCKET_PATH exists..."
if ! gsutil ls -b "$BUCKET_PATH" &> /dev/null; then
  echo "Bucket not found. Creating $BUCKET_PATH..."
  gsutil mb "$BUCKET_PATH"
else
  echo "Bucket $BUCKET_PATH already exists."
fi

# Step A: Download
echo "Downloading EVE SDE from $ZIP_URL..."
wget -O "$ZIP_FILE" "$ZIP_URL"
if [ $? -ne 0 ]; then
    echo "Download failed!"
    exit 1
fi
echo "Download complete."

# Step B: Unzip
echo "Unzipping files to $TEMP_DIR/..."
mkdir -p "$TEMP_DIR"
unzip -q "$ZIP_FILE" -d "$TEMP_DIR"
if [ $? -ne 0 ]; then
    echo "Unzip failed! The file might be corrupt."
    exit 1
fi
echo "Unzip complete."

# Step C: Find and Upload to GCS
echo "Finding .jsonl files..."
# Use 'find' to get a list of files and check if it's empty
# -L follows symlinks
file_list=$(find -L "$TEMP_DIR" -type f -name "*.jsonl")

if [ -z "$file_list" ]; then
  echo "Error: No .jsonl files were found in the unzipped archive."
  exit 1
fi

echo "Found .jsonl files. Uploading to gs://$BUCKET_NAME/..."
# Use the 'find' result to copy.
# We pipe the file list to gsutil -m cp -I for parallel streaming upload.
echo "$file_list" | gsutil -m cp -I "gs://$BUCKET_NAME/"
if [ $? -ne 0 ]; then
    echo "GCS upload failed!"
    exit 1
fi

# The 'trap' will handle cleanup automatically.
echo "--- All files successfully uploaded to gs://$BUCKET_NAME/ ---"
exit 0

Checking if bucket gs://eve-online-foundation-data/ exists...
Bucket gs://eve-online-foundation-data/ already exists.
Downloading EVE SDE from https://developers.eveonline.com/static-data/eve-online-static-data-latest-jsonl.zip...
Download complete.
Unzipping files to eve_sde_data_temp/...
Unzip complete.
Finding .jsonl files...
Found .jsonl files. Uploading to gs://eve-online-foundation-data/...
--- All files successfully uploaded to gs://eve-online-foundation-data/ ---
--- Running cleanup ---
Removed eve_sde_data_temp.
Cleanup complete.

--2025-10-24 21:29:24--  https://developers.eveonline.com/static-data/eve-online-static-data-latest-jsonl.zip
Resolving developers.eveonline.com (developers.eveonline.com)... 3.170.152.69, 3.170.152.87, 3.170.152.107, ...
Connecting to developers.eveonline.com (developers.eveonline.com)|3.170.152.69|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://developers.eveonline.com/static-data/tranquility/eve-online-static-data-3072925-jsonl.zip [following]
--2025-10-24 21:29:24--  https://developers.eveonline.com/static-data/tranquility/eve-online-static-data-3072925-jsonl.zip
Reusing existing connection to developers.eveonline.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 82257287 (78M) [application/zip]
Saving to: ‘eve_sde.zip’

     0K .......... .......... .......... .......... ..........  0% 4.16M 19s
    50K .......... .......... .......... .......... ..........  0% 9.84M 13s
   100K .......... .......... .......... .......... ..........  0% 7.27M 13s
   150K .......... .......... .......... .......... ..........  0% 13.8M 11s
   200K .......... .......... .......... .......... ..........  0% 17.2M 10s
   250K .......... .......... .......... .......... ..........  0% 13.6M 9s
   300K .......... .......... .......... .......... ..........  0% 34.3M 8s
   350K .......... .......... .......... .......... ..........  0% 29.1M 7s
   400K .......... .......... .......... .......... ..........  0% 22.0M 7s
   450K .......... .......... .......... .......... ..........  0% 27.3M 6s
   500K .......... .......... .......... .......... ..........  0% 25.5M 6s
   550K .......... .......... .......... .......... ..........  0% 36.3M 6s
   600K .......... .......... .......... .......... ..........  0% 44.4M 5s
   650K .......... .......... .......... .......... ..........  0% 61.2M 5s
   700K .......... .......... .......... .......... ..........  0% 33.9M 5s
   750K .......... .......... .......... .......... ..........  0% 63.0M 5s
   800K .......... .......... .......... .......... ..........  1% 63.2M 5s
   850K .......... .......... .......... .......... ..........  1% 62.0M 4s
   900K .......... .......... .......... .......... ..........  1% 42.1M 4s
   950K .......... .......... .......... .......... ..........  1% 63.5M 4s
  1000K .......... .......... .......... .......... ..........  1% 60.3M 4s
  1050K .......... .......... .......... .......... ..........  1% 48.2M 4s
  1100K .......... .......... .......... .......... ..........  1%  221M 4s
  1150K .......... .......... .......... .......... ..........  1% 60.5M 4s
  1200K .......... .......... .......... .......... ..........  1% 77.2M 3s
  1250K .......... .......... .......... .......... ..........  1% 60.0M 3s
  1300K .......... .......... .......... .......... ..........  1% 73.9M 3s
  1350K .......... .......... .......... .......... ..........  1%  239M 3s
  1400K .......... .......... .......... .......... ..........  1% 97.0M 3s
  1450K .......... .......... .......... .......... ..........  1% 79.3M 3s
  1500K .......... .......... .......... .......... ..........  1% 86.7M 3s
  1550K .......... .......... .......... .......... ..........  1%  290M 3s
  1600K .......... .......... .......... .......... ..........  2% 55.0M 3s
  1650K .......... .......... .......... .......... ..........  2%  164M 3s
  1700K .......... .......... .......... .......... ..........  2% 72.6M 3s
  1750K .......... .......... .......... .......... ..........  2%  159M 3s
  1800K .......... .......... .......... .......... ..........  2% 91.0M 3s
  1850K .......... .......... .......... .......... ..........  2%  203M 3s
  1900K .......... .......... .......... .......... ..........  2% 71.6M 2s
  1950K .......... .......... .......... .......... ..........  2%  257M 2s
  2000K .......... .......... .......... .......... ..........  2%  102M 2s
  2050K .......... .......... .......... .......... ..........  2%  152M 2s
  2100K .......... .......... .......... .......... ..........  2%  231M 2s
  2150K .......... .......... .......... .......... ..........  2% 91.2M 2s
  2200K .......... .......... .......... .......... ..........  2%  106M 2s
  2250K .......... .......... .......... .......... ..........  2%  260M 2s
  2300K .......... .......... .......... .......... ..........  2%  177M 2s
  2350K .......... .......... .......... .......... ..........  2%  147M 2s
  2400K .......... .......... .......... .......... ..........  3%  284M 2s
  2450K .......... .......... .......... .......... ..........  3%  199M 2s
  2500K .......... .......... .......... .......... ..........  3%  149M 2s
  2550K .......... .......... .......... .......... ..........  3%  249M 2s
  2600K .......... .......... .......... .......... ..........  3%  114M 2s
  2650K .......... .......... .......... .......... ..........  3%  184M 2s
  2700K .......... .......... .......... .......... ..........  3%  164M 2s
  2750K .......... .......... .......... .......... ..........  3%  168M 2s
  2800K .......... .......... .......... .......... ..........  3%  103M 2s
  2850K .......... .......... .......... .......... ..........  3%  158M 2s
  2900K .......... .......... .......... .......... ..........  3%  170M 2s
  2950K .......... .......... .......... .......... ..........  3%  177M 2s
  3000K .......... .......... .......... .......... ..........  3%  184M 2s
  3050K .......... .......... .......... .......... ..........  3%  201M 2s
  3100K .......... .......... .......... .......... ..........  3%  265M 2s
  3150K .......... .......... .......... .......... ..........  3%  238M 2s
  3200K .......... .......... .......... .......... ..........  4% 95.6M 2s
  3250K .......... .......... .......... .......... ..........  4%  166M 2s
  3300K .......... .......... .......... .......... ..........  4%  202M 2s
  3350K .......... .......... .......... .......... ..........  4%  128M 2s
  3400K .......... .......... .......... .......... ..........  4%  191M 2s
  3450K .......... .......... .......... .......... ..........  4%  204M 2s
  3500K .......... .......... .......... .......... ..........  4%  153M 2s
  3550K .......... .......... .......... .......... ..........  4%  177M 2s
  3600K .......... .......... .......... .......... ..........  4%  289M 2s
  3650K .......... .......... .......... .......... ..........  4%  195M 1s
  3700K .......... .......... .......... .......... ..........  4%  240M 1s
  3750K .......... .......... .......... .......... ..........  4%  168M 1s
  3800K .......... .......... .......... .......... ..........  4%  203M 1s
  3850K .......... .......... .......... .......... ..........  4%  195M 1s
  3900K .......... .......... .......... .......... ..........  4%  144M 1s
  3950K .......... .......... .......... .......... ..........  4%  169M 1s
  4000K .......... .......... .......... .......... ..........  5%  184M 1s
  4050K .......... .......... .......... .......... ..........  5%  193M 1s
  4100K .......... .......... .......... .......... ..........  5%  154M 1s
  4150K .......... .......... .......... .......... ..........  5%  201M 1s
  4200K .......... .......... .......... .......... ..........  5%  179M 1s
  4250K .......... .......... .......... .......... ..........  5%  145M 1s
  4300K .......... .......... .......... .......... ..........  5%  191M 1s
  4350K .......... .......... .......... .......... ..........  5%  182M 1s
  4400K .......... .......... .......... .......... ..........  5%  136M 1s
  4450K .......... .......... .......... .......... ..........  5%  176M 1s
  4500K .......... .......... .......... .......... ..........  5%  148M 1s
  4550K .......... .......... .......... .......... ..........  5%  107M 1s
  4600K .......... .......... .......... .......... ..........  5%  153M 1s
  4650K .......... .......... .......... .......... ..........  5%  161M 1s
  4700K .......... .......... .......... .......... ..........  5%  130M 1s
  4750K .......... .......... .......... .......... ..........  5%  153M 1s
  4800K .......... .......... .......... .......... ..........  6%  123M 1s
  4850K .......... .......... .......... .......... ..........  6%  187M 1s
  4900K .......... .......... .......... .......... ..........  6%  150M 1s
  4950K .......... .......... .......... .......... ..........  6%  176M 1s
  5000K .......... .......... .......... .......... ..........  6%  186M 1s
  5050K .......... .......... .......... .......... ..........  6%  169M 1s
  5100K .......... .......... .......... .......... ..........  6%  136M 1s
  5150K .......... .......... .......... .......... ..........  6%  180M 1s
  5200K .......... .......... .......... .......... ..........  6%  160M 1s
  5250K .......... .......... .......... .......... ..........  6%  188M 1s
  5300K .......... .......... .......... .......... ..........  6%  156M 1s
  5350K .......... .......... .......... .......... ..........  6%  186M 1s
  5400K .......... .......... .......... .......... ..........  6%  180M 1s
  5450K .......... .......... .......... .......... ..........  6%  314M 1s
  5500K .......... .......... .......... .......... ..........  6%  198M 1s
  5550K .......... .......... .......... .......... ..........  6%  174M 1s
  5600K .......... .......... .......... .......... ..........  7%  174M 1s
  5650K .......... .......... .......... .......... ..........  7%  289M 1s
  5700K .......... .......... .......... .......... ..........  7%  281M 1s
  5750K .......... .......... .......... .......... ..........  7%  242M 1s
  5800K .......... .......... .......... .......... ..........  7%  167M 1s
  5850K .......... .......... .......... .......... ..........  7%  139M 1s
  5900K .......... .......... .......... .......... ..........  7%  266M 1s
  5950K .......... .......... .......... .......... ..........  7%  218M 1s
  6000K .......... .......... .......... .......... ..........  7%  243M 1s
  6050K .......... .......... .......... .......... ..........  7%  158M 1s
  6100K .......... .......... .......... .......... ..........  7%  183M 1s
  6150K .......... .......... .......... .......... ..........  7%  286M 1s
  6200K .......... .......... .......... .......... ..........  7%  276M 1s
  6250K .......... .......... .......... .......... ..........  7%  183M 1s
  6300K .......... .......... .......... .......... ..........  7%  276M 1s
  6350K .......... .......... .......... .......... ..........  7%  194M 1s
  6400K .......... .......... .......... .......... ..........  8%  190M 1s
  6450K .......... .......... .......... .......... ..........  8%  140M 1s
  6500K .......... .......... .......... .......... ..........  8%  290M 1s
  6550K .......... .......... .......... .......... ..........  8%  313M 1s
  6600K .......... .......... .......... .......... ..........  8%  312M 1s
  6650K .......... .......... .......... .......... ..........  8%  148M 1s
  6700K .......... .......... .......... .......... ..........  8%  221M 1s
  6750K .......... .......... .......... .......... ..........  8%  157M 1s
  6800K .......... .......... .......... .......... ..........  8%  261M 1s
  6850K .......... .......... .......... .......... ..........  8%  212M 1s
  6900K .......... .......... .......... .......... ..........  8%  231M 1s
  6950K .......... .......... .......... .......... ..........  8%  265M 1s
  7000K .......... .......... .......... .......... ..........  8%  171M 1s
  7050K .......... .......... .......... .......... ..........  8%  218M 1s
  7100K .......... .......... .......... .......... ..........  8%  262M 1s
  7150K .......... .......... .......... .......... ..........  8%  193M 1s
  7200K .......... .......... .......... .......... ..........  9%  231M 1s
  7250K .......... .......... .......... .......... ..........  9%  237M 1s
  7300K .......... .......... .......... .......... ..........  9%  231M 1s
  7350K .......... .......... .......... .......... ..........  9%  136M 1s
  7400K .......... .......... .......... .......... ..........  9%  268M 1s
  7450K .......... .......... .......... .......... ..........  9%  170M 1s
  7500K .......... .......... .......... .......... ..........  9%  212M 1s
  7550K .......... .......... .......... .......... ..........  9%  180M 1s
  7600K .......... .......... .......... .......... ..........  9%  174M 1s
  7650K .......... .......... .......... .......... ..........  9%  284M 1s
  7700K .......... .......... .......... .......... ..........  9%  210M 1s
  7750K .......... .......... .......... .......... ..........  9%  274M 1s
  7800K .......... .......... .......... .......... ..........  9%  312M 1s
  7850K .......... .......... .......... .......... ..........  9%  202M 1s
  7900K .......... .......... .......... .......... ..........  9%  271M 1s
  7950K .......... .......... .......... .......... ..........  9%  261M 1s
  8000K .......... .......... .......... .......... .......... 10%  294M 1s
  8050K .......... .......... .......... .......... .......... 10%  243M 1s
  8100K .......... .......... .......... .......... .......... 10%  236M 1s
  8150K .......... .......... .......... .......... .......... 10%  247M 1s
  8200K .......... .......... .......... .......... .......... 10%  272M 1s
  8250K .......... .......... .......... .......... .......... 10%  277M 1s
  8300K .......... .......... .......... .......... .......... 10%  308M 1s
  8350K .......... .......... .......... .......... .......... 10%  165M 1s
  8400K .......... .......... .......... .......... .......... 10%  322M 1s
  8450K .......... .......... .......... .......... .......... 10%  278M 1s
  8500K .......... .......... .......... .......... .......... 10%  285M 1s
  8550K .......... .......... .......... .......... .......... 10%  326M 1s
  8600K .......... .......... .......... .......... .......... 10%  171M 1s
  8650K .......... .......... .......... .......... .......... 10%  262M 1s
  8700K .......... .......... .......... .......... .......... 10%  241M 1s
  8750K .......... .......... .......... .......... .......... 10%  227M 1s
  8800K .......... .......... .......... .......... .......... 11%  273M 1s
  8850K .......... .......... .......... .......... .......... 11%  290M 1s
  8900K .......... .......... .......... .......... .......... 11%  233M 1s
  8950K .......... .......... .......... .......... .......... 11%  296M 1s
  9000K .......... .......... .......... .......... .......... 11%  252M 1s
  9050K .......... .......... .......... .......... .......... 11%  280M 1s
  9100K .......... .......... .......... .......... .......... 11%  243M 1s
  9150K .......... .......... .......... .......... .......... 11%  237M 1s
  9200K .......... .......... .......... .......... .......... 11%  243M 1s
  9250K .......... .......... .......... .......... .......... 11%  118M 1s
  9300K .......... .......... .......... .......... .......... 11%  120M 1s
  9350K .......... .......... .......... .......... .......... 11%  226M 1s
  9400K .......... .......... .......... .......... .......... 11%  261M 1s
  9450K .......... .......... .......... .......... .......... 11%  181M 1s
  9500K .......... .......... .......... .......... .......... 11%  247M 1s
  9550K .......... .......... .......... .......... .......... 11%  327M 1s
  9600K .......... .......... .......... .......... .......... 12%  289M 1s
  9650K .......... .......... .......... .......... .......... 12%  367M 1s
  9700K .......... .......... .......... .......... .......... 12%  216M 1s
  9750K .......... .......... .......... .......... .......... 12%  449M 1s
  9800K .......... .......... .......... .......... .......... 12%  539M 1s
  9850K .......... .......... .......... .......... .......... 12%  411M 1s
  9900K .......... .......... .......... .......... .......... 12%  424M 1s
  9950K .......... .......... .......... .......... .......... 12%  326M 1s
 10000K .......... .......... .......... .......... .......... 12%  384M 1s
 10050K .......... .......... .......... .......... .......... 12%  300M 1s
 10100K .......... .......... .......... .......... .......... 12%  318M 1s
 10150K .......... .......... .......... .......... .......... 12%  512M 1s
 10200K .......... .......... .......... .......... .......... 12%  489M 1s
 10250K .......... .......... .......... .......... .......... 12%  506M 1s
 10300K .......... .......... .......... .......... .......... 12%  341M 1s
 10350K .......... .......... .......... .......... .......... 12%  317M 1s
 10400K .......... .......... .......... .......... .......... 13%  202M 1s
 10450K .......... .......... .......... .......... .......... 13%  232M 1s
 10500K .......... .......... .......... .......... .......... 13%  276M 1s
 10550K .......... .......... .......... .......... .......... 13%  219M 1s
 10600K .......... .......... .......... .......... .......... 13%  328M 1s
 10650K .......... .......... .......... .......... .......... 13%  194M 1s
 10700K .......... .......... .......... .......... .......... 13%  219M 1s
 10750K .......... .......... .......... .......... .......... 13%  294M 1s
 10800K .......... .......... .......... .......... .......... 13%  310M 1s
 10850K .......... .......... .......... .......... .......... 13%  275M 1s
 10900K .......... .......... .......... .......... .......... 13%  276M 1s
 10950K .......... .......... .......... .......... .......... 13%  180M 1s
 11000K .......... .......... .......... .......... .......... 13%  176M 1s
 11050K .......... .......... .......... .......... .......... 13%  258M 1s
 11100K .......... .......... .......... .......... .......... 13%  241M 1s
 11150K .......... .......... .......... .......... .......... 13%  164M 1s
 11200K .......... .......... .......... .......... .......... 14%  254M 1s
 11250K .......... .......... .......... .......... .......... 14%  260M 1s
 11300K .......... .......... .......... .......... .......... 14%  304M 1s
 11350K .......... .......... .......... .......... .......... 14%  270M 1s
 11400K .......... .......... .......... .......... .......... 14%  228M 1s
 11450K .......... .......... .......... .......... .......... 14%  235M 1s
 11500K .......... .......... .......... .......... .......... 14%  204M 1s
 11550K .......... .......... .......... .......... .......... 14%  253M 1s
 11600K .......... .......... .......... .......... .......... 14%  258M 1s
 11650K .......... .......... .......... .......... .......... 14%  240M 1s
 11700K .......... .......... .......... .......... .......... 14%  311M 1s
 11750K .......... .......... .......... .......... .......... 14%  221M 1s
 11800K .......... .......... .......... .......... .......... 14%  240M 1s
 11850K .......... .......... .......... .......... .......... 14%  267M 1s
 11900K .......... .......... .......... .......... .......... 14%  263M 1s
 11950K .......... .......... .......... .......... .......... 14%  310M 1s
 12000K .......... .......... .......... .......... .......... 15%  273M 1s
 12050K .......... .......... .......... .......... .......... 15%  260M 1s
 12100K .......... .......... .......... .......... .......... 15%  245M 1s
 12150K .......... .......... .......... .......... .......... 15%  264M 1s
 12200K .......... .......... .......... .......... .......... 15%  204M 1s
 12250K .......... .......... .......... .......... .......... 15%  231M 1s
 12300K .......... .......... .......... .......... .......... 15%  309M 1s
 12350K .......... .......... .......... .......... .......... 15%  276M 1s
 12400K .......... .......... .......... .......... .......... 15%  248M 1s
 12450K .......... .......... .......... .......... .......... 15%  220M 1s
 12500K .......... .......... .......... .......... .......... 15%  228M 1s
 12550K .......... .......... .......... .......... .......... 15%  299M 1s

# General EDA / Profiler

This cell is a generic "profiler" script used to explore the dataset.

It loops through a list of selected files (or all files), loads them, and automatically:

1. Flattens any dictionary columns (like name) to their English values.

2. Prints the df.info() to show schema, dtypes, and null counts.

3. Displays the df.head() to show sample data.

4. Prints value_counts() for any "safe" (hashable) categorical columns.

In [ ]:
import pandas as pd
import io
import sys
import time
from google.cloud import storage

# --- 1. Configuration ---
BUCKET_NAME = "eve-online-foundation-data"
GCS_PATH = f"gs://{BUCKET_NAME}"

# Set pandas options for nice output
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 2000)

print(f"--- Starting General Profiler (with EN-Flattening) for gs://{BUCKET_NAME} ---")

# --- 2. Get Full List of Files ---
try:
    client = storage.Client()
    blobs = client.list_blobs(BUCKET_NAME)
    all_files = [blob.name for blob in blobs if blob.name.endswith('.jsonl')]
    print(f"Found {len(all_files)} total .jsonl files in the bucket.")
except Exception as e:
    print(f"Failed to list files: {e}")
    all_files = [] # empty list to avoid crash

# --- 3. SELECT WHICH FILES TO PROCESS ---

#files_to_process = [
#    'races.jsonl',
#    'factions.jsonl',
#    'categories.jsonl',
#    'groups.jsonl',
#    'mapRegions.jsonl', # This one will still show list data
#    'types.jsonl'
#]

#
# To run on ALL files, uncomment the next line
# WARNING: This will produce a *very* long output!
files_to_process = all_files
#

# Check if our selected files actually exist
files_to_process = [f for f in files_to_process if f in all_files]
print(f"Will process {len(files_to_process)} selected files: {files_to_process}\n")


# --- 4. Loop and Analyze ---
for filename in files_to_process:
    print(f"\n\n{'='*80}")
    print(f"--- 📊 Analyzing: {filename} ---")
    print(f"{'='*80}\n")

    try:
        # 1. Read into DF
        start_time = time.time()
        df = pd.read_json(f"{GCS_PATH}/{filename}", lines=True)
        print(f"Loaded {len(df)} rows in {time.time() - start_time:.2f}s")

        # --- 2. NEW: Pre-processing to flatten dicts ---
        print("\n[PRE-PROCESSING]")
        cols_to_flatten = []
        for col in df.columns:
            if df[col].dtype == 'object':
                # Find the first non-null item to check its type
                first_item = df[col].dropna().iloc[0] if not df[col].dropna().empty else None
                if isinstance(first_item, dict):
                    cols_to_flatten.append(col)

        if not cols_to_flatten:
            print("No dictionary columns found to flatten.")
        else:
            for col in cols_to_flatten:
                print(f"Flattening '{col}' to English ('en') key...")
                # Apply the logic: get 'en' value if it's a dict, otherwise keep original
                df[col] = df[col].apply(lambda x: x.get('en') if isinstance(x, dict) else x)

        # 3. Run df.info() (will show new flattened columns)
        print("\n[INFO]")
        info_buf = io.StringIO()
        df.info(buf=info_buf)
        print(info_buf.getvalue())

        # 4. Run df.head(5) (will show simple strings now)
        print("\n[HEAD]")
        display(df.head())

        # 5. Run value_counts()
        print("\n[VALUE COUNTS (Top 5 for hashable columns)]")

        if df.empty:
            print("DataFrame is empty.")
            continue

        for col in df.columns:
            if df[col].empty or df[col].isnull().all():
                print(f"\n--- Column: '{col}' (is empty or all null) ---")
                continue

            first_item = df[col].dropna().iloc[0]

            # Check for unhashable lists
            if isinstance(first_item, list):
                print(f"\n--- Column: '{col}' (Contains unhashable lists) ---")
                print("Sample value:", first_item)

            # All other types (str, int, float, bool) are now safe
            else:
                nunique = df[col].nunique()
                print(f"\n--- Column: '{col}' (Unique values: {nunique}) ---")

                # Show value_counts if it's categorical or low-cardinality
                if nunique < 100 or isinstance(first_item, str):
                    display(df[col].value_counts().head(5).to_frame())
                else:
                    print(f"Skipping value_counts (high-cardinality numeric: {nunique} unique)")

    except Exception as e:
        print(f"*** FAILED to process {filename}. Error: {e} ***")

print("\n--- Full Analysis Loop Finished ---")

--- Starting General Profiler (with EN-Flattening) for gs://eve-online-foundation-data ---
Found 52 total .jsonl files in the bucket.
Will process 52 selected files: ['_sde.jsonl', 'agentTypes.jsonl', 'agentsInSpace.jsonl', 'ancestries.jsonl', 'bloodlines.jsonl', 'blueprints.jsonl', 'categories.jsonl', 'certificates.jsonl', 'characterAttributes.jsonl', 'contrabandTypes.jsonl', 'controlTowerResources.jsonl', 'corporationActivities.jsonl', 'dbuffCollections.jsonl', 'dogmaAttributeCategories.jsonl', 'dogmaAttributes.jsonl', 'dogmaEffects.jsonl', 'dogmaUnits.jsonl', 'dynamicItemAttributes.jsonl', 'factions.jsonl', 'graphics.jsonl', 'groups.jsonl', 'icons.jsonl', 'landmarks.jsonl', 'mapAsteroidBelts.jsonl', 'mapConstellations.jsonl', 'mapMoons.jsonl', 'mapPlanets.jsonl', 'mapRegions.jsonl', 'mapSolarSystems.jsonl', 'mapStargates.jsonl', 'mapStars.jsonl', 'marketGroups.jsonl', 'masteries.jsonl', 'metaGroups.jsonl', 'npcCharacters.jsonl', 'npcCorporationDivisions.jsonl', 'npcCorporations.jsonl', 'npcStations.jsonl', 'planetResources.jsonl', 'planetSchematics.jsonl', 'races.jsonl', 'skinLicenses.jsonl', 'skinMaterials.jsonl', 'skins.jsonl', 'sovereigntyUpgrades.jsonl', 'stationOperations.jsonl', 'stationServices.jsonl', 'translationLanguages.jsonl', 'typeBonus.jsonl', 'typeDogma.jsonl', 'typeMaterials.jsonl', 'types.jsonl']



================================================================================
--- 📊 Analyzing: _sde.jsonl ---
================================================================================

Loaded 1 rows in 1.00s

[PRE-PROCESSING]
No dictionary columns found to flatten.

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   _key         1 non-null      object
 1   buildNumber  1 non-null      int64
 2   releaseDate  1 non-null      object
dtypes: int64(1), object(2)
memory usage: 156.0+ bytes


[HEAD]

  _key  buildNumber           releaseDate
0  sde      3072925  2025-10-24T11:13:57Z

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 1) ---

      count
_key
sde       1

--- Column: 'buildNumber' (Unique values: 1) ---

             count
buildNumber
3072925          1

--- Column: 'releaseDate' (Unique values: 1) ---

                      count
releaseDate
2025-10-24T11:13:57Z      1

================================================================================
--- 📊 Analyzing: agentTypes.jsonl ---
================================================================================

Loaded 13 rows in 0.11s

[PRE-PROCESSING]
No dictionary columns found to flatten.

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   _key    13 non-null     int64
 1   name    13 non-null     object
dtypes: int64(1), object(1)
memory usage: 340.0+ bytes


[HEAD]

   _key           name
0     1       NonAgent
1     2     BasicAgent
2     3  TutorialAgent
3     4  ResearchAgent
4     5   CONCORDAgent

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 13) ---

      count
_key
1         1
2         1
3         1
4         1
5         1

--- Column: 'name' (Unique values: 13) ---

               count
name
NonAgent           1
BasicAgent         1
TutorialAgent      1
ResearchAgent      1
CONCORDAgent       1

================================================================================
--- 📊 Analyzing: agentsInSpace.jsonl ---
================================================================================

Loaded 360 rows in 0.10s

[PRE-PROCESSING]
No dictionary columns found to flatten.

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   _key           360 non-null    int64
 1   dungeonID      360 non-null    int64
 2   solarSystemID  360 non-null    int64
 3   spawnPointID   360 non-null    int64
 4   typeID         360 non-null    int64
dtypes: int64(5)
memory usage: 14.2 KB


[HEAD]

      _key  dungeonID  solarSystemID  spawnPointID  typeID
0  3018343        416       30000165          4239   20520
1  3018344        422       30000165          4271   20529
2  3018345        416       30000165          4239   20534
3  3018346        422       30000165          4271   20535
4  3018347        416       30000165          4239   20536

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 360) ---
Skipping value_counts (high-cardinality numeric: 360 unique)

--- Column: 'dungeonID' (Unique values: 169) ---
Skipping value_counts (high-cardinality numeric: 169 unique)

--- Column: 'solarSystemID' (Unique values: 128) ---
Skipping value_counts (high-cardinality numeric: 128 unique)

--- Column: 'spawnPointID' (Unique values: 169) ---
Skipping value_counts (high-cardinality numeric: 169 unique)

--- Column: 'typeID' (Unique values: 360) ---
Skipping value_counts (high-cardinality numeric: 360 unique)


================================================================================
--- 📊 Analyzing: ancestries.jsonl ---
================================================================================

Loaded 43 rows in 0.32s

[PRE-PROCESSING]
Flattening 'description' to English ('en') key...
Flattening 'name' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   _key              43 non-null     int64
 1   bloodlineID       43 non-null     int64
 2   charisma          43 non-null     int64
 3   description       43 non-null     object
 4   iconID            35 non-null     float64
 5   intelligence      43 non-null     int64
 6   memory            43 non-null     int64
 7   name              43 non-null     object
 8   perception        43 non-null     int64
 9   shortDescription  42 non-null     object
 10  willpower         43 non-null     int64
dtypes: float64(1), int64(7), object(3)
memory usage: 3.8+ KB


[HEAD]

   _key  bloodlineID  charisma                                        description  iconID  intelligence  memory                  name  perception                                   shortDescription  willpower
0     1            5         3  Holders, the major landholding class in Amarr ...  1641.0             0       0       Liberal Holders           0  Progressive members of the upper class who hav...          1
1     2            5         1  Some commoners manage to break out of Amarrian...  1642.0             0       3     Wealthy Commoners           0  Commoners who have transcended their class thr...          0
2     3            5         0  Many Amarrians still dream of the glory days o...  1643.0             0       0  Religious Reclaimers           0  Traditionalists who wish to see the Empire reg...          4
3     4            6         4  The Ni-Kunni, originally a slave race within t...  1644.0             0       0        Free Merchants           0  Roaming businessmen who find opportunity in an...          0
4     5            6         0  The Amarr Empire imposes strict trading rules ...  1645.0             1       0        Border Runners           3                Wily smugglers, bound by no border.          0

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 43) ---

      count
_key
1         1
2         1
3         1
4         1
5         1

--- Column: 'bloodlineID' (Unique values: 15) ---

             count
bloodlineID
5                3
6                3
2                3
1                3
7                3

--- Column: 'charisma' (Unique values: 5) ---

          count
charisma
0            29
4             6
1             4
2             3
3             1

--- Column: 'description' (Unique values: 43) ---

                                                    count
description
Holders, the major landholding class in Amarr s...      1
Some commoners manage to break out of Amarrian ...      1
Many Amarrians still dream of the glory days of...      1
The Ni-Kunni, originally a slave race within th...      1
The Amarr Empire imposes strict trading rules w...      1

--- Column: 'iconID' (Unique values: 35) ---

        count
iconID
1641.0      1
1642.0      1
1643.0      1
1644.0      1
1645.0      1

--- Column: 'intelligence' (Unique values: 5) ---

              count
intelligence
0                33
1                 3
2                 3
3                 2
4                 2

--- Column: 'memory' (Unique values: 5) ---

        count
memory
0          31
4           6
3           3
2           2
1           1

--- Column: 'name' (Unique values: 43) ---

                      count
name
Liberal Holders           1
Wealthy Commoners         1
Religious Reclaimers      1
Free Merchants            1
Border Runners            1

--- Column: 'perception' (Unique values: 5) ---

            count
perception
0              30
2               5
3               3
1               3
4               2

--- Column: 'shortDescription' (Unique values: 37) ---

                                                    count
shortDescription
                                                        6
Commoners who have transcended their class thro...      1
Traditionalists who wish to see the Empire rega...      1
Roaming businessmen who find opportunity in any...      1
Progressive members of the upper class who have...      1

--- Column: 'willpower' (Unique values: 5) ---

           count
willpower
0             27
2              5
4              5
3              4
1              2

================================================================================
--- 📊 Analyzing: bloodlines.jsonl ---
================================================================================

Loaded 18 rows in 0.16s

[PRE-PROCESSING]
Flattening 'description' to English ('en') key...
Flattening 'name' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   _key           18 non-null     int64
 1   charisma       18 non-null     int64
 2   corporationID  18 non-null     int64
 3   description    18 non-null     object
 4   iconID         15 non-null     float64
 5   intelligence   18 non-null     int64
 6   memory         18 non-null     int64
 7   name           18 non-null     object
 8   perception     18 non-null     int64
 9   raceID         18 non-null     int64
 10  willpower      18 non-null     int64
dtypes: float64(1), int64(8), object(2)
memory usage: 1.7+ KB


[HEAD]

   _key  charisma  corporationID                                        description  iconID  intelligence  memory       name  perception  raceID  willpower
0     1         6        1000006  The Deteis are regarded as the face of leaders...  1633.0             7       7     Deteis           5       1          5
1     2         6        1000009  Whether engaged in trade or combat, the Civire...  1631.0             5       4     Civire           9       1          6
2     3         6        1000046  Widely respected as some of the cluster's most...  1634.0             7       6  Sebiestor           5       2          6
3     4         6        1000049  A martial, strong-willed people, the Brutor ho...  1635.0             4       4     Brutor           9       2          7
4     5         3        1000066  True Amarrians are proud and supercilious, wit...  1628.0             7       6      Amarr           4       4         10

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 18) ---

      count
_key
1         1
2         1
3         1
4         1
5         1

--- Column: 'charisma' (Unique values: 7) ---

          count
charisma
6             5
8             3
9             3
3             2
5             2

--- Column: 'corporationID' (Unique values: 16) ---

               count
corporationID
1000293            3
1000006            1
1000046            1
1000009            1
1000066            1

--- Column: 'description' (Unique values: 18) ---

                                                    count
description
The Deteis are regarded as the face of leadersh...      1
Whether engaged in trade or combat, the Civire ...      1
Widely respected as some of the cluster's most ...      1
A martial, strong-willed people, the Brutor hol...      1
True Amarrians are proud and supercilious, with...      1

--- Column: 'iconID' (Unique values: 14) ---

        count
iconID
0.0         2
1633.0      1
1634.0      1
1635.0      1
1628.0      1

--- Column: 'intelligence' (Unique values: 8) ---

              count
intelligence
7                 5
5                 4
9                 3
8                 2
6                 1

--- Column: 'memory' (Unique values: 8) ---

        count
memory
4           4
6           4
7           3
9           3
10          1

--- Column: 'name' (Unique values: 18) ---

           count
name
Deteis         1
Civire         1
Sebiestor      1
Brutor         1
Amarr          1

--- Column: 'perception' (Unique values: 9) ---

            count
perception
9               5
7               3
5               2
4               2
8               2

--- Column: 'raceID' (Unique values: 6) ---

        count
raceID
1           3
2           3
4           3
8           3
16          3

--- Column: 'willpower' (Unique values: 9) ---

           count
willpower
6              4
9              4
8              2
4              2
7              2

================================================================================
--- 📊 Analyzing: blueprints.jsonl ---
================================================================================

Loaded 5031 rows in 0.57s

[PRE-PROCESSING]
Flattening 'activities' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5031 entries, 0 to 5030
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   _key                5031 non-null   int64
 1   activities          0 non-null      object
 2   blueprintTypeID     5031 non-null   int64
 3   maxProductionLimit  5031 non-null   int64
dtypes: int64(3), object(1)
memory usage: 157.3+ KB


[HEAD]

   _key activities  blueprintTypeID  maxProductionLimit
0   681       None              681                 300
1   682       None              682                 300
2   683       None              683                  30
3   684       None              684                  30
4   685       None              685                  30

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 5031) ---
Skipping value_counts (high-cardinality numeric: 5031 unique)

--- Column: 'activities' (is empty or all null) ---

--- Column: 'blueprintTypeID' (Unique values: 5031) ---
Skipping value_counts (high-cardinality numeric: 5031 unique)

--- Column: 'maxProductionLimit' (Unique values: 28) ---

                    count
maxProductionLimit
10                   1021
1                     785
200                   502
100                   442
5                     321

================================================================================
--- 📊 Analyzing: categories.jsonl ---
================================================================================

Loaded 47 rows in 0.15s

[PRE-PROCESSING]
Flattening 'name' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   _key       47 non-null     int64
 1   name       47 non-null     object
 2   published  47 non-null     bool
 3   iconID     13 non-null     float64
dtypes: bool(1), float64(1), int64(1), object(1)
memory usage: 1.3+ KB


[HEAD]

   _key       name  published  iconID
0     0    #System      False     NaN
1     1      Owner      False     NaN
2     2  Celestial       True     NaN
3     3    Station      False     NaN
4     4   Material       True    22.0

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 47) ---

      count
_key
0         1
1         1
2         1
3         1
4         1

--- Column: 'name' (Unique values: 47) ---

           count
name
#System        1
Owner          1
Celestial      1
Station        1
Material       1

--- Column: 'published' (Unique values: 2) ---

           count
published
True          33
False         14

--- Column: 'iconID' (Unique values: 6) ---

        count
iconID
0.0         7
33.0        2
22.0        1
67.0        1
21.0        1

================================================================================
--- 📊 Analyzing: certificates.jsonl ---
================================================================================

Loaded 134 rows in 0.12s

[PRE-PROCESSING]
Flattening 'description' to English ('en') key...
Flattening 'name' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   _key            134 non-null    int64
 1   description     134 non-null    object
 2   groupID         134 non-null    int64
 3   name            134 non-null    object
 4   recommendedFor  79 non-null     object
 5   skillTypes      134 non-null    object
dtypes: int64(2), object(4)
memory usage: 6.4+ KB


[HEAD]

   _key                                        description  groupID                   name                                     recommendedFor                                         skillTypes
0    50  This certificate represents a level of compete...      255    Small Energy Turret  [73789, 42685, 33079, 37453, 85062, 589, 591, ...  [{'_key': 3300, 'advanced': 5, 'basic': 3, 'el...
1    64  This certificate represents a level of compete...      255   Medium Energy Turret  [24696, 33155, 624, 29337, 33470, 33553, 33639...  [{'_key': 3300, 'advanced': 5, 'basic': 3, 'el...
2    65  This certificate represents a level of compete...      255    Large Energy Turret  [24692, 4302, 47466, 642, 33472, 33623, 33625,...  [{'_key': 3300, 'advanced': 5, 'basic': 5, 'el...
3    66  This certificate represents a level of compete...      255  Capital Energy Turret                [73790, 42241, 42243, 19720, 11567]  [{'_key': 3300, 'advanced': 5, 'basic': 5, 'el...
4    67  This certificate represents a level of compete...      255    Small Hybrid Turret  [73795, 73796, 32840, 32842, 32844, 32846, 328...  [{'_key': 3300, 'advanced': 5, 'basic': 3, 'el...

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 134) ---
Skipping value_counts (high-cardinality numeric: 134 unique)

--- Column: 'description' (Unique values: 134) ---

                                                    count
description
This certificate represents a level of competen...      1
This certificate represents a level of competen...      1
This certificate represents a level of competen...      1
This certificate represents a level of competen...      1
This certificate represents a level of competen...      1

--- Column: 'groupID' (Unique values: 18) ---

         count
groupID
270         38
255         20
268         11
272          8
256          7

--- Column: 'name' (Unique values: 134) ---

                       count
name
Small Energy Turret        1
Medium Energy Turret       1
Large Energy Turret        1
Capital Energy Turret      1
Small Hybrid Turret        1

--- Column: 'recommendedFor' (Contains unhashable lists) ---
Sample value: [73789, 42685, 33079, 37453, 85062, 589, 591, 596, 597, 615, 33655, 11184, 35779, 33879, 11393, 33657, 37481, 42246, 17703, 58745, 3516, 17924, 17926, 34317, 44993, 11940, 11942, 77114, 16236]

--- Column: 'skillTypes' (Contains unhashable lists) ---
Sample value: [{'_key': 3300, 'advanced': 5, 'basic': 3, 'elite': 5, 'improved': 4, 'standard': 4}, {'_key': 3303, 'advanced': 5, 'basic': 1, 'elite': 5, 'improved': 4, 'standard': 3}, {'_key': 3310, 'advanced': 4, 'basic': 1, 'elite': 5, 'improved': 4, 'standard': 3}, {'_key': 3311, 'advanced': 4, 'basic': 1, 'elite': 5, 'improved': 4, 'standard': 3}, {'_key': 3312, 'advanced': 4, 'basic': 1, 'elite': 5, 'improved': 4, 'standard': 3}, {'_key': 3315, 'advanced': 4, 'basic': 0, 'elite': 5, 'improved': 4, 'standard': 3}, {'_key': 3316, 'advanced': 4, 'basic': 1, 'elite': 5, 'improved': 4, 'standard': 3}, {'_key': 3317, 'advanced': 4, 'basic': 0, 'elite': 5, 'improved': 4, 'standard': 3}, {'_key': 11083, 'advanced': 1, 'basic': 0, 'elite': 5, 'improved': 0, 'standard': 0}, {'_key': 12213, 'advanced': 1, 'basic': 0, 'elite': 5, 'improved': 0, 'standard': 0}]


================================================================================
--- 📊 Analyzing: characterAttributes.jsonl ---
================================================================================

Loaded 5 rows in 0.13s

[PRE-PROCESSING]
Flattening 'name' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   _key              5 non-null      int64
 1   description       5 non-null      object
 2   iconID            5 non-null      int64
 3   name              5 non-null      object
 4   notes             5 non-null      object
 5   shortDescription  5 non-null      object
dtypes: int64(2), object(4)
memory usage: 372.0+ bytes


[HEAD]

   _key                                        description  iconID          name                                              notes                                   shortDescription
0     1  <b>Intelligence is a measure of a pilot's capa...    1380  Intelligence  Intelligence does not increase the chance of a...  A measure of individual capacity for learning,...
1     2  <b>Charisma is personal attractiveness or magn...    1378      Charisma  Charisma does not increase the chances of achi...  Personal attractiveness or magnetism that prom...
2     3  <b>Perception measures a pilot's ability to as...    1382    Perception  Perception does not increase the chances of ac...  A pilot's ability to assimilate information fr...
3     4  <b>Memory is the mental capacity to retain and...    1381        Memory  Memory does not increase the chances of achiev...  The mental capacity to retain and recall facts...
4     5  <b>Willpower is resolute control over one's ow...    1379     Willpower  Willpower does not increase the chances of ach...  Rigid self-control over personal actions, impu...

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 5) ---

      count
_key
1         1
2         1
3         1
4         1
5         1

--- Column: 'description' (Unique values: 5) ---

                                                    count
description
<b>Intelligence is a measure of a pilot's capac...      1
<b>Charisma is personal attractiveness or magne...      1
<b>Perception measures a pilot's ability to ass...      1
<b>Memory is the mental capacity to retain and ...      1
<b>Willpower is resolute control over one's own...      1

--- Column: 'iconID' (Unique values: 5) ---

        count
iconID
1380        1
1378        1
1382        1
1381        1
1379        1

--- Column: 'name' (Unique values: 5) ---

              count
name
Intelligence      1
Charisma          1
Perception        1
Memory            1
Willpower         1

--- Column: 'notes' (Unique values: 5) ---

                                                    count
notes
Intelligence does not increase the chance of ac...      1
Charisma does not increase the chances of achie...      1
Perception does not increase the chances of ach...      1
Memory does not increase the chances of achievi...      1
Willpower does not increase the chances of achi...      1

--- Column: 'shortDescription' (Unique values: 5) ---

                                                    count
shortDescription
A measure of individual capacity for learning, ...      1
Personal attractiveness or magnetism that promo...      1
A pilot's ability to assimilate information fro...      1
The mental capacity to retain and recall facts ...      1
Rigid self-control over personal actions, impul...      1

================================================================================
--- 📊 Analyzing: contrabandTypes.jsonl ---
================================================================================

Loaded 8 rows in 0.31s

[PRE-PROCESSING]
No dictionary columns found to flatten.

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   _key      8 non-null      int64
 1   factions  8 non-null      object
dtypes: int64(1), object(1)
memory usage: 260.0+ bytes


[HEAD]

   _key                                           factions
0  3713  [{'_key': 500005, 'attackMinSec': 1.1, 'confis...
1  3721  [{'_key': 500001, 'attackMinSec': 1.1, 'confis...
2  3727  [{'_key': 500003, 'attackMinSec': 1.1, 'confis...
3  3729  [{'_key': 500001, 'attackMinSec': 1.1, 'confis...
4  9844  [{'_key': 500001, 'attackMinSec': 1.1, 'confis...

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 8) ---

      count
_key
3713      1
3721      1
3727      1
3729      1
9844      1

--- Column: 'factions' (Contains unhashable lists) ---
Sample value: [{'_key': 500005, 'attackMinSec': 1.1, 'confiscateMinSec': 0.4, 'fineByValue': 4.5, 'standingLoss': 0.2}, {'_key': 500017, 'attackMinSec': 1.1, 'confiscateMinSec': 0.5, 'fineByValue': 1.5, 'standingLoss': 0.05}]


================================================================================
--- 📊 Analyzing: controlTowerResources.jsonl ---
================================================================================

Loaded 44 rows in 0.11s

[PRE-PROCESSING]
No dictionary columns found to flatten.

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   _key       44 non-null     int64
 1   resources  44 non-null     object
dtypes: int64(1), object(1)
memory usage: 836.0+ bytes


[HEAD]

    _key                                          resources
0   4361  [{'purpose': 4, 'quantity': 200, 'resourceType...
1  12235  [{'purpose': 4, 'quantity': 400, 'resourceType...
2  12236  [{'purpose': 4, 'quantity': 400, 'resourceType...
3  16213  [{'purpose': 4, 'quantity': 400, 'resourceType...
4  16214  [{'purpose': 4, 'quantity': 400, 'resourceType...

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 44) ---

       count
_key
4361       1
12235      1
12236      1
16213      1
16214      1

--- Column: 'resources' (Contains unhashable lists) ---
Sample value: [{'purpose': 4, 'quantity': 200, 'resourceTypeID': 16275}, {'purpose': 1, 'quantity': 1, 'resourceTypeID': 4051}]


================================================================================
--- 📊 Analyzing: corporationActivities.jsonl ---
================================================================================

Loaded 20 rows in 0.15s

[PRE-PROCESSING]
Flattening 'name' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   _key    20 non-null     int64
 1   name    20 non-null     object
dtypes: int64(1), object(1)
memory usage: 452.0+ bytes


[HEAD]

   _key          name
0     1   Agriculture
1     2  Construction
2     3        Mining
3     4      Chemical
4     5      Military

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 20) ---

      count
_key
1         1
2         1
3         1
4         1
5         1

--- Column: 'name' (Unique values: 20) ---

              count
name
Agriculture       1
Construction      1
Mining            1
Chemical          1
Military          1

================================================================================
--- 📊 Analyzing: dbuffCollections.jsonl ---
================================================================================

Loaded 152 rows in 0.12s

[PRE-PROCESSING]
Flattening 'displayName' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 10 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   _key                            152 non-null    int64
 1   aggregateMode                   152 non-null    object
 2   developerDescription            152 non-null    object
 3   itemModifiers                   97 non-null     object
 4   locationGroupModifiers          9 non-null      object
 5   locationModifiers               5 non-null      object
 6   locationRequiredSkillModifiers  49 non-null     object
 7   operationName                   152 non-null    object
 8   showOutputValueInUI             152 non-null    object
 9   displayName                     144 non-null    object
dtypes: int64(1), object(9)
memory usage: 12.0+ KB


[HEAD]

   _key aggregateMode         developerDescription                                      itemModifiers                             locationGroupModifiers                                  locationModifiers                     locationRequiredSkillModifiers operationName showOutputValueInUI       displayName
0     1       Maximum   [PROTOTYPE]Test Multi Buff  [{'dogmaAttributeID': 37}, {'dogmaAttributeID'...  [{'dogmaAttributeID': 20, 'groupID': 46}, {'do...  [{'dogmaAttributeID': 68}, {'dogmaAttributeID'...  [{'dogmaAttributeID': 6, 'skillID': 3427}, {'d...       PostMul          ShowNormal               NaN
1     2       Maximum  [PROTOTYPE]Test Boost Speed                         [{'dogmaAttributeID': 37}]                                                NaN                                                NaN                                                NaN   PostPercent          ShowNormal               NaN
2     3       Minimum             Velocity penalty                         [{'dogmaAttributeID': 37}]                                                NaN                                                NaN                                                NaN   PostPercent          ShowNormal  Velocity penalty
3     4       Maximum                 Warp penalty                        [{'dogmaAttributeID': 104}]                                                NaN                                                NaN                                                NaN        ModAdd                Hide      Warp penalty
4     5       Maximum               Disallow Cloak                       [{'dogmaAttributeID': 2454}]                                                NaN                                                NaN                                                NaN        ModAdd                Hide    Disallow Cloak

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 152) ---
Skipping value_counts (high-cardinality numeric: 152 unique)

--- Column: 'aggregateMode' (Unique values: 2) ---

               count
aggregateMode
Maximum           97
Minimum           55

--- Column: 'developerDescription' (Unique values: 152) ---

                             count
developerDescription
[PROTOTYPE]Test Multi Buff       1
[PROTOTYPE]Test Boost Speed      1
Velocity penalty                 1
Warp penalty                     1
Disallow Cloak                   1

--- Column: 'itemModifiers' (Contains unhashable lists) ---
Sample value: [{'dogmaAttributeID': 37}, {'dogmaAttributeID': 76}]

--- Column: 'locationGroupModifiers' (Contains unhashable lists) ---
Sample value: [{'dogmaAttributeID': 20, 'groupID': 46}, {'dogmaAttributeID': 105, 'groupID': 52}]

--- Column: 'locationModifiers' (Contains unhashable lists) ---
Sample value: [{'dogmaAttributeID': 68}, {'dogmaAttributeID': 84}]

--- Column: 'locationRequiredSkillModifiers' (Contains unhashable lists) ---
Sample value: [{'dogmaAttributeID': 6, 'skillID': 3427}, {'dogmaAttributeID': 54, 'skillID': 3305}]

--- Column: 'operationName' (Unique values: 4) ---

                count
operationName
PostPercent       127
ModAdd             16
PostAssignment      7
PostMul             2

--- Column: 'showOutputValueInUI' (Unique values: 3) ---

                     count
showOutputValueInUI
ShowNormal             116
ShowInverted            22
Hide                    14

--- Column: 'displayName' (Unique values: 120) ---

                         count
displayName
Signature Radius bonus       3
Ship Velocity                3
Ship Inertia                 3
Scan Resolution bonus        2
Scan Resolution penalty      2

================================================================================
--- 📊 Analyzing: dogmaAttributeCategories.jsonl ---
================================================================================

Loaded 37 rows in 0.14s

[PRE-PROCESSING]
No dictionary columns found to flatten.

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   _key         37 non-null     int64
 1   description  36 non-null     object
 2   name         37 non-null     object
dtypes: int64(1), object(2)
memory usage: 1020.0+ bytes


[HEAD]

   _key                     description       name
0     1  Fitting capabilities of a ship    Fitting
1     2      Shield attributes of ships     Shield
2     3       Armor attributes of ships      Armor
3     4   Structure attributes of ships  Structure
4     5  Capacitor attributes for ships  Capacitor

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 37) ---

      count
_key
1         1
2         1
3         1
4         1
5         1

--- Column: 'description' (Unique values: 36) ---

                                count
description
Fitting capabilities of a ship      1
Shield attributes of ships          1
Armor attributes of ships           1
Structure attributes of ships       1
Capacitor attributes for ships      1

--- Column: 'name' (Unique values: 37) ---

           count
name
Fitting        1
Shield         1
Armor          1
Structure      1
Capacitor      1

================================================================================
--- 📊 Analyzing: dogmaAttributes.jsonl ---
================================================================================

Loaded 2775 rows in 0.19s

[PRE-PROCESSING]
Flattening 'displayName' to English ('en') key...
Flattening 'tooltipDescription' to English ('en') key...
Flattening 'tooltipTitle' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2775 entries, 0 to 2774
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   _key                  2775 non-null   int64
 1   attributeCategoryID   2600 non-null   float64
 2   dataType              2775 non-null   int64
 3   defaultValue          2775 non-null   float64
 4   description           2606 non-null   object
 5   displayWhenZero       2775 non-null   bool
 6   highIsGood            2775 non-null   bool
 7   name                  2775 non-null   object
 8   published             2775 non-null   bool
 9   stackable             2775 non-null   bool
 10  displayName           1224 non-null   object
 11  iconID                1342 non-null   float64
 12  tooltipDescription    66 non-null     object
 13  tooltipTitle          68 non-null     object
 14  unitID                1323 non-null   float64
 15  chargeRechargeTimeID  6 non-null      float64
 16  maxAttributeID        27 non-null     float64
 17  minAttributeID        1 non-null      float64
dtypes: bool(4), float64(7), int64(2), object(5)
memory usage: 314.5+ KB


[HEAD]

   _key  attributeCategoryID  dataType  defaultValue                                        description  displayWhenZero  highIsGood           name  published  stackable      displayName  iconID                                 tooltipDescription   tooltipTitle  unitID  chargeRechargeTimeID  maxAttributeID  minAttributeID
0     2                  9.0         0           0.0           Boolean to store status of online effect            False        True       isOnline      False       True              NaN     NaN                                                NaN            NaN     NaN                   NaN             NaN             NaN
1     3                  7.0         1           0.0           current structure damage dealt to module            False       False         damage       True       True      Item Damage  1386.0                                      Module Damage  Module Damage   113.0                   NaN             NaN             NaN
2     4                  4.0         9           0.0              Integer that describes the types mass            False        True           mass       True      False             Mass    76.0  Affects acceleration and turning speed negativ...           Mass     2.0                   NaN             NaN             NaN
3     6                  5.0         5           0.0  The amount of charge used from the capacitor f...            False       False  capacitorNeed       True       True  Activation Cost  1400.0                                                NaN            NaN   114.0                   NaN             NaN             NaN
4     8                  9.0         4           0.0                                                tbd            False        True       minRange      False       True              NaN  1391.0                                                NaN            NaN     NaN                   NaN             NaN             NaN

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 2775) ---
Skipping value_counts (high-cardinality numeric: 2775 unique)

--- Column: 'attributeCategoryID' (Unique values: 37) ---

                     count
attributeCategoryID
7.0                    862
9.0                    516
37.0                   325
4.0                    112
42.0                    98

--- Column: 'dataType' (Unique values: 14) ---

          count
dataType
5          1863
4           648
11           66
12           46
3            42

--- Column: 'defaultValue' (Unique values: 62) ---

              count
defaultValue
0.0            2261
1.0             340
100.0            23
5.0              14
10000.0          13

--- Column: 'description' (Unique values: 1375) ---

                                             count
description
                                               980
Multiplied by Amarr Carrier skill level.        13
Multiplied by Caldari Carrier skill level.      13
Multiplied by Gallente Carrier skill level.     13
Multiplied by Minmatar Carrier skill level.     13

--- Column: 'displayWhenZero' (Unique values: 2) ---

                 count
displayWhenZero
False             2767
True                 8

--- Column: 'highIsGood' (Unique values: 2) ---

            count
highIsGood
True         2515
False         260

--- Column: 'name' (Unique values: 2773) ---

                            count
name
cynoJammerActivationDelay       2
902                             2
scanResolutionBonusInterim      1
remoteResistanceID              1
maxRangeBonusInterim            1

--- Column: 'published' (Unique values: 2) ---

           count
published
False       1528
True        1247

--- Column: 'stackable' (Unique values: 2) ---

           count
stackable
True        2540
False        235

--- Column: 'displayName' (Unique values: 1001) ---

                            count
displayName
Can be fitted to               29
Special Ability Bonus          13
Duration                       13
Optimal Range                   7
Used with (Launcher Group)      6

--- Column: 'iconID' (Unique values: 88) ---

        count
iconID
0.0       726
1392.0     73
1391.0     57
1389.0     35
1443.0     33

--- Column: 'tooltipDescription' (Unique values: 63) ---

                                                    count
tooltipDescription
Larger values reduce the chance of being jammed...      4
Affects acceleration and turning speed negative...      1
Module Damage                                           1
The maximum velocity that can be achieved in su...      1
The maximum volume of items that can be carried...      1

--- Column: 'tooltipTitle' (Unique values: 67) ---

                     count
tooltipTitle
Area Effect Radius       2
Mass                     1
Module Damage            1
Structure Hitpoints      1
Maximum Velocity         1

--- Column: 'unitID' (Unique values: 45) ---

        count
unitID
105.0     379
1.0       127
104.0      98
101.0      91
113.0      56

--- Column: 'chargeRechargeTimeID' (Unique values: 6) ---

                      count
chargeRechargeTimeID
55.0                      1
113.0                     1
111.0                     1
109.0                     1
110.0                     1

--- Column: 'maxAttributeID' (Unique values: 14) ---

                count
maxAttributeID
5732.0              5
1528.0              4
1527.0              4
1529.0              4
482.0               1

--- Column: 'minAttributeID' (Unique values: 1) ---

                count
minAttributeID
2266.0              1

================================================================================
--- 📊 Analyzing: dogmaEffects.jsonl ---
================================================================================

Loaded 3286 rows in 0.37s

[PRE-PROCESSING]
Flattening 'description' to English ('en') key...
Flattening 'displayName' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3286 entries, 0 to 3285
Data columns (total 26 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   _key                            3286 non-null   int64
 1   disallowAutoRepeat              3286 non-null   bool
 2   dischargeAttributeID            169 non-null    float64
 3   durationAttributeID             221 non-null    float64
 4   effectCategoryID                3286 non-null   int64
 5   electronicChance                3286 non-null   bool
 6   guid                            1626 non-null   object
 7   isAssistance                    3286 non-null   bool
 8   isOffensive                     3286 non-null   bool
 9   isWarpSafe                      3286 non-null   bool
 10  name                            3286 non-null   object
 11  propulsionChance                3286 non-null   bool
 12  published                       3286 non-null   bool
 13  rangeChance                     3286 non-null   bool
 14  distribution                    74 non-null     float64
 15  falloffAttributeID              51 non-null     float64
 16  rangeAttributeID                194 non-null    float64
 17  trackingSpeedAttributeID        6 non-null      float64
 18  description                     745 non-null    object
 19  displayName                     69 non-null     object
 20  iconID                          1268 non-null   float64
 21  modifierInfo                    3071 non-null   object
 22  npcUsageChanceAttributeID       7 non-null      float64
 23  npcActivationChanceAttributeID  19 non-null     float64
 24  fittingUsageChanceAttributeID   12 non-null     float64
 25  resistanceAttributeID           39 non-null     float64
dtypes: bool(8), float64(11), int64(2), object(5)
memory usage: 487.9+ KB


[HEAD]

   _key  disallowAutoRepeat  dischargeAttributeID  durationAttributeID  effectCategoryID  electronicChance                       guid  isAssistance  isOffensive  isWarpSafe              name  propulsionChance  published  rangeChance  distribution  falloffAttributeID  rangeAttributeID  trackingSpeedAttributeID                 description displayName  iconID modifierInfo  npcUsageChanceAttributeID  npcActivationChanceAttributeID  fittingUsageChanceAttributeID  resistanceAttributeID
0     4               False                   6.0                 73.0                 1             False     effects.ShieldBoosting         False        False        True    shieldBoosting             False      False        False           NaN                 NaN               NaN                       NaN                         NaN         NaN     NaN          NaN                        NaN                             NaN                            NaN                    NaN
1     9               False                   NaN                  NaN                 2             False  effects.MissileDeployment         False         True       False  missileLaunching             False      False        False           NaN                 NaN               NaN                       NaN                         NaN         NaN     NaN          NaN                        NaN                             NaN                            NaN                    NaN
2    10               False                   6.0                 51.0                 2             False              effects.Laser         False         True       False      targetAttack             False      False        False           2.0               158.0              54.0                     160.0                         NaN         NaN     NaN          NaN                        NaN                             NaN                            NaN                    NaN
3    11               False                   NaN                  NaN                 0             False                                    False        False       False           loPower             False       True        False           NaN                 NaN               NaN                       NaN   Requires a low power slot   Low power   295.0          NaN                        NaN                             NaN                            NaN                    NaN
4    12               False                   NaN                  NaN                 0             False                                    False        False       False           hiPower             False       True        False           NaN                 NaN               NaN                       NaN  Requires a high power slot  High power   293.0          NaN                        NaN                             NaN                            NaN                    NaN

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 3286) ---
Skipping value_counts (high-cardinality numeric: 3286 unique)

--- Column: 'disallowAutoRepeat' (Unique values: 1) ---

                    count
disallowAutoRepeat
False                3286

--- Column: 'dischargeAttributeID' (Unique values: 24) ---

                      count
dischargeAttributeID
6.0                     142
515.0                     2
2637.0                    2
1319.0                    2
2674.0                    2

--- Column: 'durationAttributeID' (Unique values: 62) ---

                     count
durationAttributeID
73.0                   129
51.0                     9
636.0                    6
630.0                    5
505.0                    4

--- Column: 'effectCategoryID' (Unique values: 8) ---

                  count
effectCategoryID
0                  2797
1                   142
2                   120
7                   109
4                    93

--- Column: 'electronicChance' (Unique values: 2) ---

                  count
electronicChance
False              3284
True                  2

--- Column: 'guid' (Unique values: 78) ---

                                         count
guid
                                          1195
None                                       235
effects.Laser                               15
effects.ElectronicAttributeModifyTarget     11
effects.WarpScramble                         8

--- Column: 'isAssistance' (Unique values: 2) ---

              count
isAssistance
False          3251
True             35

--- Column: 'isOffensive' (Unique values: 2) ---

             count
isOffensive
False         3175
True           111

--- Column: 'isWarpSafe' (Unique values: 2) ---

            count
isWarpSafe
False        3201
True           85

--- Column: 'name' (Unique values: 3285) ---

                                                count
name
battlecruiserSkillLevelPreMulShipBonusCBC3Ship      2
doomsdayAOEBubble                                   1
emergencyHullEnergizer                              1
fighterAbilityLaunchBomb                            1
modifyEnergyWarfareResistance                       1

--- Column: 'propulsionChance' (Unique values: 2) ---

                  count
propulsionChance
False              3285
True                  1

--- Column: 'published' (Unique values: 2) ---

           count
published
False       3172
True         114

--- Column: 'rangeChance' (Unique values: 2) ---

             count
rangeChance
False         3278
True             8

--- Column: 'distribution' (Unique values: 2) ---

              count
distribution
2.0              40
1.0              34

--- Column: 'falloffAttributeID' (Unique values: 22) ---

                    count
falloffAttributeID
2044.0                 22
158.0                   9
328.0                   1
950.0                   1
954.0                   1

--- Column: 'rangeAttributeID' (Unique values: 37) ---

                  count
rangeAttributeID
54.0                142
103.0                 7
99.0                  4
142.0                 3
936.0                 2

--- Column: 'trackingSpeedAttributeID' (Unique values: 1) ---

                          count
trackingSpeedAttributeID
160.0                         6

--- Column: 'description' (Unique values: 67) ---

                                                    count
description
Automatically generated effect                        668
Anchoring this object in space.                         5
Attempts to prevent the target from warping.            3
Structure Rig Material effect on Manufacturing ...      3
this is the online effect for structures                2

--- Column: 'displayName' (Unique values: 57) ---

                    count
displayName
Warp Scramble           4
anchoring               3
unanchoring             3
Max Velocity Bonus      3
modifyTargetSpeed       2

--- Column: 'iconID' (Unique values: 17) ---

        count
iconID
0.0      1249
1389.0      3
1384.0      2
295.0       1
293.0       1

--- Column: 'modifierInfo' (Contains unhashable lists) ---
Sample value: [{'domain': 'shipID', 'func': 'ItemModifier', 'modifiedAttributeID': 263, 'modifyingAttributeID': 72, 'operation': 2}]

--- Column: 'npcUsageChanceAttributeID' (Unique values: 3) ---

                           count
npcUsageChanceAttributeID
504.0                          4
512.0                          2
1664.0                         1

--- Column: 'npcActivationChanceAttributeID' (Unique values: 17) ---

                                count
npcActivationChanceAttributeID
930.0                               3
932.0                               1
935.0                               1
1007.0                              1
1006.0                              1

--- Column: 'fittingUsageChanceAttributeID' (Unique values: 5) ---

                               count
fittingUsageChanceAttributeID
1093.0                             4
1091.0                             2
1089.0                             2
1092.0                             2
1090.0                             2

--- Column: 'resistanceAttributeID' (Unique values: 8) ---

                       count
resistanceAttributeID
2116.0                    13
2045.0                     8
2113.0                     7
2253.0                     7
2135.0                     1

================================================================================
--- 📊 Analyzing: dogmaUnits.jsonl ---
================================================================================

Loaded 60 rows in 0.14s

[PRE-PROCESSING]
Flattening 'description' to English ('en') key...
Flattening 'displayName' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   _key         60 non-null     int64
 1   description  44 non-null     object
 2   displayName  56 non-null     object
 3   name         60 non-null     object
dtypes: int64(1), object(3)
memory usage: 2.0+ KB


[HEAD]

   _key description displayName              name
0     1       Meter           m            Length
1     2    Kilogram          kg              Mass
2     3      Second         sec              Time
3     4      Ampere           A  Electric Current
4     5      Kelvin           K       Temperature

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 60) ---

      count
_key
1         1
2         1
3         1
4         1
5         1

--- Column: 'description' (Unique values: 44) ---

             count
description
Meter            1
Kilogram         1
Second           1
Ampere           1
Kelvin           1

--- Column: 'displayName' (Unique values: 47) ---

             count
displayName
%                8
m/sec            2
sec              2
A                1
K                1

--- Column: 'name' (Unique values: 60) ---

                  count
name
Length                1
Mass                  1
Time                  1
Electric Current      1
Temperature           1

================================================================================
--- 📊 Analyzing: dynamicItemAttributes.jsonl ---
================================================================================

Loaded 376 rows in 0.12s

[PRE-PROCESSING]
No dictionary columns found to flatten.

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 376 entries, 0 to 375
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   _key                376 non-null    int64
 1   attributeIDs        376 non-null    object
 2   inputOutputMapping  376 non-null    object
dtypes: int64(1), object(2)
memory usage: 8.9+ KB


[HEAD]

    _key                                       attributeIDs                                 inputOutputMapping
0  47297  [{'_key': 6, 'max': 1.4, 'min': 0.600000000000...  [{'applicableTypes': [5975, 12052, 12076, 1411...
1  47299  [{'_key': 6, 'max': 1.2, 'min': 0.85}, {'_key'...  [{'applicableTypes': [5945, 12054, 12084, 1411...
2  47699  [{'_key': 6, 'max': 1.8, 'min': 1.4}, {'_key':...  [{'applicableTypes': [28514, 41038, 14652, 146...
3  47700  [{'_key': 6, 'max': 2.5, 'min': 0.9}, {'_key':...  [{'applicableTypes': [28514, 15419, 41038, 146...
4  47701  [{'_key': 6, 'max': 2.0, 'min': 1.0}, {'_key':...  [{'applicableTypes': [28514, 15419, 41038, 146...

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 376) ---
Skipping value_counts (high-cardinality numeric: 376 unique)

--- Column: 'attributeIDs' (Contains unhashable lists) ---
Sample value: [{'_key': 6, 'max': 1.4, 'min': 0.6000000000000001}, {'_key': 20, 'max': 1.1, 'min': 0.9}, {'_key': 30, 'max': 1.5, 'min': 0.8}, {'_key': 50, 'max': 1.5, 'min': 0.8}, {'_key': 554, 'max': 1.3, 'min': 0.7000000000000001}]

--- Column: 'inputOutputMapping' (Contains unhashable lists) ---
Sample value: [{'applicableTypes': [5975, 12052, 12076, 14118, 14120, 15751, 15764, 19315, 19321, 19327, 19339, 19345, 19351, 21478, 35659, 35660, 84964, 84965], 'resultingType': 47408}]


================================================================================
--- 📊 Analyzing: factions.jsonl ---
================================================================================

Loaded 27 rows in 0.15s

[PRE-PROCESSING]
Flattening 'description' to English ('en') key...
Flattening 'name' to English ('en') key...
Flattening 'shortDescription' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   _key                  27 non-null     int64
 1   corporationID         26 non-null     float64
 2   description           27 non-null     object
 3   flatLogo              18 non-null     object
 4   flatLogoWithName      6 non-null      object
 5   iconID                27 non-null     int64
 6   memberRaces           27 non-null     object
 7   militiaCorporationID  6 non-null      float64
 8   name                  27 non-null     object
 9   shortDescription      4 non-null      object
 10  sizeFactor            27 non-null     int64
 11  solarSystemID         27 non-null     int64
 12  uniqueName            27 non-null     bool
dtypes: bool(1), float64(2), int64(4), object(6)
memory usage: 2.7+ KB


[HEAD]

     _key  corporationID                                        description       flatLogo         flatLogoWithName  iconID memberRaces  militiaCorporationID                 name                                   shortDescription  sizeFactor  solarSystemID  uniqueName
0  500001      1000035.0  The Caldari State is ruled by several mega-cor...   caldari_logo   caldari_logo_w_letters    1439         [1]             1000180.0        Caldari State  In the Caldari State, there is no higher honor...           5       30000145        True
1  500002      1000051.0  The Minmatar Republic was formed over a centur...  minmatar_logo  minmatar_logo_w_letters    1440         [2]             1000182.0    Minmatar Republic  The Minmatar Republic seeks to end tyranny and...           5       30002544        True
2  500003      1000084.0  The largest of the five main empires, the Amar...     amarr_logo     amarr_logo_w_letters    1442         [4]             1000179.0         Amarr Empire  The Amarr Empire is built upon faith in the On...           5       30002187        True
3  500004      1000120.0  The Gallente Federation encompasses several ra...  gallente_logo  gallente_logo_w_letters    1441         [8]             1000181.0  Gallente Federation  The Gallente Federation prizes the pursuit of ...           5       30004993        True
4  500005      1000149.0  The Jove Empire is isolated from the rest of t...            NaN                      NaN    2195        [16]                   NaN          Jove Empire                                                NaN           5       30001642        True

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 27) ---

        count
_key
500001      1
500002      1
500003      1
500004      1
500005      1

--- Column: 'corporationID' (Unique values: 26) ---

               count
corporationID
1000035.0          1
1000051.0          1
1000084.0          1
1000120.0          1
1000149.0          1

--- Column: 'description' (Unique values: 27) ---

                                                    count
description
The Caldari State is ruled by several mega-corp...      1
The Minmatar Republic was formed over a century...      1
The largest of the five main empires, the Amarr...      1
The Gallente Federation encompasses several rac...      1
The Jove Empire is isolated from the rest of th...      1

--- Column: 'flatLogo' (Unique values: 18) ---

               count
flatLogo
caldari_logo       1
minmatar_logo      1
amarr_logo         1
gallente_logo      1
concord_logo       1

--- Column: 'flatLogoWithName' (Unique values: 6) ---

                         count
flatLogoWithName
caldari_logo_w_letters       1
minmatar_logo_w_letters      1
amarr_logo_w_letters         1
gallente_logo_w_letters      1
guristas_logo_w_letters      1

--- Column: 'iconID' (Unique values: 25) ---

        count
iconID
1441        2
20996       2
1439        1
1442        1
1440        1

--- Column: 'memberRaces' (Contains unhashable lists) ---
Sample value: [1]

--- Column: 'militiaCorporationID' (Unique values: 6) ---

                      count
militiaCorporationID
1000180.0                 1
1000182.0                 1
1000179.0                 1
1000181.0                 1
1000437.0                 1

--- Column: 'name' (Unique values: 27) ---

                     count
name
Caldari State            1
Minmatar Republic        1
Amarr Empire             1
Gallente Federation      1
Jove Empire              1

--- Column: 'shortDescription' (Unique values: 4) ---

                                                    count
shortDescription
In the Caldari State, there is no higher honor ...      1
The Minmatar Republic seeks to end tyranny and ...      1
The Amarr Empire is built upon faith in the One...      1
The Gallente Federation prizes the pursuit of i...      1

--- Column: 'sizeFactor' (Unique values: 4) ---

            count
sizeFactor
5               9
4               8
3               7
0               3

--- Column: 'solarSystemID' (Unique values: 23) ---

               count
solarSystemID
30005286           4
30005204           2
30002544           1
30002187           1
30004993           1

--- Column: 'uniqueName' (Unique values: 2) ---

            count
uniqueName
True           23
False           4

================================================================================
--- 📊 Analyzing: graphics.jsonl ---
================================================================================

Loaded 5503 rows in 0.18s

[PRE-PROCESSING]
No dictionary columns found to flatten.

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5503 entries, 0 to 5502
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   _key              5503 non-null   int64
 1   graphicFile       2351 non-null   object
 2   iconFolder        2565 non-null   object
 3   sofFactionName    3658 non-null   object
 4   sofHullName       3080 non-null   object
 5   sofRaceName       3853 non-null   object
 6   sofMaterialSetID  90 non-null     float64
 7   sofLayout         53 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 344.1+ KB


[HEAD]

   _key                                 graphicFile                                     iconFolder sofFactionName sofHullName sofRaceName  sofMaterialSetID sofLayout
0    10  res:/dx9/model/worldobject/planet/moon.red                                            NaN            NaN         NaN         NaN               NaN       NaN
1    38                                         NaN  res:/dx9/model/ship/caldari/frigate/cf1/icons    caldaribase      cf1_t1     caldari               NaN       NaN
2    39                                         NaN  res:/dx9/model/ship/caldari/frigate/cf2/icons    caldaribase      cf2_t1     caldari               NaN       NaN
3    40                                         NaN  res:/dx9/model/ship/caldari/frigate/cf4/icons    caldaribase      cf4_t1     caldari               NaN       NaN
4    41                                         NaN  res:/dx9/model/ship/caldari/cruiser/cc1/icons    caldaribase      cc1_t1     caldari               NaN       NaN

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 5503) ---
Skipping value_counts (high-cardinality numeric: 5503 unique)

--- Column: 'graphicFile' (Unique values: 2024) ---

                                                    count
graphicFile
res:/dx9/model/turret/launcher/rapidheavy/rapid...     12
res:/dx9/model/Turret/Launcher/Rocket/Rocket_T1...     11
res:/dx9/model/turret/Launcher/Torpedo/Torpedo_...     11
res:/dx9/model/Turret/Launcher/Light/Light_T1.red      10
res:/dx9/model/Turret/Launcher/HeavyAssault/Hea...     10

--- Column: 'iconFolder' (Unique values: 926) ---

                                                    count
iconFolder
res:/fisfx/module/icons                                73
res:/dx9/model/celestial/sun/icons                     32
res:/dx9/model/worldobject/cloud/icons                 28
res:/dx9/model/structure/caldari/modular/struct...     26
res:/dx9/model/structure/caldari/defense/icons         22

--- Column: 'sofFactionName' (Unique values: 265) ---

                count
sofFactionName
caldaribase       199
amarrbase         180
gallentebase      172
minmatarbase      164
minmatarnavy      108

--- Column: 'sofHullName' (Unique values: 1681) ---

             count
sofHullName
cs1             16
cs2             16
cs4             15
cs3             14
gs8             13

--- Column: 'sofRaceName' (Unique values: 21) ---

             count
sofRaceName
caldari        694
gallente       588
amarr          585
minmatar       447
generic        447

--- Column: 'sofMaterialSetID' (Unique values: 55) ---

                  count
sofMaterialSetID
2765.0               11
2760.0                5
2579.0                4
287.0                 3
104.0                 3

--- Column: 'sofLayout' (Contains unhashable lists) ---
Sample value: ['hangar_announcements']


================================================================================
--- 📊 Analyzing: groups.jsonl ---
================================================================================

Loaded 1557 rows in 0.19s

[PRE-PROCESSING]
Flattening 'name' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1557 entries, 0 to 1556
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   _key                  1557 non-null   int64
 1   anchorable            1557 non-null   bool
 2   anchored              1557 non-null   bool
 3   categoryID            1557 non-null   int64
 4   fittableNonSingleton  1557 non-null   bool
 5   name                  1557 non-null   object
 6   published             1557 non-null   bool
 7   useBasePrice          1557 non-null   bool
 8   iconID                763 non-null    float64
dtypes: bool(5), float64(1), int64(2), object(1)
memory usage: 56.4+ KB


[HEAD]

   _key  anchorable  anchored  categoryID  fittableNonSingleton           name  published  useBasePrice  iconID
0     0       False     False           0                 False        #System      False         False     NaN
1     1       False     False           1                 False      Character      False         False     NaN
2     2       False     False           1                 False    Corporation      False         False     NaN
3     3       False     False           2                 False         Region      False         False     NaN
4     4       False     False           2                 False  Constellation      False         False     NaN

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 1557) ---
Skipping value_counts (high-cardinality numeric: 1557 unique)

--- Column: 'anchorable' (Unique values: 2) ---

            count
anchorable
False        1511
True           46

--- Column: 'anchored' (Unique values: 2) ---

          count
anchored
False      1464
True         93

--- Column: 'categoryID' (Unique values: 46) ---

            count
categoryID
11            388
9             206
7             187
66            162
8              78

--- Column: 'fittableNonSingleton' (Unique values: 2) ---

                      count
fittableNonSingleton
False                  1486
True                     71

--- Column: 'name' (Unique values: 1552) ---

                               count
name
Laboratory                         2
Asteroid Belt                      2
Encounter Surveillance System      2
Miscellaneous                      2
Services                           2

--- Column: 'published' (Unique values: 2) ---

           count
published
True         945
False        612

--- Column: 'useBasePrice' (Unique values: 2) ---

              count
useBasePrice
False          1198
True            359

--- Column: 'iconID' (Unique values: 91) ---

        count
iconID
0.0       591
15.0       34
107.0       5
82.0        4
182.0       4

================================================================================
--- 📊 Analyzing: icons.jsonl ---
================================================================================

Loaded 4315 rows in 0.13s

[PRE-PROCESSING]
No dictionary columns found to flatten.

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4315 entries, 0 to 4314
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   _key      4315 non-null   int64
 1   iconFile  4315 non-null   object
dtypes: int64(1), object(1)
memory usage: 67.6+ KB


[HEAD]

   _key                            iconFile
0     0   res:/ui/texture/icons/7_64_15.png
1    15   res:/ui/texture/icons/5_64_11.png
2    16  res:/ui/texture/icons/26_64_11.png
3    21    res:/ui/texture/icons/6_64_3.png
4    22   res:/ui/texture/icons/6_64_14.png

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 4315) ---
Skipping value_counts (high-cardinality numeric: 4315 unique)

--- Column: 'iconFile' (Unique values: 4058) ---

                                                    count
iconFile
res:/UI/Texture/classes/Cosmetics/Ship/componen...      8
res:/UI/Texture/classes/Cosmetics/Ship/material...      4
res:/UI/Asset/mannequin/bottomouter/4085_female...      3
res:/UI/Asset/mannequin/bottomouter/4078_female...      3
res:/UI/Asset/mannequin/bottomouter/3999_female...      3

================================================================================
--- 📊 Analyzing: landmarks.jsonl ---
================================================================================

Loaded 45 rows in 0.14s

[PRE-PROCESSING]
Flattening 'description' to English ('en') key...
Flattening 'name' to English ('en') key...
Flattening 'position' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   _key         45 non-null     int64
 1   description  45 non-null     object
 2   name         45 non-null     object
 3   position     0 non-null      object
 4   iconID       19 non-null     float64
 5   locationID   10 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 2.2+ KB


[HEAD]

   _key                                        description               name position  iconID  locationID
0     1  In the system of New Eden sits the impenetrabl...           EVE Gate     None     NaN         NaN
1     3  Once, Amarr Prime was known as 'Athra', its na...  Amarr Home Worlds     None  2071.0         NaN
2     4  The largest of the five main empires, the Amar...       Amarr Empire     None  2071.0         NaN
3     5  The Minmatar Republic was formed over a centur...  Minmatar Republic     None  2081.0         NaN
4     6  The Caldari State is ruled by several mega-cor...      Caldari State     None  2072.0         NaN

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 45) ---

      count
_key
1         1
3         1
4         1
5         1
6         1

--- Column: 'description' (Unique values: 45) ---

                                                    count
description
In the system of New Eden sits the impenetrable...      1
Once, Amarr Prime was known as 'Athra', its nam...      1
The largest of the five main empires, the Amarr...      1
The Minmatar Republic was formed over a century...      1
The Caldari State is ruled by several mega-corp...      1

--- Column: 'name' (Unique values: 45) ---

                   count
name
EVE Gate               1
Amarr Home Worlds      1
Amarr Empire           1
Minmatar Republic      1
Caldari State          1

--- Column: 'position' (is empty or all null) ---

--- Column: 'iconID' (Unique values: 18) ---

        count
iconID
2071.0      2
2081.0      1
2072.0      1
2076.0      1
2079.0      1

--- Column: 'locationID' (Unique values: 10) ---

            count
locationID
30000116.0      1
30002395.0      1
30000309.0      1
30003618.0      1
30001202.0      1

================================================================================
--- 📊 Analyzing: mapAsteroidBelts.jsonl ---
================================================================================

Loaded 40928 rows in 1.99s

[PRE-PROCESSING]
Flattening 'position' to English ('en') key...
Flattening 'statistics' to English ('en') key...
Flattening 'uniqueName' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40928 entries, 0 to 40927
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   _key            40928 non-null  int64
 1   celestialIndex  40928 non-null  int64
 2   orbitID         40928 non-null  int64
 3   orbitIndex      40928 non-null  int64
 4   position        0 non-null      object
 5   radius          40226 non-null  float64
 6   solarSystemID   40928 non-null  int64
 7   statistics      0 non-null      float64
 8   typeID          40928 non-null  int64
 9   uniqueName      46 non-null     object
dtypes: float64(2), int64(6), object(2)
memory usage: 3.1+ MB


[HEAD]

       _key  celestialIndex   orbitID  orbitIndex position         radius  solarSystemID  statistics  typeID uniqueName
0  40000003               1  40000002           1     None   27043.400391       30000001         NaN      15        NaN
1  40000006               2  40000005           1     None  106355.000000       30000001         NaN      15        NaN
2  40000009               4  40000008           1     None   53559.000000       30000001         NaN      15        NaN
3  40000018               6  40000017           1     None   50028.800781       30000001         NaN      15        NaN
4  40000023               2  40000022           1     None   31406.900391       30000002         NaN      15        NaN

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 40928) ---
Skipping value_counts (high-cardinality numeric: 40928 unique)

--- Column: 'celestialIndex' (Unique values: 17) ---

                count
celestialIndex
7                6890
8                6647
6                6096
9                4666
5                4456

--- Column: 'orbitID' (Unique values: 17277) ---
Skipping value_counts (high-cardinality numeric: 17277 unique)

--- Column: 'orbitIndex' (Unique values: 43) ---

            count
orbitIndex
1           17277
2            7094
3            4231
4            2985
5            2192

--- Column: 'position' (is empty or all null) ---

--- Column: 'radius' (Unique values: 34346) ---
Skipping value_counts (high-cardinality numeric: 34346 unique)

--- Column: 'solarSystemID' (Unique values: 3974) ---
Skipping value_counts (high-cardinality numeric: 3974 unique)

--- Column: 'statistics' (is empty or all null) ---

--- Column: 'typeID' (Unique values: 1) ---

        count
typeID
15      40928

--- Column: 'uniqueName' (Unique values: 46) ---

                                        count
uniqueName
Uplingur IV (Ndoria) - Asteroid Belt 1      1
Uplingur IV (Ndoria) - Asteroid Belt 2      1
Uplingur IV (Ndoria) - Asteroid Belt 3      1
Uplingur IV (Ndoria) - Asteroid Belt 4      1
Uplingur IV (Ndoria) - Asteroid Belt 5      1

================================================================================
--- 📊 Analyzing: mapConstellations.jsonl ---
================================================================================

Loaded 1175 rows in 0.21s

[PRE-PROCESSING]
Flattening 'name' to English ('en') key...
Flattening 'position' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1175 entries, 0 to 1174
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   _key             1175 non-null   int64
 1   factionID        377 non-null    float64
 2   name             1175 non-null   object
 3   position         0 non-null      object
 4   regionID         1175 non-null   int64
 5   solarSystemIDs   1175 non-null   object
 6   wormholeClassID  1141 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 64.4+ KB


[HEAD]

       _key  factionID       name position  regionID                                     solarSystemIDs  wormholeClassID
0  20000001   500007.0  San Matar     None  10000001  [30000001, 30000002, 30000003, 30000004, 30000...              7.0
1  20000002   500007.0     Anares     None  10000001  [30000009, 30000010, 30000011, 30000012, 30000...              7.0
2  20000003   500007.0    Mamouna     None  10000001  [30000017, 30000018, 30000019, 30000020, 30000...              7.0
3  20000004   500007.0   Kalangin     None  10000001  [30000023, 30000024, 30000025, 30000026, 30000...              7.0
4  20000005   500007.0     Hevaka     None  10000001  [30000031, 30000032, 30000033, 30000034, 30000...              7.0

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 1175) ---
Skipping value_counts (high-cardinality numeric: 1175 unique)

--- Column: 'factionID' (Unique values: 20) ---

           count
factionID
500003.0     101
500004.0      54
500001.0      47
500002.0      41
500005.0      19

--- Column: 'name' (Unique values: 1175) ---

           count
name
GPMC-01        1
San Matar      1
Anares         1
Mamouna        1
Kalangin       1

--- Column: 'position' (is empty or all null) ---

--- Column: 'regionID' (Unique values: 113) ---
Skipping value_counts (high-cardinality numeric: 113 unique)

--- Column: 'solarSystemIDs' (Contains unhashable lists) ---
Sample value: [30000001, 30000002, 30000003, 30000004, 30000005, 30000006, 30000007, 30000008]

--- Column: 'wormholeClassID' (Unique values: 18) ---

                 count
wormholeClassID
9.0                479
7.0                273
4.0                 80
3.0                 78
5.0                 66

================================================================================
--- 📊 Analyzing: mapMoons.jsonl ---
================================================================================

Loaded 342170 rows in 12.52s

[PRE-PROCESSING]
Flattening 'attributes' to English ('en') key...
Flattening 'position' to English ('en') key...
Flattening 'statistics' to English ('en') key...
Flattening 'uniqueName' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 342170 entries, 0 to 342169
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   _key            342170 non-null  int64
 1   attributes      0 non-null       object
 2   celestialIndex  342170 non-null  int64
 3   orbitID         342170 non-null  int64
 4   orbitIndex      342170 non-null  int64
 5   position        0 non-null       object
 6   radius          342170 non-null  int64
 7   solarSystemID   342170 non-null  int64
 8   statistics      0 non-null       float64
 9   typeID          342170 non-null  int64
 10  npcStationIDs   3801 non-null    object
 11  uniqueName      137 non-null     object
dtypes: float64(1), int64(7), object(4)
memory usage: 31.3+ MB


[HEAD]

       _key attributes  celestialIndex   orbitID  orbitIndex position   radius  solarSystemID  statistics  typeID npcStationIDs uniqueName
0  40000004       None               1  40000002           1     None   270000       30000001         NaN      14           NaN        NaN
1  40000010       None               4  40000008           1     None   420000       30000001         NaN      14           NaN        NaN
2  40000012       None               5  40000011           1     None   300000       30000001         NaN      14    [60012526]        NaN
3  40000013       None               5  40000011           2     None   690000       30000001         NaN      14           NaN        NaN
4  40000014       None               5  40000011           3     None  1560000       30000001         NaN      14           NaN        NaN

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 342170) ---
Skipping value_counts (high-cardinality numeric: 342170 unique)

--- Column: 'attributes' (is empty or all null) ---

--- Column: 'celestialIndex' (Unique values: 18) ---

                count
celestialIndex
6               61302
7               59443
5               49969
8               47476
4               33528

--- Column: 'orbitID' (Unique values: 51460) ---
Skipping value_counts (high-cardinality numeric: 51460 unique)

--- Column: 'orbitIndex' (Unique values: 33) ---

            count
orbitIndex
1           51460
2           32666
3           24922
4           21248
5           18933

--- Column: 'position' (is empty or all null) ---

--- Column: 'radius' (Unique values: 1026) ---
Skipping value_counts (high-cardinality numeric: 1026 unique)

--- Column: 'solarSystemID' (Unique values: 7926) ---
Skipping value_counts (high-cardinality numeric: 7926 unique)

--- Column: 'statistics' (is empty or all null) ---

--- Column: 'typeID' (Unique values: 2) ---

         count
typeID
14      342169
52673        1

--- Column: 'npcStationIDs' (Contains unhashable lists) ---
Sample value: [60012526]

--- Column: 'uniqueName' (Unique values: 137) ---

                               count
uniqueName
Uplingur IV (Ndoria) - Moon 1      1
Uplingur IV (Ndoria) - Moon 2      1
Uplingur IV (Ndoria) - Moon 3      1
Uplingur IV (Ndoria) - Moon 4      1
Uplingur IV (Ndoria) - Moon 5      1

================================================================================
--- 📊 Analyzing: mapPlanets.jsonl ---
================================================================================

Loaded 67961 rows in 2.44s

[PRE-PROCESSING]
Flattening 'attributes' to English ('en') key...
Flattening 'position' to English ('en') key...
Flattening 'statistics' to English ('en') key...
Flattening 'uniqueName' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67961 entries, 0 to 67960
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   _key             67961 non-null  int64
 1   asteroidBeltIDs  17277 non-null  object
 2   attributes       0 non-null      object
 3   celestialIndex   67961 non-null  int64
 4   moonIDs          51460 non-null  object
 5   orbitID          67961 non-null  int64
 6   position         0 non-null      object
 7   radius           67961 non-null  int64
 8   solarSystemID    67961 non-null  int64
 9   statistics       0 non-null      object
 10  typeID           67961 non-null  int64
 11  npcStationIDs    1098 non-null   object
 12  uniqueName       43 non-null     object
dtypes: int64(6), object(7)
memory usage: 6.7+ MB


[HEAD]

       _key asteroidBeltIDs attributes  celestialIndex                                            moonIDs   orbitID position    radius  solarSystemID statistics  typeID npcStationIDs uniqueName
0  40000002      [40000003]       None               1                                         [40000004]  40000001     None   5060000       30000001       None      11           NaN        NaN
1  40000005      [40000006]       None               2                                                NaN  40000001     None   6060000       30000001       None      11           NaN        NaN
2  40000007             NaN       None               3                                                NaN  40000001     None   3490000       30000001       None    2016           NaN        NaN
3  40000008      [40000009]       None               4                                         [40000010]  40000001     None   5540000       30000001       None    2014    [60014437]        NaN
4  40000011             NaN       None               5  [40000012, 40000013, 40000014, 40000015, 40000...  40000001     None  16140000       30000001       None      13           NaN        NaN

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 67961) ---
Skipping value_counts (high-cardinality numeric: 67961 unique)

--- Column: 'asteroidBeltIDs' (Contains unhashable lists) ---
Sample value: [40000003]

--- Column: 'attributes' (is empty or all null) ---

--- Column: 'celestialIndex' (Unique values: 18) ---

                count
celestialIndex
1                8035
2                8021
3                7995
4                7959
5                7831

--- Column: 'moonIDs' (Contains unhashable lists) ---
Sample value: [40000004]

--- Column: 'orbitID' (Unique values: 8035) ---
Skipping value_counts (high-cardinality numeric: 8035 unique)

--- Column: 'position' (is empty or all null) ---

--- Column: 'radius' (Unique values: 7228) ---
Skipping value_counts (high-cardinality numeric: 7228 unique)

--- Column: 'solarSystemID' (Unique values: 8035) ---
Skipping value_counts (high-cardinality numeric: 8035 unique)

--- Column: 'statistics' (is empty or all null) ---

--- Column: 'typeID' (Unique values: 10) ---

        count
typeID
13      20262
2016    19714
11       7200
2015     6611
2017     5569

--- Column: 'npcStationIDs' (Contains unhashable lists) ---
Sample value: [60014437]

--- Column: 'uniqueName' (Unique values: 43) ---

                          count
uniqueName
Uplingur IV (Ndoria)          1
New Caldari I (Matigu)        1
New Caldari II (Matias)       1
New Caldari III (Orieku)      1
New Caldari Prime             1

================================================================================
--- 📊 Analyzing: mapRegions.jsonl ---
================================================================================

Loaded 113 rows in 0.43s

[PRE-PROCESSING]
Flattening 'description' to English ('en') key...
Flattening 'name' to English ('en') key...
Flattening 'position' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113 entries, 0 to 112
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   _key              113 non-null    int64
 1   constellationIDs  113 non-null    object
 2   description       69 non-null     object
 3   factionID         32 non-null     float64
 4   name              113 non-null    object
 5   nebulaID          113 non-null    int64
 6   position          0 non-null      object
 7   wormholeClassID   109 non-null    float64
dtypes: float64(2), int64(2), object(4)
memory usage: 7.2+ KB


[HEAD]

       _key                                   constellationIDs                                        description  factionID                name  nebulaID position  wormholeClassID
0  10000001  [20000001, 20000002, 20000003, 20000004, 20000...  The Derelik region, sovereign seat of the Amma...   500007.0             Derelik     11799     None              7.0
1  10000002  [20000017, 20000018, 20000019, 20000020, 20000...  "The greater the State becomes, the greater hu...   500001.0           The Forge     11806     None              7.0
2  10000003  [20000030, 20000031, 20000032, 20000033, 20000...  A sprawling region in the galactic "north," th...        NaN  Vale of the Silent     11814     None              9.0
3  10000004  [20000047, 20000048, 20000049, 20000050, 20000...                                  <b>CLASSIFIED</b>        NaN              UUA-F4     11817     None              NaN
4  10000005  [20000063, 20000064, 20000065, 20000066, 20000...  In the outer reaches of the south, nestled beh...        NaN             Detorid     11849     None              9.0

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 113) ---
Skipping value_counts (high-cardinality numeric: 113 unique)

--- Column: 'constellationIDs' (Contains unhashable lists) ---
Sample value: [20000001, 20000002, 20000003, 20000004, 20000005, 20000006, 20000007, 20000008, 20000009, 20000010, 20000011, 20000012, 20000013, 20000014, 20000015, 20000016]

--- Column: 'description' (Unique values: 69) ---

                                                    count
description
The Derelik region, sovereign seat of the Ammat...      1
"The greater the State becomes, the greater hum...      1
A sprawling region in the galactic "north," the...      1
<b>CLASSIFIED</b>                                       1
In the outer reaches of the south, nestled behi...      1

--- Column: 'factionID' (Unique values: 14) ---

           count
factionID
500003.0       8
500004.0       6
500001.0       4
500002.0       3
500005.0       2

--- Column: 'name' (Unique values: 113) ---

                    count
name
Derelik                 1
The Forge               1
Vale of the Silent      1
UUA-F4                  1
Detorid                 1

--- Column: 'nebulaID' (Unique values: 80) ---

          count
nebulaID
11784         8
11783         7
11785         6
11821         6
11782         5

--- Column: 'position' (is empty or all null) ---

--- Column: 'wormholeClassID' (Unique values: 16) ---

                 count
wormholeClassID
9.0                 41
7.0                 24
4.0                  8
3.0                  7
5.0                  6

================================================================================
--- 📊 Analyzing: mapSolarSystems.jsonl ---
================================================================================

Loaded 8437 rows in 0.39s

[PRE-PROCESSING]
Flattening 'name' to English ('en') key...
Flattening 'position' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8437 entries, 0 to 8436
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   _key                        8437 non-null   int64
 1   border                      1997 non-null   float64
 2   constellationID             8437 non-null   int64
 3   hub                         2678 non-null   float64
 4   international               108 non-null    float64
 5   luminosity                  5431 non-null   float64
 6   name                        8437 non-null   object
 7   planetIDs                   8035 non-null   object
 8   position                    0 non-null      object
 9   radius                      8437 non-null   int64
 10  regionID                    8437 non-null   int64
 11  regional                    537 non-null    float64
 12  securityClass               5140 non-null   object
 13  securityStatus              8437 non-null   float64
 14  starID                      8036 non-null   float64
 15  stargateIDs                 5215 non-null   object
 16  corridor                    1920 non-null   float64
 17  fringe                      782 non-null    float64
 18  wormholeClassID             692 non-null    float64
 19  visualEffect                129 non-null    object
 20  disallowedAnchorCategories  538 non-null    object
 21  disallowedAnchorGroups      26 non-null     object
 22  factionID                   16 non-null     float64
dtypes: float64(11), int64(4), object(8)
memory usage: 1.5+ MB


[HEAD]

       _key  border  constellationID  hub  international  luminosity      name                                          planetIDs position         radius  regionID  regional securityClass  securityStatus      starID                               stargateIDs  corridor  fringe  wormholeClassID visualEffect disallowedAnchorCategories disallowedAnchorGroups  factionID
0  30000001     1.0         20000001  1.0            1.0     0.01575     Tanoo  [40000002, 40000005, 40000007, 40000008, 40000...     None  1323338301440  10000001       1.0             B        0.858324  40000001.0            [50000056, 50000057, 50000058]       NaN     NaN              NaN          NaN                        NaN                    NaN        NaN
1  30000002     1.0         20000001  NaN            1.0     0.01282  Lashesih  [40000020, 40000022, 40000024, 40000028, 40000...     None  1018400014336  10000001       1.0             B        0.751689  40000019.0                      [50000067, 50000068]       1.0     NaN              NaN          NaN                        NaN                    NaN        NaN
2  30000003     1.0         20000001  1.0            NaN     0.62130   Akpivem  [40000041, 40000043, 40000046, 40000055, 40000...     None  2473362456576  10000001       NaN             B        0.846292  40000040.0  [50000342, 50000343, 50000344, 50000345]       NaN     NaN              NaN          NaN                        NaN                    NaN        NaN
3  30000004     1.0         20000001  NaN            1.0     0.34610      Jark  [40000130, 40000132, 40000134, 40000137, 40000...     None  1771412258816  10000001       1.0             B        0.817001  40000129.0                      [50001729, 50001730]       1.0     NaN              NaN          NaN                        NaN                    NaN        NaN
4  30000005     1.0         20000001  1.0            NaN     0.02403     Sasta  [40000191, 40000193, 40000194, 40000196, 40000...     None  2563946315776  10000001       NaN             B        0.814337  40000190.0  [50001739, 50001740, 50001741, 50001742]       NaN     NaN              NaN          NaN                        NaN                    NaN        NaN

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 8437) ---
Skipping value_counts (high-cardinality numeric: 8437 unique)

--- Column: 'border' (Unique values: 1) ---

        count
border
1.0      1997

--- Column: 'constellationID' (Unique values: 1175) ---
Skipping value_counts (high-cardinality numeric: 1175 unique)

--- Column: 'hub' (Unique values: 1) ---

     count
hub
1.0   2678

--- Column: 'international' (Unique values: 1) ---

               count
international
1.0              108

--- Column: 'luminosity' (Unique values: 4004) ---
Skipping value_counts (high-cardinality numeric: 4004 unique)

--- Column: 'name' (Unique values: 8437) ---

          count
name
GPMS-01       1
Tanoo         1
Lashesih      1
Akpivem       1
Jark          1

--- Column: 'planetIDs' (Contains unhashable lists) ---
Sample value: [40000002, 40000005, 40000007, 40000008, 40000011, 40000017]

--- Column: 'position' (is empty or all null) ---

--- Column: 'radius' (Unique values: 7525) ---
Skipping value_counts (high-cardinality numeric: 7525 unique)

--- Column: 'regionID' (Unique values: 113) ---
Skipping value_counts (high-cardinality numeric: 113 unique)

--- Column: 'regional' (Unique values: 1) ---

          count
regional
1.0         537

--- Column: 'securityClass' (Unique values: 62) ---

               count
securityClass
B1               389
I                354
J                316
G                292
B                283

--- Column: 'securityStatus' (Unique values: 5325) ---
Skipping value_counts (high-cardinality numeric: 5325 unique)

--- Column: 'starID' (Unique values: 8036) ---
Skipping value_counts (high-cardinality numeric: 8036 unique)

--- Column: 'stargateIDs' (Contains unhashable lists) ---
Sample value: [50000056, 50000057, 50000058]

--- Column: 'corridor' (Unique values: 1) ---

          count
corridor
1.0        1920

--- Column: 'fringe' (Unique values: 1) ---

        count
fringe
1.0       782

--- Column: 'wormholeClassID' (Unique values: 6) ---

                 count
wormholeClassID
8.0                687
14.0                 1
15.0                 1
16.0                 1
17.0                 1

--- Column: 'visualEffect' (Unique values: 3) ---

                           count
visualEffect
SHATTEREDWORMHOLE_OVERLAY    101
TRIGLAVIAN_HOME               27
THERA                          1

--- Column: 'disallowedAnchorCategories' (Contains unhashable lists) ---
Sample value: [22, 65]

--- Column: 'disallowedAnchorGroups' (Contains unhashable lists) ---
Sample value: [12, 340, 448]

--- Column: 'factionID' (Unique values: 7) ---

           count
factionID
500001.0      10
500013.0       1
500029.0       1
500027.0       1
500002.0       1

================================================================================
--- 📊 Analyzing: mapStargates.jsonl ---
================================================================================

Loaded 13776 rows in 0.40s

[PRE-PROCESSING]
Flattening 'destination' to English ('en') key...
Flattening 'position' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13776 entries, 0 to 13775
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   _key           13776 non-null  int64
 1   destination    0 non-null      object
 2   position       0 non-null      object
 3   solarSystemID  13776 non-null  int64
 4   typeID         13776 non-null  int64
dtypes: int64(3), object(2)
memory usage: 538.3+ KB


[HEAD]

       _key destination position  solarSystemID  typeID
0  50000001        None     None       30000777   29633
1  50000002        None     None       30000777    3877
2  50000003        None     None       30000777   29633
3  50000004        None     None       30001386      16
4  50000005        None     None       30001386      16

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 13776) ---
Skipping value_counts (high-cardinality numeric: 13776 unique)

--- Column: 'destination' (is empty or all null) ---

--- Column: 'position' (is empty or all null) ---

--- Column: 'solarSystemID' (Unique values: 5215) ---
Skipping value_counts (high-cardinality numeric: 5215 unique)

--- Column: 'typeID' (Unique values: 24) ---

        count
typeID
29624    3420
3875     3123
29633    2518
16       2116
17        556

================================================================================
--- 📊 Analyzing: mapStars.jsonl ---
================================================================================

Loaded 8036 rows in 0.19s

[PRE-PROCESSING]
Flattening 'statistics' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8036 entries, 0 to 8035
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   _key           8036 non-null   int64
 1   radius         8036 non-null   int64
 2   solarSystemID  8036 non-null   int64
 3   statistics     0 non-null      object
 4   typeID         8036 non-null   int64
dtypes: int64(4), object(1)
memory usage: 314.0+ KB


[HEAD]

       _key     radius  solarSystemID statistics  typeID
0  40000001   63350000       30000001       None   45041
1  40000019  133000000       30000002       None   45037
2  40000040  255000000       30000003       None    3799
3  40000129  477100000       30000004       None   45030
4  40000190  588300000       30000005       None   45040

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 8036) ---
Skipping value_counts (high-cardinality numeric: 8036 unique)

--- Column: 'radius' (Unique values: 3480) ---
Skipping value_counts (high-cardinality numeric: 3480 unique)

--- Column: 'solarSystemID' (Unique values: 8036) ---
Skipping value_counts (high-cardinality numeric: 8036 unique)

--- Column: 'statistics' (is empty or all null) ---

--- Column: 'typeID' (Unique values: 38) ---

        count
typeID
45041     526
3802      494
45039     457
3800      427
45037     394

================================================================================
--- 📊 Analyzing: marketGroups.jsonl ---
================================================================================

Loaded 2039 rows in 0.19s

[PRE-PROCESSING]
Flattening 'description' to English ('en') key...
Flattening 'name' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2039 entries, 0 to 2038
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   _key           2039 non-null   int64
 1   description    1565 non-null   object
 2   hasTypes       2039 non-null   bool
 3   iconID         2009 non-null   float64
 4   name           2039 non-null   object
 5   parentGroupID  2020 non-null   float64
dtypes: bool(1), float64(2), int64(1), object(2)
memory usage: 81.8+ KB


[HEAD]

   _key                                        description  hasTypes  iconID                    name  parentGroupID
0     2  Blueprints are data items used in industry for...     False  2703.0  Blueprints & Reactions            NaN
1     4  Capsuleer spaceships of all sizes and roles, i...     False  1443.0                   Ships            NaN
2     5  Small, fast vessels suited to a variety of pur...     False  1443.0       Standard Frigates         1361.0
3     6  The middle children of the starship industry, ...     False  1443.0       Standard Cruisers         1367.0
4     7  The foundations of any respectable fighting fo...     False  1443.0    Standard Battleships         1376.0

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 2039) ---
Skipping value_counts (high-cardinality numeric: 2039 unique)

--- Column: 'description' (Unique values: 1448) ---

                                                    count
description
Implant Slot 08                                        14
Implant Slot 07                                        11
Materials used in the construction of specific ...     11
Implant Slot 06                                        10
Implant Slot 09                                         9

--- Column: 'hasTypes' (Unique values: 2) ---

          count
hasTypes
True       1609
False       430

--- Column: 'iconID' (Unique values: 409) ---
Skipping value_counts (high-cardinality numeric: 409 unique)

--- Column: 'name' (Unique values: 965) ---

          count
name
Caldari      90
Minmatar     90
Amarr        90
Gallente     90
Medium       44

--- Column: 'parentGroupID' (Unique values: 430) ---
Skipping value_counts (high-cardinality numeric: 430 unique)


================================================================================
--- 📊 Analyzing: masteries.jsonl ---
================================================================================

Loaded 460 rows in 0.12s

[PRE-PROCESSING]
No dictionary columns found to flatten.

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 460 entries, 0 to 459
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   _key    460 non-null    int64
 1   _value  460 non-null    object
dtypes: int64(1), object(1)
memory usage: 7.3+ KB


[HEAD]

   _key                                             _value
0   582  [{'_key': 0, '_value': [96, 139, 85, 87, 94]},...
1   583  [{'_key': 0, '_value': [96, 99, 150, 75, 139, ...
2   584  [{'_key': 0, '_value': [96, 100, 139, 85, 94]}...
3   585  [{'_key': 0, '_value': [96, 99, 150, 71, 141, ...
4   586  [{'_key': 0, '_value': [96, 104, 105, 141, 85,...

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 460) ---
Skipping value_counts (high-cardinality numeric: 460 unique)

--- Column: '_value' (Contains unhashable lists) ---
Sample value: [{'_key': 0, '_value': [96, 139, 85, 87, 94]}, {'_key': 1, '_value': [96, 139, 85, 87, 94]}, {'_key': 2, '_value': [96, 139, 85, 87, 94]}, {'_key': 3, '_value': [96, 139, 85, 87, 94]}, {'_key': 4, '_value': [96, 139, 85, 118, 87, 94]}]


================================================================================
--- 📊 Analyzing: metaGroups.jsonl ---
================================================================================

Loaded 13 rows in 0.18s

[PRE-PROCESSING]
Flattening 'color' to English ('en') key...
Flattening 'name' to English ('en') key...
Flattening 'description' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   _key         13 non-null     int64
 1   color        0 non-null      float64
 2   name         13 non-null     object
 3   iconID       12 non-null     float64
 4   iconSuffix   12 non-null     object
 5   description  3 non-null      object
dtypes: float64(2), int64(1), object(3)
memory usage: 756.0+ bytes


[HEAD]

   _key  color       name   iconID iconSuffix description
0     1    NaN     Tech I      NaN        NaN         NaN
1     2    NaN    Tech II  24150.0         t2         NaN
2     3    NaN  Storyline  24147.0  storyline         NaN
3     4    NaN    Faction  24146.0    faction         NaN
4     5    NaN    Officer  24149.0    officer         NaN

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 13) ---

      count
_key
1         1
2         1
3         1
4         1
5         1

--- Column: 'color' (is empty or all null) ---

--- Column: 'name' (Unique values: 13) ---

           count
name
Tech I         1
Tech II        1
Storyline      1
Faction        1
Officer        1

--- Column: 'iconID' (Unique values: 12) ---

         count
iconID
24150.0      1
24147.0      1
24146.0      1
24149.0      1
24148.0      1

--- Column: 'iconSuffix' (Unique values: 12) ---

            count
iconSuffix
t2              1
storyline       1
faction         1
officer         1
deadspace       1

--- Column: 'description' (Unique values: 3) ---

                                                    count
description
Modules found in deadspace.                             1
This item is only available through the New Ede...      1
This item is only available for a limited time.         1

================================================================================
--- 📊 Analyzing: npcCharacters.jsonl ---
================================================================================

Loaded 11302 rows in 0.62s

[PRE-PROCESSING]
Flattening 'name' to English ('en') key...
Flattening 'agent' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11302 entries, 0 to 11301
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   _key           11302 non-null  int64
 1   bloodlineID    11302 non-null  int64
 2   ceo            11302 non-null  bool
 3   corporationID  11302 non-null  int64
 4   gender         11302 non-null  bool
 5   locationID     11256 non-null  float64
 6   name           11302 non-null  object
 7   raceID         11302 non-null  int64
 8   startDate      11185 non-null  object
 9   uniqueName     11302 non-null  bool
 10  skills         421 non-null    object
 11  ancestryID     11101 non-null  float64
 12  careerID       11098 non-null  float64
 13  schoolID       11095 non-null  float64
 14  specialityID   11096 non-null  float64
 15  agent          0 non-null      float64
 16  description    24 non-null     object
dtypes: bool(3), float64(6), int64(4), object(4)
memory usage: 1.2+ MB


[HEAD]

      _key  bloodlineID   ceo  corporationID  gender  locationID            name  raceID            startDate  uniqueName                                skills  ancestryID  careerID  schoolID  specialityID  agent description
0  3000001            1  True        1000001   False  60000001.0        Dame Hel       1  2003-03-12 20:04:00       False                                   NaN         NaN       NaN       NaN           NaN    NaN         NaN
1  3003869            5  True        1000073   False  60007183.0   Pamoo Meninri       4  2003-03-27 13:27:00        True  [{'typeID': 3363}, {'typeID': 3368}]         NaN       NaN       NaN           NaN    NaN         NaN
2  3003873            6  True        1000079    True  60007768.0  Badji Bihabnir       4  2003-03-27 13:27:00        True  [{'typeID': 3363}, {'typeID': 3368}]         NaN       NaN       NaN           NaN    NaN         NaN
3  3003877            5  True        1000063   False  60006100.0  Saronu Seevath       4  2003-03-27 13:27:00        True  [{'typeID': 3363}, {'typeID': 3368}]         NaN       NaN       NaN           NaN    NaN         NaN
4  3003881            6  True        1000084    True  60008368.0   Kezti Sundara       4  2003-03-27 13:27:00        True  [{'typeID': 3368}, {'typeID': 3363}]         NaN       NaN       NaN           NaN    NaN         NaN

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 11302) ---
Skipping value_counts (high-cardinality numeric: 11302 unique)

--- Column: 'bloodlineID' (Unique values: 13) ---

             count
bloodlineID
1             1771
2             1697
7             1454
8             1408
5             1400

--- Column: 'ceo' (Unique values: 2) ---

       count
ceo
False  11045
True     257

--- Column: 'corporationID' (Unique values: 260) ---
Skipping value_counts (high-cardinality numeric: 260 unique)

--- Column: 'gender' (Unique values: 2) ---

        count
gender
True     5713
False    5589

--- Column: 'locationID' (Unique values: 5092) ---
Skipping value_counts (high-cardinality numeric: 5092 unique)

--- Column: 'name' (Unique values: 11302) ---

                  count
name
Kobalos Tyrannos      1
Dame Hel              1
Pamoo Meninri         1
Badji Bihabnir        1
Saronu Seevath        1

--- Column: 'raceID' (Unique values: 5) ---

        count
raceID
1        3560
8        2921
4        2803
2        1989
16         29

--- Column: 'startDate' (Unique values: 1018) ---

                     count
startDate
2003-12-04 16:29:00   3069
2003-05-04 00:33:00   2999
2003-05-04 00:32:00   1268
2003-05-04 00:34:00    653
2004-10-25 10:47:00    592

--- Column: 'uniqueName' (Unique values: 2) ---

            count
uniqueName
True        11284
False          18

--- Column: 'skills' (Contains unhashable lists) ---
Sample value: [{'typeID': 3363}, {'typeID': 3368}]

--- Column: 'ancestryID' (Unique values: 37) ---

            count
ancestryID
12.0          617
8.0           580
7.0           566
10.0          566
11.0          561

--- Column: 'careerID' (Unique values: 13) ---

          count
careerID
11.0       1195
17.0       1179
14.0       1132
81.0        969
84.0        960

--- Column: 'schoolID' (Unique values: 13) ---

          count
schoolID
17.0       1193
19.0       1179
18.0       1133
20.0        967
21.0        964

--- Column: 'specialityID' (Unique values: 25) ---

              count
specialityID
11.0            639
18.0            609
14.0            591
17.0            571
12.0            555

--- Column: 'agent' (is empty or all null) ---

--- Column: 'description' (Unique values: 8) ---

                                                    count
description
From Paragon meet IRIS, the next step in custom...     11
This individual commands one of the powerful ve...      7
This individual commands one of the powerful ve...      1
The Vigilant Tyrannos command structure is appa...      1
Chief of the Nefantar Tribe                             1

================================================================================
--- 📊 Analyzing: npcCorporationDivisions.jsonl ---
================================================================================

Loaded 10 rows in 0.14s

[PRE-PROCESSING]
Flattening 'leaderTypeName' to English ('en') key...
Flattening 'name' to English ('en') key...
Flattening 'description' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   _key            10 non-null     int64
 1   displayName     9 non-null      object
 2   internalName    10 non-null     object
 3   leaderTypeName  10 non-null     object
 4   name            10 non-null     object
 5   description     5 non-null      object
dtypes: int64(1), object(5)
memory usage: 612.0+ bytes


[HEAD]

   _key                        displayName                  internalName        leaderTypeName                          name                                        description
0    18  Research and development division                           R&D      Chief Researcher                           R&D                                                NaN
1    22          New distribution division                  Distribution  Distribution Manager                  Distribution                                                NaN
2    23                New mining division                        Mining    Mining Coordinator                        Mining                                                NaN
3    24              New security division                      Security             Commander                      Security                                                NaN
4    25                    Business career  Industrialist - Entrepreneur         Chief Advisor  Industrialist - Entrepreneur  These pilots are masters of arbitrage, profite...

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 10) ---

      count
_key
18        1
22        1
23        1
24        1
25        1

--- Column: 'displayName' (Unique values: 9) ---

                                   count
displayName
Research and development division      1
New distribution division              1
New mining division                    1
New security division                  1
Business career                        1

--- Column: 'internalName' (Unique values: 10) ---

                              count
internalName
R&D                               1
Distribution                      1
Mining                            1
Security                          1
Industrialist - Entrepreneur      1

--- Column: 'leaderTypeName' (Unique values: 6) ---

                      count
leaderTypeName
Chief Advisor             5
Chief Researcher          1
Distribution Manager      1
Mining Coordinator        1
Commander                 1

--- Column: 'name' (Unique values: 10) ---

                              count
name
R&D                               1
Distribution                      1
Mining                            1
Security                          1
Industrialist - Entrepreneur      1

--- Column: 'description' (Unique values: 5) ---

                                                    count
description
These pilots are masters of arbitrage, profitee...      1
Space is vast, and a lot of it remains uncharte...      1
Industrial pilots are the rugged individuals te...      1
Enforcer pilots live for war, wielding unimagin...      1
Pilots on this advanced training program will b...      1

================================================================================
--- 📊 Analyzing: npcCorporations.jsonl ---
================================================================================

Loaded 283 rows in 0.18s

[PRE-PROCESSING]
Flattening 'description' to English ('en') key...
Flattening 'name' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 283 entries, 0 to 282
Data columns (total 33 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   _key                        283 non-null    int64
 1   ceoID                       260 non-null    float64
 2   deleted                     283 non-null    bool
 3   description                 280 non-null    object
 4   extent                      283 non-null    object
 5   hasPlayerPersonnelManager   283 non-null    bool
 6   initialPrice                283 non-null    int64
 7   memberLimit                 283 non-null    int64
 8   minSecurity                 283 non-null    int64
 9   minimumJoinStanding         283 non-null    int64
 10  name                        283 non-null    object
 11  sendCharTerminationMessage  283 non-null    bool
 12  shares                      283 non-null    int64
 13  size                        283 non-null    object
 14  stationID                   262 non-null    float64
 15  taxRate                     283 non-null    float64
 16  tickerName                  283 non-null    object
 17  uniqueName                  283 non-null    bool
 18  allowedMemberRaces          212 non-null    object
 19  corporationTrades           184 non-null    object
 20  divisions                   118 non-null    object
 21  enemyID                     250 non-null    float64
 22  factionID                   273 non-null    float64
 23  friendID                    246 non-null    float64
 24  iconID                      252 non-null    float64
 25  investors                   227 non-null    object
 26  lpOfferTables               181 non-null    object
 27  mainActivityID              266 non-null    float64
 28  raceID                      257 non-null    float64
 29  sizeFactor                  189 non-null    float64
 30  solarSystemID               261 non-null    float64
 31  secondaryActivityID         34 non-null     float64
 32  exchangeRates               1 non-null      object
dtypes: bool(4), float64(12), int64(6), object(11)
memory usage: 65.4+ KB


[HEAD]

      _key      ceoID  deleted                                        description extent  hasPlayerPersonnelManager  initialPrice  memberLimit  minSecurity  minimumJoinStanding                  name  sendCharTerminationMessage       shares size   stationID  taxRate tickerName  uniqueName allowedMemberRaces                                  corporationTrades                                          divisions    enemyID  factionID   friendID  iconID                                          investors             lpOfferTables  mainActivityID  raceID  sizeFactor  solarSystemID  secondaryActivityID exchangeRates
0  1000001  3000001.0    False  The internal corporation used for characters i...      L                      False             0           -1            0                    1              Doomheim                        True            1    T  60000001.0      0.0        666       False                NaN                                                NaN                                                NaN        NaN        NaN        NaN     NaN                                                NaN                       NaN             NaN     NaN         NaN            NaN                  NaN           NaN
1  1000002  3004049.0    False  The CBD Corporation is one of the biggest expo...      G                      False            47           -1            0                    1       CBD Corporation                       False  30515077373    H  60000004.0      0.0       CBDC        True                [1]  [{'_key': 41, '_value': 0.42430165130978204}, ...  [{'_key': 22, 'divisionNumber': 1, 'leaderID':...  1000005.0   500001.0  1000006.0  1465.0  [{'_key': 1000002, '_value': 42}, {'_key': 100...            [6, 9, 58, 62]            10.0     1.0        1.75     30002780.0                  NaN           NaN
2  1000003  3004169.0    False  Prompt Delivery is a express delivery company ...      R                      False             5           -1           -1                    1       Prompt Delivery                       False   9657087378    M  60000274.0      0.0         PD        True                [1]  [{'_key': 672, '_value': 0.00234777173674}, {'...                                                NaN  1000009.0   500001.0  1000040.0  1581.0  [{'_key': 1000023, '_value': 2}, {'_key': 1000...            [9, 58, 62, 6]            10.0     1.0        1.25     30000149.0                  NaN           NaN
3  1000004  3004217.0    False  Ytiri is a rare example of an outsider company...      N                      False            40           -1            0                    1                 Ytiri                       False   3495338567    L  60000310.0      0.0          Y        True                [1]  [{'_key': 672, '_value': 0.00679812185743}, {'...                                                NaN  1000007.0   500001.0  1000039.0  1582.0  [{'_key': 1000010, '_value': 55}, {'_key': 100...  [9, 58, 62, 107, 6, 237]            10.0     1.0        1.50     30001399.0                  NaN           NaN
4  1000005  3004113.0    False  Hyasyoda is one of the oldest of the Caldari m...      N                      False            23           -1            0                    1  Hyasyoda Corporation                       False  54422491638    H  60000430.0      0.0         HC        True                [1]  [{'_key': 521, '_value': 0.30334326204002304},...  [{'_key': 22, 'divisionNumber': 1, 'leaderID':...  1000002.0   500001.0  1000019.0  1583.0  [{'_key': 1000005, '_value': 25}, {'_key': 100...            [6, 7, 59, 62]             3.0     1.0        1.75     30002801.0                  NaN           NaN

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 283) ---
Skipping value_counts (high-cardinality numeric: 283 unique)

--- Column: 'ceoID' (Unique values: 258) ---
Skipping value_counts (high-cardinality numeric: 258 unique)

--- Column: 'deleted' (Unique values: 2) ---

         count
deleted
False      280
True         3

--- Column: 'description' (Unique values: 280) ---

                                                    count
description
The Deathless Wraiths are the elite infiltratio...      1
The internal corporation used for characters in...      1
The CBD Corporation is one of the biggest expor...      1
Prompt Delivery is a express delivery company t...      1
Ytiri is a rare example of an outsider company ...      1

--- Column: 'extent' (Unique values: 5) ---

        count
extent
N          92
G          69
L          65
R          33
C          24

--- Column: 'hasPlayerPersonnelManager' (Unique values: 2) ---

                           count
hasPlayerPersonnelManager
False                        279
True                           4

--- Column: 'initialPrice' (Unique values: 68) ---

              count
initialPrice
0                97
20               61
200              12
35                9
25                4

--- Column: 'memberLimit' (Unique values: 1) ---

             count
memberLimit
-1             283

--- Column: 'minSecurity' (Unique values: 10) ---

             count
minSecurity
 0             195
 1              25
-1              24
-10             16
-2               8

--- Column: 'minimumJoinStanding' (Unique values: 2) ---

                     count
minimumJoinStanding
1                      276
0                        7

--- Column: 'name' (Unique values: 283) ---

                   count
name
Deathless Wraiths      1
Doomheim               1
CBD Corporation        1
Prompt Delivery        1
Ytiri                  1

--- Column: 'sendCharTerminationMessage' (Unique values: 2) ---

                            count
sendCharTerminationMessage
False                         262
True                           21

--- Column: 'shares' (Unique values: 116) ---
Skipping value_counts (high-cardinality numeric: 116 unique)

--- Column: 'size' (Unique values: 5) ---

      count
size
T        87
S        62
L        55
M        47
H        32

--- Column: 'stationID' (Unique values: 237) ---
Skipping value_counts (high-cardinality numeric: 237 unique)

--- Column: 'taxRate' (Unique values: 3) ---

         count
taxRate
0.00       254
0.11        27
0.10         2

--- Column: 'tickerName' (Unique values: 283) ---

            count
tickerName
DTH-W           1
666             1
CBDC            1
PD              1
Y               1

--- Column: 'uniqueName' (Unique values: 2) ---

            count
uniqueName
True          282
False           1

--- Column: 'allowedMemberRaces' (Contains unhashable lists) ---
Sample value: [1]

--- Column: 'corporationTrades' (Contains unhashable lists) ---
Sample value: [{'_key': 41, '_value': 0.42430165130978204}, {'_key': 43, '_value': -0.6711405041493871}, {'_key': 421, '_value': 0.30011431580456105}, {'_key': 518, '_value': 0.7750082325370861}, {'_key': 672, '_value': 0.06973519798742}, {'_key': 786, '_value': 0.19450615755504702}, {'_key': 967, '_value': 0.06973519798742}, {'_key': 1010, '_value': 0.203714265385796}, {'_key': 1026, '_value': 0.250433366002142}, {'_key': 1032, '_value': 0.145367158457186}, {'_key': 1072, '_value': 0.366952571787724}, {'_key': 1102, '_value': 0.26645062706195505}, {'_key': 1105, '_value': 0.312579484016382}, {'_key': 1109, '_value': 0.282533822130326}, {'_key': 1116, '_value': 0.263228573138787}, {'_key': 1130, '_value': 0.108646600322821}, {'_key': 1133, '_value': 0.153125955405782}, {'_key': 2368, '_value': -0.19984995874199998}, {'_key': 2369, '_value': -0.19984995874199998}, {'_key': 2371, '_value': -0.19984995874199998}, {'_key': 2373, '_value': -0.19984995874199998}, {'_key': 2374, '_value': -0.19984995874199998}, {'_key': 2375, '_value': -0.19984995874199998}, {'_key': 2376, '_value': -0.19984995874199998}, {'_key': 2377, '_value': -0.19984995874199998}, {'_key': 3243, '_value': 0.505488198166489}, {'_key': 3567, '_value': 0.28196743128698204}, {'_key': 3699, '_value': -0.27914122434379}, {'_key': 9852, '_value': 0.5663904297633721}, {'_key': 11562, '_value': 0.145367158457186}, {'_key': 11614, '_value': 0.334671699123576}, {'_key': 12057, '_value': 0.366952571787724}, {'_key': 12067, '_value': 0.366952571787724}, {'_key': 12266, '_value': 0.16666599999999998}, {'_key': 12270, '_value': 0.16666599999999998}, {'_key': 16279, '_value': 0.19984995874156103}, {'_key': 17483, '_value': 0.19984995874156103}, {'_key': 22543, '_value': 0.19984995874156103}, {'_key': 22577, '_value': 0.19984995874156103}, {'_key': 22779, '_value': 0.16666599999999998}, {'_key': 22783, '_value': 0.505488198166489}, {'_key': 27915, '_value': 0.126372049541622}, {'_key': 28368, '_value': 0.19984995874156103}, {'_key': 28386, '_value': 0.19984995874156103}, {'_key': 28448, '_value': 0.19984995874156103}, {'_key': 28449, '_value': 0.19984995874156103}, {'_key': 28450, '_value': 0.19984995874156103}, {'_key': 28451, '_value': 0.19984995874156103}, {'_key': 28452, '_value': 0.19984995874156103}, {'_key': 28453, '_value': 0.19984995874156103}, {'_key': 28454, '_value': 0.19984995874156103}, {'_key': 28455, '_value': 0.19984995874156103}, {'_key': 28456, '_value': 0.19984995874156103}, {'_key': 28457, '_value': 0.19984995874156103}, {'_key': 28458, '_value': 0.19984995874156103}, {'_key': 28459, '_value': 0.19984995874156103}, {'_key': 28460, '_value': 0.19984995874156103}, {'_key': 28461, '_value': 0.19984995874156103}, {'_key': 28462, '_value': 0.19984995874156103}, {'_key': 28463, '_value': 0.19984995874156103}, {'_key': 28464, '_value': 0.19984995874156103}, {'_key': 28465, '_value': 0.19984995874156103}, {'_key': 28466, '_value': 0.19984995874156103}, {'_key': 28467, '_value': 0.19984995874156103}, {'_key': 28468, '_value': 0.19984995874156103}, {'_key': 28469, '_value': 0.19984995874156103}, {'_key': 28470, '_value': 0.19984995874156103}, {'_key': 28471, '_value': 0.19984995874156103}, {'_key': 28472, '_value': 0.19984995874156103}, {'_key': 28473, '_value': 0.19984995874156103}, {'_key': 28474, '_value': 0.19984995874156103}, {'_key': 28475, '_value': 0.19984995874156103}, {'_key': 28476, '_value': 0.19984995874156103}, {'_key': 28477, '_value': 0.19984995874156103}, {'_key': 28478, '_value': 0.19984995874156103}, {'_key': 28479, '_value': 0.19984995874156103}, {'_key': 28480, '_value': 0.19984995874156103}, {'_key': 28481, '_value': 0.19984995874156103}, {'_key': 28482, '_value': 0.19984995874156103}, {'_key': 28483, '_value': 0.19984995874156103}, {'_key': 28484, '_value': 0.19984995874156103}, {'_key': 28485, '_value': 0.19984995874156103}, {'_key': 28486, '_value': 0.19984995874156103}, {'_key': 28487, '_value': 0.19984995874156103}, {'_key': 28488, '_value': 0.19984995874156103}, {'_key': 28489, '_value': 0.19984995874156103}, {'_key': 28490, '_value': 0.19984995874156103}, {'_key': 28491, '_value': 0.19984995874156103}, {'_key': 28492, '_value': 0.19984995874156103}, {'_key': 28493, '_value': 0.19984995874156103}, {'_key': 28494, '_value': 0.19984995874156103}, {'_key': 28495, '_value': 0.19984995874156103}, {'_key': 28496, '_value': 0.19984995874156103}, {'_key': 28497, '_value': 0.19984995874156103}, {'_key': 28498, '_value': 0.19984995874156103}, {'_key': 28499, '_value': 0.19984995874156103}, {'_key': 28500, '_value': 0.19984995874156103}, {'_key': 28501, '_value': 0.19984995874156103}, {'_key': 28502, '_value': 0.19984995874156103}, {'_key': 28503, '_value': 0.19984995874156103}, {'_key': 28504, '_value': 0.19984995874156103}, {'_key': 28505, '_value': 0.19984995874156103}, {'_key': 28655, '_value': 0.505488198166489}, {'_key': 32839, '_value': 0.2}, {'_key': 32854, '_value': 0.2}, {'_key': 32855, '_value': 0.2}, {'_key': 38660, '_value': 0.19984995874199998}, {'_key': 40338, '_value': 0.33467169912399997}, {'_key': 40672, '_value': 0.16666599999999998}, {'_key': 40740, '_value': 0.505488198166}, {'_key': 40741, '_value': 0.505488198166}, {'_key': 41221, '_value': 0.366952571788}, {'_key': 41242, '_value': 0.366952571788}, {'_key': 41243, '_value': 1.0}, {'_key': 49100, '_value': 0.505488198166}, {'_key': 56749, '_value': 0.16666599999999998}, {'_key': 60338, '_value': 0.2}, {'_key': 72258, '_value': -1.0}, {'_key': 73248, '_value': -1.0}]

--- Column: 'divisions' (Contains unhashable lists) ---
Sample value: [{'_key': 22, 'divisionNumber': 1, 'leaderID': 3008500, 'size': 37}, {'_key': 23, 'divisionNumber': 2, 'leaderID': 3008486, 'size': 41}, {'_key': 24, 'divisionNumber': 3, 'leaderID': 3008463, 'size': 20}]

--- Column: 'enemyID' (Unique values: 186) ---
Skipping value_counts (high-cardinality numeric: 186 unique)

--- Column: 'factionID' (Unique values: 27) ---

           count
factionID
500001.0      61
500003.0      48
500004.0      44
500002.0      37
500013.0      10

--- Column: 'friendID' (Unique values: 194) ---
Skipping value_counts (high-cardinality numeric: 194 unique)

--- Column: 'iconID' (Unique values: 198) ---
Skipping value_counts (high-cardinality numeric: 198 unique)

--- Column: 'investors' (Contains unhashable lists) ---
Sample value: [{'_key': 1000002, '_value': 42}, {'_key': 1000006, '_value': 9}, {'_key': 1000013, '_value': 14}]

--- Column: 'lpOfferTables' (Contains unhashable lists) ---
Sample value: [6, 9, 58, 62]

--- Column: 'mainActivityID' (Unique values: 20) ---

                count
mainActivityID
5.0                93
14.0               23
3.0                19
7.0                19
18.0               17

--- Column: 'raceID' (Unique values: 8) ---

        count
raceID
1.0        67
8.0        62
4.0        56
2.0        44
16.0       12

--- Column: 'sizeFactor' (Unique values: 5) ---

            count
sizeFactor
1.00           62
1.25           44
1.75           41
1.50           27
2.00           15

--- Column: 'solarSystemID' (Unique values: 202) ---
Skipping value_counts (high-cardinality numeric: 202 unique)

--- Column: 'secondaryActivityID' (Unique values: 14) ---

                     count
secondaryActivityID
5.0                     10
19.0                     4
13.0                     4
2.0                      3
11.0                     2

--- Column: 'exchangeRates' (Contains unhashable lists) ---
Sample value: [{'_key': 1000002, '_value': 0.8}, {'_key': 1000003, '_value': 0.8}, {'_key': 1000004, '_value': 0.8}, {'_key': 1000005, '_value': 0.8}, {'_key': 1000006, '_value': 0.8}, {'_key': 1000007, '_value': 0.8}, {'_key': 1000008, '_value': 0.8}, {'_key': 1000009, '_value': 0.8}, {'_key': 1000010, '_value': 0.8}, {'_key': 1000011, '_value': 0.8}, {'_key': 1000012, '_value': 0.8}, {'_key': 1000013, '_value': 0.8}, {'_key': 1000014, '_value': 0.8}, {'_key': 1000015, '_value': 0.8}, {'_key': 1000016, '_value': 0.8}, {'_key': 1000017, '_value': 0.8}, {'_key': 1000018, '_value': 0.8}, {'_key': 1000019, '_value': 0.8}, {'_key': 1000020, '_value': 0.8}, {'_key': 1000021, '_value': 0.8}, {'_key': 1000022, '_value': 0.8}, {'_key': 1000023, '_value': 0.8}, {'_key': 1000024, '_value': 0.8}, {'_key': 1000025, '_value': 0.8}, {'_key': 1000026, '_value': 0.8}, {'_key': 1000027, '_value': 0.8}, {'_key': 1000028, '_value': 0.8}, {'_key': 1000029, '_value': 0.8}, {'_key': 1000030, '_value': 0.8}, {'_key': 1000031, '_value': 0.8}, {'_key': 1000032, '_value': 0.8}, {'_key': 1000033, '_value': 0.8}, {'_key': 1000034, '_value': 0.8}, {'_key': 1000035, '_value': 0.8}, {'_key': 1000036, '_value': 0.8}, {'_key': 1000037, '_value': 0.8}, {'_key': 1000038, '_value': 0.8}, {'_key': 1000039, '_value': 0.8}, {'_key': 1000040, '_value': 0.8}, {'_key': 1000041, '_value': 0.8}, {'_key': 1000042, '_value': 0.8}, {'_key': 1000043, '_value': 0.8}, {'_key': 1000044, '_value': 0.8}, {'_key': 1000045, '_value': 0.8}, {'_key': 1000046, '_value': 0.8}, {'_key': 1000047, '_value': 0.8}, {'_key': 1000048, '_value': 0.8}, {'_key': 1000049, '_value': 0.8}, {'_key': 1000050, '_value': 0.8}, {'_key': 1000051, '_value': 0.8}, {'_key': 1000052, '_value': 0.8}, {'_key': 1000053, '_value': 0.8}, {'_key': 1000054, '_value': 0.8}, {'_key': 1000055, '_value': 0.8}, {'_key': 1000056, '_value': 0.8}, {'_key': 1000057, '_value': 0.8}, {'_key': 1000058, '_value': 0.8}, {'_key': 1000059, '_value': 0.8}, {'_key': 1000060, '_value': 0.8}, {'_key': 1000061, '_value': 0.8}, {'_key': 1000062, '_value': 0.8}, {'_key': 1000063, '_value': 0.8}, {'_key': 1000064, '_value': 0.8}, {'_key': 1000065, '_value': 0.8}, {'_key': 1000066, '_value': 0.8}, {'_key': 1000067, '_value': 0.8}, {'_key': 1000068, '_value': 0.8}, {'_key': 1000069, '_value': 0.8}, {'_key': 1000070, '_value': 0.8}, {'_key': 1000071, '_value': 0.8}, {'_key': 1000072, '_value': 0.8}, {'_key': 1000073, '_value': 0.8}, {'_key': 1000074, '_value': 0.8}, {'_key': 1000075, '_value': 0.8}, {'_key': 1000076, '_value': 0.8}, {'_key': 1000077, '_value': 0.8}, {'_key': 1000078, '_value': 0.8}, {'_key': 1000079, '_value': 0.8}, {'_key': 1000080, '_value': 0.8}, {'_key': 1000081, '_value': 0.8}, {'_key': 1000082, '_value': 0.8}, {'_key': 1000083, '_value': 0.8}, {'_key': 1000084, '_value': 0.8}, {'_key': 1000085, '_value': 0.8}, {'_key': 1000086, '_value': 0.8}, {'_key': 1000087, '_value': 0.8}, {'_key': 1000088, '_value': 0.8}, {'_key': 1000089, '_value': 0.8}, {'_key': 1000090, '_value': 0.8}, {'_key': 1000091, '_value': 0.8}, {'_key': 1000092, '_value': 0.8}, {'_key': 1000093, '_value': 0.8}, {'_key': 1000094, '_value': 0.8}, {'_key': 1000095, '_value': 0.8}, {'_key': 1000096, '_value': 0.8}, {'_key': 1000097, '_value': 0.8}, {'_key': 1000098, '_value': 0.8}, {'_key': 1000099, '_value': 0.8}, {'_key': 1000100, '_value': 0.8}, {'_key': 1000101, '_value': 0.8}, {'_key': 1000102, '_value': 0.8}, {'_key': 1000103, '_value': 0.8}, {'_key': 1000104, '_value': 0.8}, {'_key': 1000105, '_value': 0.8}, {'_key': 1000106, '_value': 0.8}, {'_key': 1000107, '_value': 0.8}, {'_key': 1000108, '_value': 0.8}, {'_key': 1000109, '_value': 0.8}, {'_key': 1000110, '_value': 0.8}, {'_key': 1000111, '_value': 0.8}, {'_key': 1000112, '_value': 0.8}, {'_key': 1000113, '_value': 0.8}, {'_key': 1000114, '_value': 0.8}, {'_key': 1000115, '_value': 0.8}, {'_key': 1000116, '_value': 0.8}, {'_key': 1000117, '_value': 0.8}, {'_key': 1000118, '_value': 0.8}, {'_key': 1000119, '_value': 0.8}, {'_key': 1000120, '_value': 0.8}, {'_key': 1000121, '_value': 0.8}, {'_key': 1000122, '_value': 0.8}, {'_key': 1000123, '_value': 0.8}, {'_key': 1000126, '_value': 0.8}, {'_key': 1000129, '_value': 0.4}, {'_key': 1000130, '_value': 0.4}, {'_key': 1000139, '_value': 0.4}, {'_key': 1000144, '_value': 0.4}, {'_key': 1000145, '_value': 0.4}, {'_key': 1000146, '_value': 0.4}, {'_key': 1000147, '_value': 0.4}, {'_key': 1000151, '_value': 0.8}, {'_key': 1000152, '_value': 0.8}, {'_key': 1000153, '_value': 0.8}, {'_key': 1000154, '_value': 0.8}, {'_key': 1000156, '_value': 0.8}, {'_key': 1000159, '_value': 0.0}, {'_key': 1000160, '_value': 0.4}, {'_key': 1000163, '_value': 0.4}, {'_key': 1000165, '_value': 0.8}, {'_key': 1000166, '_value': 0.8}, {'_key': 1000167, '_value': 0.8}, {'_key': 1000168, '_value': 0.8}, {'_key': 1000169, '_value': 0.8}, {'_key': 1000170, '_value': 0.8}, {'_key': 1000171, '_value': 0.8}, {'_key': 1000172, '_value': 0.8}]


================================================================================
--- 📊 Analyzing: npcStations.jsonl ---
================================================================================

Loaded 5154 rows in 0.27s

[PRE-PROCESSING]
Flattening 'position' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5154 entries, 0 to 5153
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   _key                      5154 non-null   int64
 1   celestialIndex            5153 non-null   float64
 2   operationID               5154 non-null   int64
 3   orbitID                   5154 non-null   int64
 4   orbitIndex                3968 non-null   float64
 5   ownerID                   5154 non-null   int64
 6   position                  0 non-null      object
 7   reprocessingEfficiency    5154 non-null   float64
 8   reprocessingHangarFlag    5154 non-null   int64
 9   reprocessingStationsTake  5154 non-null   float64
 10  solarSystemID             5154 non-null   int64
 11  typeID                    5154 non-null   int64
 12  useOperationName          5154 non-null   bool
dtypes: bool(1), float64(4), int64(7), object(1)
memory usage: 488.3+ KB


[HEAD]

       _key  celestialIndex  operationID   orbitID  orbitIndex  ownerID position  reprocessingEfficiency  reprocessingHangarFlag  reprocessingStationsTake  solarSystemID  typeID  useOperationName
0  60000004            10.0           26  40176406         3.0  1000002     None                     0.5                       4                      0.05       30002780    1531              True
1  60000007             5.0           26  40176297         9.0  1000002     None                     0.5                       4                      0.05       30002779    1531              True
2  60000010             1.0           26  40176121         NaN  1000002     None                     0.5                       4                      0.05       30002776    1531              True
3  60000013             5.0           26  40176290         2.0  1000002     None                     0.5                       4                      0.05       30002779    1531              True
4  60000016             8.0           26  40176260        13.0  1000002     None                     0.5                       4                      0.05       30002778    1531              True

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 5154) ---
Skipping value_counts (high-cardinality numeric: 5154 unique)

--- Column: 'celestialIndex' (Unique values: 15) ---

                count
celestialIndex
6.0               820
7.0               773
5.0               711
8.0               610
4.0               566

--- Column: 'operationID' (Unique values: 59) ---

             count
operationID
38             495
14             495
26             449
33             324
15             286

--- Column: 'orbitID' (Unique values: 4900) ---
Skipping value_counts (high-cardinality numeric: 4900 unique)

--- Column: 'orbitIndex' (Unique values: 27) ---

            count
orbitIndex
1.0           734
2.0           442
3.0           296
4.0           269
5.0           219

--- Column: 'ownerID' (Unique values: 185) ---
Skipping value_counts (high-cardinality numeric: 185 unique)

--- Column: 'position' (is empty or all null) ---

--- Column: 'reprocessingEfficiency' (Unique values: 6) ---

                        count
reprocessingEfficiency
0.50                     4646
0.30                      262
0.32                      161
0.35                       55
0.25                       18

--- Column: 'reprocessingHangarFlag' (Unique values: 1) ---

                        count
reprocessingHangarFlag
4                        5154

--- Column: 'reprocessingStationsTake' (Unique values: 2) ---

                          count
reprocessingStationsTake
0.050                      5036
0.025                       118

--- Column: 'solarSystemID' (Unique values: 1712) ---
Skipping value_counts (high-cardinality numeric: 1712 unique)

--- Column: 'typeID' (Unique values: 43) ---

        count
typeID
1529      569
1531      503
3865      347
3867      335
3870      301

--- Column: 'useOperationName' (Unique values: 2) ---

                  count
useOperationName
True               4984
False               170

================================================================================
--- 📊 Analyzing: planetResources.jsonl ---
================================================================================

Loaded 25798 rows in 0.27s

[PRE-PROCESSING]
No dictionary columns found to flatten.

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25798 entries, 0 to 25797
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   _key                      25798 non-null  int64
 1   power                     12126 non-null  float64
 2   workforce                 10210 non-null  float64
 3   cycle_minutes             3462 non-null   float64
 4   harvest_silo_max          3462 non-null   float64
 5   maturation_cycle_minutes  3462 non-null   float64
 6   maturation_percent        3462 non-null   float64
 7   mature_silo_max           3462 non-null   float64
 8   reagent_harvest_amount    3462 non-null   float64
 9   reagent_type_id           3462 non-null   float64
dtypes: float64(9), int64(1)
memory usage: 2.0 MB


[HEAD]

       _key  power  workforce  cycle_minutes  harvest_silo_max  maturation_cycle_minutes  maturation_percent  mature_silo_max  reagent_harvest_amount  reagent_type_id
0  40013180  740.0        NaN            NaN               NaN                       NaN                 NaN              NaN                     NaN              NaN
1  40013181    NaN     3490.0            NaN               NaN                       NaN                 NaN              NaN                     NaN              NaN
2  40013183    NaN     2240.0            NaN               NaN                       NaN                 NaN              NaN                     NaN              NaN
3  40013186    NaN     3080.0            NaN               NaN                       NaN                 NaN              NaN                     NaN              NaN
4  40013188    NaN     9220.0            NaN               NaN                       NaN                 NaN              NaN                     NaN              NaN

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 25798) ---
Skipping value_counts (high-cardinality numeric: 25798 unique)

--- Column: 'power' (Unique values: 92) ---

       count
power
500.0    611
650.0    449
550.0    404
680.0    399
620.0    357

--- Column: 'workforce' (Unique values: 873) ---
Skipping value_counts (high-cardinality numeric: 873 unique)

--- Column: 'cycle_minutes' (Unique values: 1) ---

               count
cycle_minutes
60.0            3462

--- Column: 'harvest_silo_max' (Unique values: 492) ---
Skipping value_counts (high-cardinality numeric: 492 unique)

--- Column: 'maturation_cycle_minutes' (Unique values: 1) ---

                          count
maturation_cycle_minutes
4320.0                     3462

--- Column: 'maturation_percent' (Unique values: 1) ---

                    count
maturation_percent
16.0                 3462

--- Column: 'mature_silo_max' (Unique values: 492) ---
Skipping value_counts (high-cardinality numeric: 492 unique)

--- Column: 'reagent_harvest_amount' (Unique values: 492) ---
Skipping value_counts (high-cardinality numeric: 492 unique)

--- Column: 'reagent_type_id' (Unique values: 2) ---

                 count
reagent_type_id
81143.0           2337
81144.0           1125

================================================================================
--- 📊 Analyzing: planetSchematics.jsonl ---
================================================================================

Loaded 68 rows in 0.25s

[PRE-PROCESSING]
Flattening 'name' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68 entries, 0 to 67
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   _key       68 non-null     int64
 1   cycleTime  68 non-null     int64
 2   name       68 non-null     object
 3   pins       68 non-null     object
 4   types      68 non-null     object
dtypes: int64(2), object(3)
memory usage: 2.8+ KB


[HEAD]

   _key  cycleTime             name                                              pins                                              types
0    65       3600  Superconductors  [2470, 2472, 2474, 2480, 2484, 2485, 2491, 2494]  [{'_key': 2389, 'isInput': True, 'quantity': 4...
1    66       3600          Coolant  [2470, 2472, 2474, 2480, 2484, 2485, 2491, 2494]  [{'_key': 2390, 'isInput': True, 'quantity': 4...
2    67       3600      Rocket Fuel  [2470, 2472, 2474, 2480, 2484, 2485, 2491, 2494]  [{'_key': 2389, 'isInput': True, 'quantity': 4...
3    68       3600    Synthetic Oil  [2470, 2472, 2474, 2480, 2484, 2485, 2491, 2494]  [{'_key': 2390, 'isInput': True, 'quantity': 4...
4    69       3600           Oxides  [2470, 2472, 2474, 2480, 2484, 2485, 2491, 2494]  [{'_key': 2317, 'isInput': False, 'quantity': ...

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 68) ---

      count
_key
65        1
66        1
67        1
68        1
69        1

--- Column: 'cycleTime' (Unique values: 2) ---

           count
cycleTime
3600          53
1800          15

--- Column: 'name' (Unique values: 68) ---

                 count
name
Superconductors      1
Coolant              1
Rocket Fuel          1
Synthetic Oil        1
Oxides               1

--- Column: 'pins' (Contains unhashable lists) ---
Sample value: [2470, 2472, 2474, 2480, 2484, 2485, 2491, 2494]

--- Column: 'types' (Contains unhashable lists) ---
Sample value: [{'_key': 2389, 'isInput': True, 'quantity': 40}, {'_key': 3645, 'isInput': True, 'quantity': 40}, {'_key': 9838, 'isInput': False, 'quantity': 5}]


================================================================================
--- 📊 Analyzing: races.jsonl ---
================================================================================

Loaded 11 rows in 0.14s

[PRE-PROCESSING]
Flattening 'description' to English ('en') key...
Flattening 'name' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   _key         11 non-null     int64
 1   description  8 non-null      object
 2   iconID       5 non-null      float64
 3   name         11 non-null     object
 4   shipTypeID   4 non-null      float64
 5   skills       4 non-null      object
dtypes: float64(2), int64(1), object(3)
memory usage: 660.0+ bytes


[HEAD]

   _key                                        description  iconID      name  shipTypeID                                             skills
0     1  Founded on the tenets of patriotism and hard w...  1439.0   Caldari       601.0  [{'_key': 3300, '_value': 4}, {'_key': 3301, '...
1     2  Once a thriving tribal civilization, the Minma...  1440.0  Minmatar       588.0  [{'_key': 3300, '_value': 4}, {'_key': 3302, '...
2     4  The Amarr Empire is the largest and oldest of ...  1442.0     Amarr       596.0  [{'_key': 3300, '_value': 4}, {'_key': 3303, '...
3     8  Champions of liberty and defenders of the down...  1441.0  Gallente       606.0  [{'_key': 3300, '_value': 4}, {'_key': 3301, '...
4    16  The most mysterious and elusive of all the uni...     NaN      Jove         NaN                                                NaN

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 11) ---

      count
_key
1         1
2         1
4         1
8         1
16        1

--- Column: 'description' (Unique values: 8) ---

                                                    count
description
Founded on the tenets of patriotism and hard wo...      1
Once a thriving tribal civilization, the Minmat...      1
The Amarr Empire is the largest and oldest of t...      1
Champions of liberty and defenders of the downt...      1
The most mysterious and elusive of all the univ...      1

--- Column: 'iconID' (Unique values: 5) ---

        count
iconID
1439.0      1
1440.0      1
1442.0      1
1441.0      1
0.0         1

--- Column: 'name' (Unique values: 11) ---

          count
name
Caldari       1
Minmatar      1
Amarr         1
Gallente      1
Jove          1

--- Column: 'shipTypeID' (Unique values: 4) ---

            count
shipTypeID
601.0           1
588.0           1
596.0           1
606.0           1

--- Column: 'skills' (Contains unhashable lists) ---
Sample value: [{'_key': 3300, '_value': 4}, {'_key': 3301, '_value': 1}, {'_key': 3310, '_value': 2}, {'_key': 3311, '_value': 2}, {'_key': 3312, '_value': 2}, {'_key': 3315, '_value': 0}, {'_key': 3316, '_value': 2}, {'_key': 3317, '_value': 1}, {'_key': 3318, '_value': 2}, {'_key': 3319, '_value': 1}, {'_key': 3327, '_value': 3}, {'_key': 3330, '_value': 1}, {'_key': 3342, '_value': 1}, {'_key': 3380, '_value': 1}, {'_key': 3386, '_value': 3}, {'_key': 3392, '_value': 3}, {'_key': 3394, '_value': 2}, {'_key': 3402, '_value': 4}, {'_key': 3411, '_value': 1}, {'_key': 3412, '_value': 3}, {'_key': 3413, '_value': 4}, {'_key': 3417, '_value': 3}, {'_key': 3418, '_value': 3}, {'_key': 3419, '_value': 2}, {'_key': 3420, '_value': 2}, {'_key': 3424, '_value': 1}, {'_key': 3425, '_value': 2}, {'_key': 3426, '_value': 4}, {'_key': 3427, '_value': 1}, {'_key': 3428, '_value': 2}, {'_key': 3429, '_value': 3}, {'_key': 3431, '_value': 2}, {'_key': 3432, '_value': 3}, {'_key': 3435, '_value': 1}, {'_key': 3436, '_value': 1}, {'_key': 3437, '_value': 1}, {'_key': 3443, '_value': 2}, {'_key': 3449, '_value': 3}, {'_key': 3450, '_value': 3}, {'_key': 3453, '_value': 1}, {'_key': 3454, '_value': 1}, {'_key': 3455, '_value': 2}, {'_key': 3551, '_value': 3}, {'_key': 13278, '_value': 1}, {'_key': 16598, '_value': 1}, {'_key': 21718, '_value': 1}, {'_key': 25739, '_value': 1}, {'_key': 25811, '_value': 1}, {'_key': 25863, '_value': 3}, {'_key': 32918, '_value': 1}]


================================================================================
--- 📊 Analyzing: skinLicenses.jsonl ---
================================================================================

Loaded 11528 rows in 0.22s

[PRE-PROCESSING]
No dictionary columns found to flatten.

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11528 entries, 0 to 11527
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   _key           11528 non-null  int64
 1   duration       11528 non-null  int64
 2   licenseTypeID  11528 non-null  int64
 3   skinID         11528 non-null  int64
 4   isSingleUse    4246 non-null   float64
dtypes: float64(1), int64(4)
memory usage: 450.4 KB


[HEAD]

    _key  duration  licenseTypeID  skinID  isSingleUse
0  34599        -1          34599     187          NaN
1  34600        -1          34600     188          NaN
2  34601        -1          34601      44          NaN
3  34602        -1          34602      45          NaN
4  34603        -1          34603       9          NaN

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 11528) ---
Skipping value_counts (high-cardinality numeric: 11528 unique)

--- Column: 'duration' (Unique values: 6) ---

          count
duration
-1         6705
 7         1253
 30        1212
 90        1175
 365       1175

--- Column: 'licenseTypeID' (Unique values: 11528) ---
Skipping value_counts (high-cardinality numeric: 11528 unique)

--- Column: 'skinID' (Unique values: 6697) ---
Skipping value_counts (high-cardinality numeric: 6697 unique)

--- Column: 'isSingleUse' (Unique values: 2) ---

             count
isSingleUse
0.0           4114
1.0            132

================================================================================
--- 📊 Analyzing: skinMaterials.jsonl ---
================================================================================

Loaded 824 rows in 0.24s

[PRE-PROCESSING]
Flattening 'displayName' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 824 entries, 0 to 823
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   _key           824 non-null    int64
 1   displayName    822 non-null    object
 2   materialSetID  824 non-null    int64
dtypes: int64(2), object(1)
memory usage: 19.4+ KB


[HEAD]

   _key displayName  materialSetID
0     1  Ardishapur              1
1     2       Kador              2
2     3       Quafe              3
3     4      Khanid              4
4     5       Sarum              5

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 824) ---
Skipping value_counts (high-cardinality numeric: 824 unique)

--- Column: 'displayName' (Unique values: 343) ---

                        count
displayName
Aurora Universalis         31
Halcyon Dawn               21
Biosecurity Responders     21
Serenity                   13
Capsuleer Day XVIII        12

--- Column: 'materialSetID' (Unique values: 805) ---
Skipping value_counts (high-cardinality numeric: 805 unique)


================================================================================
--- 📊 Analyzing: skins.jsonl ---
================================================================================

Loaded 6699 rows in 0.59s

[PRE-PROCESSING]
Flattening 'skinDescription' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6699 entries, 0 to 6698
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   _key                6699 non-null   int64
 1   allowCCPDevs        6699 non-null   bool
 2   internalName        6699 non-null   object
 3   skinMaterialID      6699 non-null   int64
 4   types               6699 non-null   object
 5   visibleSerenity     6699 non-null   bool
 6   visibleTranquility  6699 non-null   bool
 7   isStructureSkin     939 non-null    float64
 8   skinDescription     2391 non-null   object
dtypes: bool(3), float64(1), int64(2), object(3)
memory usage: 333.8+ KB


[HEAD]

   _key  allowCCPDevs            internalName  skinMaterialID    types  visibleSerenity  visibleTranquility  isStructureSkin skinDescription
0     5          True         Megathron Quafe               3    [641]            False                True              NaN             NaN
1     8          True           Dominix Quafe               3    [645]            False                True              NaN             NaN
2     9          True           Oracle Khanid               4   [4302]            False                True              NaN             NaN
3    10          True            Oracle Sarum               5   [4302]            False                True              NaN             NaN
4    11          True  Prophecy Blood Raiders              25  [16233]             True                True              NaN             NaN

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 6699) ---
Skipping value_counts (high-cardinality numeric: 6699 unique)

--- Column: 'allowCCPDevs' (Unique values: 2) ---

              count
allowCCPDevs
True           6211
False           488

--- Column: 'internalName' (Unique values: 6679) ---

                                 count
internalName
Eagle Gilded Predator                2
Stormbringer Aurora Universalis      2
Brutix Serpentis Serenity Only       2
Thanatos Quafe Serenity Only         2
Rifter Justice                       2

--- Column: 'skinMaterialID' (Unique values: 814) ---
Skipping value_counts (high-cardinality numeric: 814 unique)

--- Column: 'types' (Contains unhashable lists) ---
Sample value: [641]

--- Column: 'visibleSerenity' (Unique values: 2) ---

                 count
visibleSerenity
True              3501
False             3198

--- Column: 'visibleTranquility' (Unique values: 2) ---

                    count
visibleTranquility
True                 5408
False                1291

--- Column: 'isStructureSkin' (Unique values: 2) ---

                 count
isStructureSkin
0.0                935
1.0                  4

--- Column: 'skinDescription' (Unique values: 129) ---

                                                    count
skinDescription
This SKIN will be applied directly to your char...    712
CONCORD Biosecurity Responders are available to...    242
Inner Zone Shipping has increased its internal ...     62
In the icy climes of the Northern Mikramurka on...     60
<i>"Faith is an oasis from which we must draw i...     58

================================================================================
--- 📊 Analyzing: sovereigntyUpgrades.jsonl ---
================================================================================

Loaded 27 rows in 0.31s

[PRE-PROCESSING]
No dictionary columns found to flatten.

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   _key                      27 non-null     int64
 1   fuel_hourly_upkeep        4 non-null      float64
 2   fuel_startup_cost         4 non-null      float64
 3   fuel_type_id              4 non-null      float64
 4   mutually_exclusive_group  27 non-null     object
 5   power_allocation          27 non-null     int64
 6   workforce_allocation      27 non-null     int64
dtypes: float64(3), int64(3), object(1)
memory usage: 1.6+ KB


[HEAD]

    _key  fuel_hourly_upkeep  fuel_startup_cost  fuel_type_id mutually_exclusive_group  power_allocation  workforce_allocation
0  81615               205.0            62000.0       81143.0         Infrastructure_5               250                  1500
1  81619               205.0            82600.0       81143.0         Infrastructure_4               250                  4500
2  81621                25.0             1770.0       81144.0         Infrastructure_3               500                 18100
3  81623                90.0             5305.0       81144.0         Infrastructure_2              1750                 17500
4  82492                 NaN                NaN           NaN                    PvE_A               700                  5400

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 27) ---

       count
_key
81615      1
81619      1
81621      1
81623      1
82492      1

--- Column: 'fuel_hourly_upkeep' (Unique values: 3) ---

                    count
fuel_hourly_upkeep
205.0                   2
25.0                    1
90.0                    1

--- Column: 'fuel_startup_cost' (Unique values: 4) ---

                   count
fuel_startup_cost
62000.0                1
82600.0                1
1770.0                 1
5305.0                 1

--- Column: 'fuel_type_id' (Unique values: 2) ---

              count
fuel_type_id
81143.0           2
81144.0           2

--- Column: 'mutually_exclusive_group' (Unique values: 14) ---

                          count
mutually_exclusive_group
PvE_A                         3
PvE_C                         3
PvE_B                         3
Mining_E                      2
Mining_A                      2

--- Column: 'power_allocation' (Unique values: 12) ---

                  count
power_allocation
500                   9
1350                  7
250                   2
1750                  1
700                   1

--- Column: 'workforce_allocation' (Unique values: 14) ---

                      count
workforce_allocation
12700                     7
6400                      7
5400                      2
18100                     1
4500                      1

================================================================================
--- 📊 Analyzing: stationOperations.jsonl ---
================================================================================

Loaded 66 rows in 0.39s

[PRE-PROCESSING]
Flattening 'description' to English ('en') key...
Flattening 'operationName' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   _key                 66 non-null     int64
 1   activityID           66 non-null     int64
 2   border               66 non-null     float64
 3   corridor             66 non-null     float64
 4   description          54 non-null     object
 5   fringe               66 non-null     float64
 6   hub                  66 non-null     float64
 7   manufacturingFactor  66 non-null     float64
 8   operationName        66 non-null     object
 9   ratio                66 non-null     float64
 10  researchFactor       66 non-null     float64
 11  services             66 non-null     object
 12  stationTypes         47 non-null     object
dtypes: float64(7), int64(2), object(4)
memory usage: 6.8+ KB


[HEAD]

   _key  activityID  border  corridor                                        description  fringe  hub  manufacturingFactor     operationName  ratio  researchFactor                                           services                                       stationTypes
0     1           1     0.0      0.20  Makes livestock and grain that is shipped to f...    0.70  0.1                 0.98        Plantation   0.65            0.98                  [3, 5, 7, 17, 19, 22, 23, 25, 26]  [{'_key': 1, '_value': 1531}, {'_key': 2, '_va...
1     2           1     0.3      0.20          Makes food that is shipped to warehouses.    0.00  0.5                 0.98    Food Packaging   0.20            0.98              [3, 5, 7, 17, 19, 20, 22, 23, 25, 26]  [{'_key': 1, '_value': 4024}, {'_key': 2, '_va...
2     3           1     0.5      0.50  Stores products and shifts goods to external r...    0.00  0.0                 0.98         Warehouse   0.15            0.98              [3, 5, 7, 17, 19, 20, 22, 23, 25, 26]  [{'_key': 1, '_value': 1531}, {'_key': 2, '_va...
3     4           2     0.0      0.10         Mines minerals from asteroid belts/clouds.    0.90  0.0                 0.95           Foundry   0.30            0.98  [1, 3, 5, 7, 13, 14, 17, 19, 20, 21, 22, 23, 2...  [{'_key': 1, '_value': 1529}, {'_key': 2, '_va...
4     5           2     0.1      0.15                Molds finished construction pieces.    0.25  0.5                 0.95  Production Plant   0.50            0.98  [1, 3, 5, 7, 13, 14, 17, 19, 20, 21, 22, 23, 2...  [{'_key': 1, '_value': 1529}, {'_key': 2, '_va...

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 66) ---

      count
_key
1         1
2         1
3         1
4         1
5         1

--- Column: 'activityID' (Unique values: 19) ---

            count
activityID
7              13
20              7
14              6
5               4
3               3

--- Column: 'border' (Unique values: 9) ---

        count
border
0.00       36
0.50       12
0.45        7
0.10        3
0.25        3

--- Column: 'corridor' (Unique values: 7) ---

          count
corridor
0.00         27
0.10         16
0.50         10
0.30          5
0.15          3

--- Column: 'description' (Unique values: 51) ---

                                                    count
description
Stores product and freights goods to external r...      2
Stores product and freights goods to production...      2
Mines minerals from asteroid belts/clouds.              2
Stores products and shifts goods to external re...      1
Makes food that is shipped to warehouses.               1

--- Column: 'fringe' (Unique values: 8) ---

        count
fringe
0.00       48
0.70        4
0.90        4
0.50        4
0.25        2

--- Column: 'hub' (Unique values: 12) ---

      count
hub
0.00     42
0.50      6
0.45      6
0.10      3
0.90      2

--- Column: 'manufacturingFactor' (Unique values: 9) ---

                     count
manufacturingFactor
0.98                    43
0.95                     7
0.97                     5
0.90                     4
0.60                     3

--- Column: 'operationName' (Unique values: 60) ---

                  count
operationName
Warehouse             6
Factory               2
Food Packaging        1
Plantation            1
Production Plant      1

--- Column: 'ratio' (Unique values: 13) ---

       count
ratio
0.0       22
0.2        9
0.3        7
0.1        6
0.8        5

--- Column: 'researchFactor' (Unique values: 9) ---

                count
researchFactor
0.98               48
0.90                4
0.97                3
0.60                3
0.95                3

--- Column: 'services' (Contains unhashable lists) ---
Sample value: [3, 5, 7, 17, 19, 22, 23, 25, 26]

--- Column: 'stationTypes' (Contains unhashable lists) ---
Sample value: [{'_key': 1, '_value': 1531}, {'_key': 2, '_value': 2499}, {'_key': 4, '_value': 1930}, {'_key': 8, '_value': 3866}, {'_key': 16, '_value': 3865}]


================================================================================
--- 📊 Analyzing: stationServices.jsonl ---
================================================================================

Loaded 27 rows in 0.48s

[PRE-PROCESSING]
Flattening 'serviceName' to English ('en') key...
Flattening 'description' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   _key         27 non-null     int64
 1   serviceName  27 non-null     object
 2   description  1 non-null      object
dtypes: int64(1), object(2)
memory usage: 780.0+ bytes


[HEAD]

   _key             serviceName description
0     1         Bounty Missions         NaN
1     2  Assassination Missions         NaN
2     3        Courier Missions         NaN
3     4                Interbus         NaN
4     5      Reprocessing Plant         NaN

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 27) ---

      count
_key
1         1
2         1
3         1
4         1
5         1

--- Column: 'serviceName' (Unique values: 27) ---

                        count
serviceName
Bounty Missions             1
Assassination Missions      1
Courier Missions            1
Interbus                    1
Reprocessing Plant          1

--- Column: 'description' (Unique values: 1) ---

                                  count
description
Used to buy insurance for ships.      1

================================================================================
--- 📊 Analyzing: translationLanguages.jsonl ---
================================================================================

Loaded 8 rows in 0.11s

[PRE-PROCESSING]
No dictionary columns found to flatten.

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   _key    8 non-null      object
 1   name    8 non-null      object
dtypes: object(2)
memory usage: 260.0+ bytes


[HEAD]

  _key     name
0   ru  Russian
1   fr   French
2   en  English
3   zh  Chinese
4   de   German

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 8) ---

      count
_key
ru        1
fr        1
en        1
zh        1
de        1

--- Column: 'name' (Unique values: 8) ---

         count
name
Russian      1
French       1
English      1
Chinese      1
German       1

================================================================================
--- 📊 Analyzing: typeBonus.jsonl ---
================================================================================

Loaded 628 rows in 0.26s

[PRE-PROCESSING]
No dictionary columns found to flatten.

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 628 entries, 0 to 627
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   _key         628 non-null    int64
 1   roleBonuses  468 non-null    object
 2   types        517 non-null    object
 3   iconID       62 non-null     float64
 4   miscBonuses  71 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 24.7+ KB


[HEAD]

   _key                                        roleBonuses                                              types  iconID miscBonuses
0   582  [{'bonus': 300.0, 'bonusText': {'de': 'Bonus a...  [{'_key': 3330, '_value': [{'bonus': 10.0, 'bo...     NaN         NaN
1   583  [{'bonus': 80, 'bonusText': {'de': 'Reduktion ...  [{'_key': 3330, '_value': [{'bonus': 10, 'bonu...     NaN         NaN
2   584                                                NaN  [{'_key': 3330, '_value': [{'bonus': 15, 'bonu...     NaN         NaN
3   585  [{'bonus': 80, 'bonusText': {'de': 'Reduktion ...  [{'_key': 3329, '_value': [{'bonus': 5, 'bonus...     NaN         NaN
4   586  [{'bonus': 5, 'bonusText': {'de': 'Bonus auf d...  [{'_key': 3329, '_value': [{'bonus': 7.5, 'bon...     NaN         NaN

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 628) ---
Skipping value_counts (high-cardinality numeric: 628 unique)

--- Column: 'roleBonuses' (Contains unhashable lists) ---
Sample value: [{'bonus': 300.0, 'bonusText': {'de': 'Bonus auf den Präzisionsabfall von <a href=showinfo:3422>Schildfernboostern</a>', 'en': 'bonus to <a href=showinfo:3422>Remote Shield Booster</a> falloff', 'es': 'de bonificación al alcance efectivo del <a href=showinfo:3422>potenciador de escudo remoto</a>.', 'fr': 'de bonus à la perte du <a href=showinfo:3422>booster de bouclier à distance</a>', 'ja': '<a href=showinfo:3422>リモートシールドブースター</a>の精度低下範囲が改善', 'ko': '<a href=showinfo:3422>원격 실드 부스터</a> 유효사거리 증가', 'ru': 'увеличивается добавочная дальность действия <a href=showinfo:3422>установок дистанционной накачки щитов</a>', 'zh': '<a href=showinfo:3422>远程护盾回充增量器</a>失准范围加成'}, 'importance': 1, 'unitID': 105}]

--- Column: 'types' (Contains unhashable lists) ---
Sample value: [{'_key': 3330, '_value': [{'bonus': 10.0, 'bonusText': {'de': 'Bonus auf die Leistung von <a href=showinfo:3422>Schildfernboostern</a>', 'en': 'bonus to <a href=showinfo:3422>Remote Shield Booster</a> amount', 'es': 'de bonificación a la eficiencia de los <a href=showinfo:3422>potenciadores de escudo remotos</a>.', 'fr': 'de bonus au montant des <a href=showinfo:3422>boosters de bouclier à distance</a>', 'ja': '<a href=showinfo:3422>リモートシールドブースター</a>のブースト量が増加', 'ko': '<a href=showinfo:3422>원격 실드 부스터</a> 회복량 증가', 'ru': 'повышается производительность <a href=showinfo:3422>установок дистанционной накачки щитов</a>', 'zh': '<a href="showinfo:3422">远程护盾回充增量器</a>回充量加成'}, 'importance': 1, 'unitID': 105}, {'bonus': 10.0, 'bonusText': {'de': 'Reduktion der Aktivierungskosten von <a href=showinfo:3422>Schildfernboostern</a>', 'en': 'reduction in <a href=showinfo:3422>Remote Shield Booster</a> activation cost', 'es': 'de reducción del coste de activación del <a href=showinfo:3422>potenciador de escudo remoto</a>.', 'fr': "de réduction du coût d'activation des <a href=showinfo:3422>boosters de bouclier à distance</a>", 'ja': '<a href=showinfo:3422>リモートシールドブースター</a>の起動コストが軽減', 'ko': '<a href=showinfo:3422>원격 실드 부스터</a> 활성화 비용 감소', 'ru': 'сокращается потребление энергии <a href=showinfo:3422>установками дистанционной накачки щитов</a>', 'zh': '<a href="showinfo:3422">远程护盾回充增量器</a>启动消耗减少'}, 'importance': 2, 'unitID': 105}]}]

--- Column: 'iconID' (Unique values: 17) ---

         count
iconID
24304.0      7
24307.0      6
24306.0      6
24303.0      6
24305.0      6

--- Column: 'miscBonuses' (Contains unhashable lists) ---
Sample value: [{'bonusText': {'de': 'Bis zu 10\xa0% Reduktion der Schild- und Panzerungsresistenzen', 'en': 'Up to 10% reduction in shield and armor resistances', 'es': 'Hasta un 10\xa0% de reducción de las resistencias de blindaje y escudo.', 'fr': "Jusqu'à 10\xa0% de réduction des résistances de bouclier et de blindage", 'ja': 'シールドとアーマーレジスタンスが最大10%減少', 'ko': '실드 및 장갑 저항력 최대 10% 감소', 'ru': 'Уменьшение сопротивляемости щитов и брони до 10%', 'zh': '护盾和装甲抗性降低，最多10%'}, 'importance': 2, 'isPositive': False}, {'bonusText': {'de': 'Bis zu 10\xa0% Reduktion des Schadens durch Geschütztürme, Werfer, Drohnen und Smartbombs', 'en': 'Up to 10% reduction in turret, launcher, drone and smartbomb damage', 'es': 'Hasta un 10\xa0% de reducción del daño de torretas, lanzadores, drones y bombas inteligentes.', 'fr': "Jusqu'à 10\xa0% de réduction des dégâts de tourelles, de lanceurs, de drones et de bombes de proximité", 'ja': 'タレット、ランチャー、ドローン、スマートボムのダメージが最大10%減少', 'ko': '터렛, 런처, 드론, 스마트폭탄 피해량 최대 10% 감소', 'ru': 'Уменьшение урона от турелей, пусковых установок, дронов и импульсных излучателей до 10%', 'zh': '炮台、发射器、无人机和立体炸弹的威力被削弱，最多10%'}, 'importance': 3, 'isPositive': False}, {'bonusText': {'de': 'Anziehungsfeld-Störsender sind für das ganze System aktiviert.', 'en': 'System-wide cynosural field jammers are in effect', 'es': 'Se activan los aparatos perturbadores de campo cinosural en todo el sistema.', 'fr': 'Brouilleurs de champ cynosural effectifs dans tout le système en action', 'ja': '全システム用サイノシュラルフィールドジャマー装置が起動中', 'ko': '항성계 전체에 사이노슈럴 필드 재머 작동 중', 'ru': 'Действуют глушители поля приводного маяка с охватом всей системы', 'zh': '全星系遭受反诱导力场干扰'}, 'importance': 4, 'isPositive': False}, {'bonus': 50.0, 'bonusText': {'de': 'Verringerung von CONCORD-Kopfgeldern', 'en': 'reduction in CONCORD bounties', 'es': 'de reducción a las recompensas de CONCORD.', 'fr': 'réduction des primes CONCORD', 'ja': 'CONCORDの懸賞金削減', 'ko': 'CONCORD 현상금 감소', 'ru': 'уменьшение наград, назначенных КОНКОРДом', 'zh': '统合部赏金减少'}, 'importance': 1, 'isPositive': False, 'unitID': 105}]


================================================================================
--- 📊 Analyzing: typeDogma.jsonl ---
================================================================================

Loaded 25788 rows in 1.42s

[PRE-PROCESSING]
No dictionary columns found to flatten.

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25788 entries, 0 to 25787
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   _key             25788 non-null  int64
 1   dogmaAttributes  25788 non-null  object
 2   dogmaEffects     15393 non-null  object
dtypes: int64(1), object(2)
memory usage: 604.5+ KB


[HEAD]

   _key                                    dogmaAttributes dogmaEffects
0    18  [{'attributeID': 182, 'value': 3386.0}, {'attr...          NaN
1    19  [{'attributeID': 182, 'value': 3386.0}, {'attr...          NaN
2    20  [{'attributeID': 182, 'value': 3386.0}, {'attr...          NaN
3    21  [{'attributeID': 182, 'value': 3386.0}, {'attr...          NaN
4    22  [{'attributeID': 182, 'value': 3386.0}, {'attr...          NaN

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 25788) ---
Skipping value_counts (high-cardinality numeric: 25788 unique)

--- Column: 'dogmaAttributes' (Contains unhashable lists) ---
Sample value: [{'attributeID': 182, 'value': 3386.0}, {'attributeID': 277, 'value': 1.0}, {'attributeID': 790, 'value': 60377.0}, {'attributeID': 1980, 'value': 0.5}, {'attributeID': 2115, 'value': 0.0}, {'attributeID': 2699, 'value': 1.0}, {'attributeID': 2711, 'value': 18.0}]

--- Column: 'dogmaEffects' (Contains unhashable lists) ---
Sample value: [{'effectID': 596, 'isDefault': False}, {'effectID': 600, 'isDefault': False}, {'effectID': 1173, 'isDefault': False}]


================================================================================
--- 📊 Analyzing: typeMaterials.jsonl ---
================================================================================

Loaded 9430 rows in 0.27s

[PRE-PROCESSING]
No dictionary columns found to flatten.

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9430 entries, 0 to 9429
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   _key       9430 non-null   int64
 1   materials  9430 non-null   object
dtypes: int64(1), object(1)
memory usage: 147.5+ KB


[HEAD]

   _key                                          materials
0    18  [{'materialTypeID': 34, 'quantity': 175}, {'ma...
1    19  [{'materialTypeID': 34, 'quantity': 48000}, {'...
2    20  [{'materialTypeID': 36, 'quantity': 60}, {'mat...
3    21  [{'materialTypeID': 35, 'quantity': 450}, {'ma...
4    22  [{'materialTypeID': 35, 'quantity': 3200}, {'m...

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 9430) ---
Skipping value_counts (high-cardinality numeric: 9430 unique)

--- Column: 'materials' (Contains unhashable lists) ---
Sample value: [{'materialTypeID': 34, 'quantity': 175}, {'materialTypeID': 36, 'quantity': 70}]


================================================================================
--- 📊 Analyzing: types.jsonl ---
================================================================================

Loaded 50488 rows in 4.64s

[PRE-PROCESSING]
Flattening 'name' to English ('en') key...
Flattening 'description' to English ('en') key...

[INFO]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50488 entries, 0 to 50487
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   _key                   50488 non-null  int64
 1   groupID                50488 non-null  int64
 2   mass                   20285 non-null  float64
 3   name                   50488 non-null  object
 4   portionSize            50488 non-null  int64
 5   published              50488 non-null  bool
 6   volume                 45085 non-null  float64
 7   radius                 14867 non-null  float64
 8   description            32679 non-null  object
 9   graphicID              17458 non-null  float64
 10  soundID                4956 non-null   float64
 11  iconID                 21920 non-null  float64
 12  raceID                 22508 non-null  float64
 13  basePrice              13725 non-null  float64
 14  marketGroupID          18791 non-null  float64
 15  capacity               9450 non-null   float64
 16  metaGroupID            13251 non-null  float64
 17  variationParentTypeID  4739 non-null   float64
 18  factionID              1320 non-null   float64
dtypes: bool(1), float64(13), int64(3), object(2)
memory usage: 7.0+ MB


[HEAD]

   _key  groupID  mass           name  portionSize  published  volume        radius description  graphicID  soundID  iconID  raceID  basePrice  marketGroupID  capacity  metaGroupID  variationParentTypeID  factionID
0     0        0   1.0        #System            1      False     NaN           NaN         NaN        NaN      NaN     NaN     NaN        NaN            NaN       NaN          NaN                    NaN        NaN
1     2        2   NaN    Corporation            1      False     NaN           NaN         NaN        NaN      NaN     NaN     NaN        NaN            NaN       NaN          NaN                    NaN        NaN
2     3        3   NaN         Region            1      False     1.0           NaN         NaN        NaN      NaN     NaN     NaN        NaN            NaN       NaN          NaN                    NaN        NaN
3     4        4   NaN  Constellation            1      False     1.0           NaN         NaN        NaN      NaN     NaN     NaN        NaN            NaN       NaN          NaN                    NaN        NaN
4     5        5   NaN   Solar System            1      False     1.0  5.000000e+12         NaN        NaN      NaN     NaN     NaN        NaN            NaN       NaN          NaN                    NaN        NaN

[VALUE COUNTS (Top 5 for hashable columns)]

--- Column: '_key' (Unique values: 50488) ---
Skipping value_counts (high-cardinality numeric: 50488 unique)

--- Column: 'groupID' (Unique values: 1453) ---
Skipping value_counts (high-cardinality numeric: 1453 unique)

--- Column: 'mass' (Unique values: 499) ---
Skipping value_counts (high-cardinality numeric: 499 unique)

--- Column: 'name' (Unique values: 48599) ---

                                count
name
Deathless Circle Data Fragment    229
Partially Corrupted Cryschip      120
Expired Proving Filament           68
Corrupted Trinary Data Vault       60
Wormhole C729                      27

--- Column: 'portionSize' (Unique values: 16) ---

             count
portionSize
1            49208
100            992
5000           102
250             76
500             28

--- Column: 'published' (Unique values: 2) ---

           count
published
True       26001
False      24487

--- Column: 'volume' (Unique values: 305) ---
Skipping value_counts (high-cardinality numeric: 305 unique)

--- Column: 'radius' (Unique values: 615) ---
Skipping value_counts (high-cardinality numeric: 615 unique)

--- Column: 'description' (Unique values: 13363) ---

                                                    count
description
Emblems by Paragon bring new light to your ship...    792
This SKIN will be applied directly to your char...    511
The remains of a destroyed ship. Perhaps with t...    282
CONCORD Biosecurity Responders are available to...    247
Encoded with identifiers of the elusive "Deathl...    228

--- Column: 'graphicID' (Unique values: 3892) ---
Skipping value_counts (high-cardinality numeric: 3892 unique)

--- Column: 'soundID' (Unique values: 180) ---
Skipping value_counts (high-cardinality numeric: 180 unique)

--- Column: 'iconID' (Unique values: 3409) ---
Skipping value_counts (high-cardinality numeric: 3409 unique)

--- Column: 'raceID' (Unique values: 11) ---

        count
raceID
4.0      7000
1.0      5048
2.0      4261
8.0      4216
128.0     883

--- Column: 'basePrice' (Unique values: 1535) ---
Skipping value_counts (high-cardinality numeric: 1535 unique)

--- Column: 'marketGroupID' (Unique values: 1559) ---
Skipping value_counts (high-cardinality numeric: 1559 unique)

--- Column: 'capacity' (Unique values: 329) ---
Skipping value_counts (high-cardinality numeric: 329 unique)

--- Column: 'metaGroupID' (Unique values: 13) ---

             count
metaGroupID
4.0           2715
1.0           2615
2.0           2302
19.0          1433
17.0          1337

--- Column: 'variationParentTypeID' (Unique values: 1227) ---
Skipping value_counts (high-cardinality numeric: 1227 unique)

--- Column: 'factionID' (Unique values: 29) ---

           count
factionID
500026.0     209
500027.0     165
500002.0     115
500004.0     112
500003.0     101

--- Full Analysis Loop Finished ---

The files fall under 3 main functional categories:

**1. Universe Geography (The "Map")**
This group defines the physical layout of the EVE universe. The files are all linked in a clear hierarchy (a region contains constellations, which contain solar systems, etc.).

* mapRegions.jsonl

* mapConstellations.jsonl

* mapSolarSystems.jsonl

* mapPlanets.jsonl

* mapMoons.jsonl

* mapStargates.jsonl

* mapStars.jsonl

**2. Item & Blueprint Definitions (The "Things")**
This group defines every single item in the game, from a ship to a piece of ore to a skillbook. It also uses a hierarchy (categories contain groups, which contain types).

* categories.jsonl (Highest level: "Ship", "Module", "Skill")

* groups.jsonl (Mid-level: "Frigate", "Cruiser", "Laser Turret")

* types.jsonl (The master file for all items: "Kestrel", "Rifter", "1MN Afterburner I")

* blueprints.jsonl (Defines manufacturing requirements)

* graphics.jsonl, icons.jsonl (Visual assets for the items)

**3. Factions, NPCs, and Stations (The "Entities")**
This group defines all the non-player characters and organizations, including who they are, who they work for, and where their stations are located.

* factions.jsonl (e.g., "Caldari State", "Gallente Federation")

* races.jsonl (e.g., "Caldari", "Gallente")

* npcCorporations.jsonl (The specific NPC companies)

* npcStations.jsonl (Links corporations to solar systems)

* agentsInSpace.jsonl (Links agents to corporations)

# Data Visualization (Plotly)

These cells use Plotly Express to create interactive visualizations for different aspects of the dataset. Each cell joins 2-4 files to build the necessary data.

* Treemap: Shows the hierarchy of all items (Categories -> Groups).

* Force-Directed Graph: Shows the ownership network (Factions -> Corporations -> Stations).

* Bar Chart: Shows the count of items by Race.

* 3D Scatter Plot: Creates a 3D map of the EVE universe by plotting mapSolarSystems.jsonl and coloring by mapRegions.jsonl.

## Treemap

In [ ]:
import pandas as pd
import plotly.express as px
import sys
import time
import io

# --- 1. Install Plotly ---
print("Installing plotly...")
!pip install -q plotly

# --- 2. Configuration ---
BUCKET_NAME = "eve-online-foundation-data"
GCS_PATH = f"gs://{BUCKET_NAME}"

# --- 3. Helper Function ---
def load_and_flatten_name(filename, gcs_path=GCS_PATH, id_col='_key', name_col='name'):
    """Loads a JSONL file from GCS, flattens its 'name' column, and renames its ID."""
    print(f"Loading & flattening: {filename}...")
    try:
        df = pd.read_json(f"{gcs_path}/{filename}", lines=True)

        # Flatten the name column (e.g., name['en'])
        if name_col in df.columns:
            new_col_name = f"{filename.split('.')[0]}_name_en"
            df[new_col_name] = df[name_col].apply(
                lambda x: x.get('en') if isinstance(x, dict) else None
            )
            # We don't drop the original 'name' in case we need it

        # Rename the primary key
        if id_col in df.columns:
            df = df.rename(columns={id_col: f'{filename.split(".")[0]}_id'})

        return df
    except Exception as e:
        print(f"FAILED to load {filename}. Error: {e}")
        return None

# --- 4. Main Data Loading and Merging ---
print("\n--- Building Hierarchy for Treemap ---")
start_time = time.time()

# Load the three key tables
df_types = load_and_flatten_name("types.jsonl")
df_groups = load_and_flatten_name("groups.jsonl")
df_categories = load_and_flatten_name("categories.jsonl")

# We only care about published items
df_types_published = df_types[df_types['published'] == True]

print("Merging tables...")
# Merge types -> groups
df_merged = pd.merge(
    df_types_published[['types_id', 'groupID', 'types_name_en']],
    df_groups[['groups_id', 'categoryID', 'groups_name_en']],
    left_on='groupID',
    right_on='groups_id',
    how='left'
)

# Merge result -> categories
df_full_hierarchy = pd.merge(
    df_merged,
    df_categories[['categories_id', 'categories_name_en']],
    left_on='categoryID',
    right_on='categories_id',
    how='left'
)

# Handle cases where items might not have a group or category
df_full_hierarchy['categories_name_en'] = df_full_hierarchy['categories_name_en'].fillna('Unknown Category')
df_full_hierarchy['groups_name_en'] = df_full_hierarchy['groups_name_en'].fillna('Unknown Group')

print(f"Data prepared in {time.time() - start_time:.2f}s")

# --- 5. Create the Treemap ---
print("\n--- Generating Treemap ---")
# To use the treemap, we need to group and count the items
df_grouped = df_full_hierarchy.groupby(
    ['categories_name_en', 'groups_name_en']
).size().reset_index(name='item_count')

# Create the plot
fig = px.treemap(
    df_grouped,
    # The 'path' defines the hierarchy. We add a root node "All Items".
    path=[px.Constant("All Published Items"), 'categories_name_en', 'groups_name_en'],
    # The 'values' defines the size of each box
    values='item_count',
    # 'color' can be used to shade by a value, here we use item_count again
    color='item_count',
    color_continuous_scale='Blues',
    title='EVE Online: Breakdown of All Published Items'
)

# Improve the hover data
fig.update_traces(
    hovertemplate='<b>%{label}</b><br>Item Count: %{value}<br>Parent: %{parent}'
)

fig.update_layout(margin = dict(t=50, l=25, r=25, b=25))

# Display the interactive plot in Colab
fig.show()

Installing plotly...

--- Building Hierarchy for Treemap ---
Loading & flattening: types.jsonl...
Loading & flattening: groups.jsonl...
Loading & flattening: categories.jsonl...
Merging tables...
Data prepared in 4.33s

--- Generating Treemap ---

## Faction & Station Ownership: Force-Directed Graph

In [ ]:
import pandas as pd
import plotly.graph_objects as go
import networkx as nx # For graph layout
import sys
import time

# --- 1. Configuration (ensure GCS_PATH is defined) ---
BUCKET_NAME = "eve-online-foundation-data"
GCS_PATH = f"gs://{BUCKET_NAME}"

# --- 2. Helper Function (Copy from Cell 2) ---
def load_and_flatten_name(filename, gcs_path=GCS_PATH, id_col='_key', name_col='name'):
    """Loads a JSONL file from GCS, flattens its 'name' column, and renames its ID."""
    print(f"Loading & flattening: {filename}...")
    try:
        df = pd.read_json(f"{gcs_path}/{filename}", lines=True)

        # Flatten the name column (e.g., name['en'])
        if name_col in df.columns:
            new_col_name = f"{filename.split('.')[0]}_name_en"
            df[new_col_name] = df[name_col].apply(
                lambda x: x.get('en') if isinstance(x, dict) else None
            )
            # For network graphs, we often prefer a single name column
            df[name_col] = df[new_col_name] # Overwrite 'name' with English version
            df = df.drop(columns=[new_col_name]) # Drop the _name_en if 'name' is overwritten

        # Flatten 'description' column if present
        if 'description' in df.columns and any(isinstance(x, dict) for x in df['description'].dropna()):
            df['description'] = df['description'].apply(
                lambda x: x.get('en') if isinstance(x, dict) else x
            )

        # Rename the primary key
        if id_col in df.columns:
            df = df.rename(columns={id_col: f'{filename.split(".")[0]}_id'})

        return df
    except Exception as e:
        print(f"FAILED to load {filename}. Error: {e}")
        return None

# --- 3. Main Data Loading and Graph Construction (Corrected) ---
print("\n--- Building Data for Force-Directed Graph ---")
start_time = time.time()

# Load and flatten relevant dataframes
df_factions = load_and_flatten_name("factions.jsonl", name_col='name')
df_corporations = load_and_flatten_name("npcCorporations.jsonl", name_col='name')
# 'npcStations' does not have a 'name' column, so we don't pass 'name_col'
df_stations = load_and_flatten_name("npcStations.jsonl")
df_types = load_and_flatten_name("types.jsonl", name_col='name')

# --- Create Nodes ---
# Add a 'type' column for coloring/sizing
df_factions['node_type'] = 'Faction'
df_corporations['node_type'] = 'Corporation'
df_stations['node_type'] = 'Station'

# Get Station Type names
df_station_types = df_types[['types_id', 'name']].rename(columns={
    'types_id': 'typeID',
    'name': 'stationTypeName'
})
# Join the type name to the stations
df_stations = pd.merge(df_stations, df_station_types, on='typeID', how='left')

# Consolidate all nodes into a single DataFrame
all_nodes = pd.concat([
    # Factions
    df_factions.rename(columns={'factions_id': 'id', 'name': 'node_name'})
               [['id', 'node_name', 'node_type']],
    # Corporations
    df_corporations.rename(columns={'npcCorporations_id': 'id', 'name': 'node_name'})
                   [['id', 'node_name', 'node_type', 'factionID']],
    # Stations (using stationTypeName as the name)
    df_stations.rename(columns={'npcStations_id': 'id', 'stationTypeName': 'node_name', 'ownerID': 'corporationID'})
               [['id', 'node_name', 'node_type', 'corporationID']]
], ignore_index=True, sort=False)

# Clean up names (some station types might be null)
all_nodes['node_name'] = all_nodes['node_name'].fillna('Unknown Station Type')


# --- Create Edges (Links) ---
# Faction owns Corporation
faction_corp_edges = df_corporations.dropna(subset=['factionID']).apply(
    lambda row: {'source': row['factionID'], 'target': row['npcCorporations_id'], 'relation': 'Owns'}, axis=1
).tolist()

# Corporation owns Station
# Use 'ownerID' and 'npcStations_id' from the original df_stations
corp_station_edges = df_stations.dropna(subset=['ownerID']).apply(
    lambda row: {'source': row['ownerID'], 'target': row['npcStations_id'], 'relation': 'Owns'}, axis=1
).tolist()

all_edges = faction_corp_edges + corp_station_edges

# Filter out nodes not involved in any relationship to reduce clutter
involved_nodes_ids = set([edge['source'] for edge in all_edges] + [edge['target'] for edge in all_edges])
all_nodes_filtered = all_nodes[all_nodes['id'].isin(involved_nodes_ids)].copy()

print(f"Graph data prepared with {len(all_nodes_filtered)} nodes and {len(all_edges)} edges in {time.time() - start_time:.2f}s")

# --- 4. Build NetworkX Graph and Layout ---
G = nx.Graph()

for _, row in all_nodes_filtered.iterrows():
    G.add_node(row['id'],
               name=row['node_name'],
               type=row['node_type'],
               size=5 if row['node_type'] == 'Station' else (10 if row['node_type'] == 'Corporation' else 15), # Visual sizing
               hover_text=f"<b>{row['node_name']}</b><br>Type: {row['node_type']}<br>ID: {row['id']}")

for edge in all_edges:
    # Ensure source and target nodes exist in the filtered graph
    if edge['source'] in G and edge['target'] in G:
        G.add_edge(edge['source'], edge['target'], relation=edge['relation'])

# Use a spring layout for better visualization of clusters
pos = nx.spring_layout(G, k=0.1, iterations=50, seed=42) # k adjusts distance

# --- 5. Create Plotly Figure ---
print("--- Generating Force-Directed Graph ---")

edge_x = []
edge_y = []
for edge in G.edges():
    x0, y0 = pos[edge[0]]
    x1, y1 = pos[edge[1]]
    edge_x.append(x0)
    edge_x.append(x1)
    edge_x.append(None) # Separates segments
    edge_y.append(y0)
    edge_y.append(y1)
    edge_y.append(None)

edge_trace = go.Scatter(
    x=edge_x, y=edge_y,
    line=dict(width=0.5, color='#888'),
    hoverinfo='none',
    mode='lines')

node_x = []
node_y = []
node_text = []
node_size = []
node_color = []

node_colors_map = {
    'Faction': '#FF5733',     # Red
    'Corporation': '#337BFF', # Blue
    'Station': '#33FF57'      # Green
}

for node in G.nodes():
    x, y = pos[node]
    node_x.append(x)
    node_y.append(y)
    node_text.append(G.nodes[node]['hover_text'])
    node_size.append(G.nodes[node]['size'] * 2) # Adjust for better visibility
    node_color.append(node_colors_map.get(G.nodes[node]['type'], 'gray'))

node_trace = go.Scatter(
    x=node_x, y=node_y,
    mode='markers',
    hoverinfo='text',
    text=node_text,
    marker=dict(
        showscale=False,
        color=node_color,
        size=node_size,
        line_width=2))

fig = go.Figure(data=[edge_trace, node_trace],
             layout=go.Layout(
                title='<br>EVE Online: Faction, Corporation, and Station Ownership Network',
                titlefont_size=16,
                showlegend=False,
                hovermode='closest',
                margin=dict(b=20,l=5,r=5,t=40),
                annotations=[ dict(
                    text="Red: Faction | Blue: Corporation | Green: Station",
                    showarrow=False,
                    xref="paper", yref="paper",
                    x=0.005, y=-0.002 ) ],
                xaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
                yaxis=dict(showgrid=False, zeroline=False, showticklabels=False))
                )
fig.show()

print("Graph generation complete.")

--- Building Data for Force-Directed Graph ---
Loading & flattening: factions.jsonl...
Loading & flattening: npcCorporations.jsonl...
Loading & flattening: npcStations.jsonl...
Loading & flattening: types.jsonl...
Graph data prepared with 5455 nodes and 5427 edges in 7.34s
--- Generating Force-Directed Graph ---

Graph generation complete.

## Bar Chart (Items by Race)

In [ ]:
import pandas as pd
import plotly.express as px
import sys
import time
import io

# --- 1. Configuration (ensure GCS_PATH and helper function are in memory) ---
# This assumes GCS_PATH is set and load_and_flatten_name() is defined
# in a previous cell (like Cell 2).

print("--- Building Bar Chart: Item Types by Race ---")
start_time = time.time()

try:
    # --- 2. Load Data ---
    print("Loading types.jsonl (only key columns)...")
    # We can optimize by only loading the columns we need
    df_types = pd.read_json(
        f"{GCS_PATH}/types.jsonl",
        lines=True,
        dtype={'raceID': 'float'} # Ensure raceID is float to handle NaNs
    )
    # Filter for published items and keep only what we need
    df_types_published = df_types[
        df_types['published'] == True
    ][['_key', 'raceID']].rename(columns={'_key': 'types_id'})

    # Load and flatten races
    df_races = load_and_flatten_name("races.jsonl", name_col='name')
    df_races = df_races[['races_id', 'name']] # Keep only ID and name

    print("Merging data...")
    # --- 3. Merge Data ---
    df_merged = pd.merge(
        df_types_published,
        df_races,
        left_on='raceID',
        right_on='races_id',
        how='left' # Keep all types, even those with no race
    )

    # --- 4. Clean and Group ---
    # Items with no race (raceID is NaN) are important! Let's label them.
    df_merged['name'] = df_merged['name'].fillna('Race: None')

    print("Grouping and counting...")
    df_counts = df_merged.groupby('name').size().reset_index(name='item_count')
    df_counts = df_counts.sort_values(by='item_count', ascending=False)

    print(f"Data prepared in {time.time() - start_time:.2f}s")

    # --- 5. Plot ---
    print("\n--- Generating Bar Chart ---")
    fig = px.bar(
        df_counts,
        x='name',
        y='item_count',
        color='name',
        title='EVE Online: Count of Published Items by Race',
        labels={'name': 'Race', 'item_count': 'Number of Published Items'}
    )

    fig.update_layout(xaxis_title="Race", yaxis_title="Item Count")
    fig.show()

except Exception as e:
    print(f"*** FAILED to build bar chart. Error: {e} ***")

--- Building Bar Chart: Item Types by Race ---
Loading types.jsonl (only key columns)...
Loading & flattening: races.jsonl...
Merging data...
Grouping and counting...
Data prepared in 7.96s

--- Generating Bar Chart ---

## Spatial Data: 3D Scatter Plots

In [ ]:
import pandas as pd
import plotly.express as px
import sys
import time
import io

# --- 1. Configuration (ensure GCS_PATH and helper function are in memory) ---
# This assumes GCS_PATH is set and load_and_flatten_name() is defined
# in a previous cell (like Cell 2).

print("--- Building 3D Solar System Map ---")
start_time = time.time()

try:
    # --- 2. Load Data ---
    print("Loading mapSolarSystems.jsonl...")
    df_systems = load_and_flatten_name("mapSolarSystems.jsonl", name_col='name')
    # Rename the flattened name for clarity
    df_systems = df_systems.rename(columns={'name': 'system_name_en'})

    print("Loading mapRegions.jsonl...")
    df_regions = load_and_flatten_name("mapRegions.jsonl", name_col='name')

    # Use the correct 'mapRegions_id'
    df_regions = df_regions[['mapRegions_id', 'name']].rename(columns={'name': 'region_name_en'})

    print("Merging data...")
    # --- 3. Merge Data ---
    df_merged = pd.merge(
        df_systems,
        df_regions,
        left_on='regionID',
        right_on='mapRegions_id', # Corrected column name
        how='left'
    )

    # Handle any systems without a region
    df_merged['region_name_en'] = df_merged['region_name_en'].fillna('Unknown Region')

    # --- 4. Un-nest the 'position' column ---
    print("Un-nesting 'position' column...")
    pos_df = pd.json_normalize(df_merged['position'])

    # Join the new x, y, z columns back to the main DataFrame
    df_final_map = pd.concat([df_merged, pos_df], axis=1)

    print(f"Data prepared in {time.time() - start_time:.2f}s")

    # --- 5. Plot ---
    print("\n--- Generating 3D Scatter Plot ---")

    fig = px.scatter_3d(
        df_final_map, # Use the final, un-nested DataFrame
        x='x',
        y='y',
        z='z',
        color='region_name_en',      # Color-code by region name
        hover_name='system_name_en', # Show system name on hover
        hover_data={                 # Add extra data to hover
            'region_name_en': True,
            'securityStatus': True,
            'x': False, # Hide coordinates from hover box
            'y': False,
            'z': False
        },
        title='3D Map of the EVE Online Universe'
    )

    # --- 6. Clean up the plot ---
    fig.update_traces(marker=dict(size=1.5))
    fig.update_layout(
        title_text='3D Map of the EVE Online Universe (Colored by Region)',
        scene=dict(
            xaxis_title='X Coordinate',
            yaxis_title='Y Coordinate',
            zaxis_title='Z Coordinate',
            bgcolor='rgb(10, 10, 10)' # Dark background
        ),
        legend_title_text='Region'
    )

    fig.show()

except Exception as e:
    print(f"*** FAILED to build 3D map. Error: {e} ***")

--- Building 3D Solar System Map ---
Loading mapSolarSystems.jsonl...
Loading & flattening: mapSolarSystems.jsonl...
Loading mapRegions.jsonl...
Loading & flattening: mapRegions.jsonl...
Merging data...
Un-nesting 'position' column...
Data prepared in 0.59s

--- Generating 3D Scatter Plot ---

# Helper Functions

In [ ]:
import pandas as pd
import sys

# --- 1. Configuration (ensure GCS_PATH is defined) ---
BUCKET_NAME = "eve-online-foundation-data"
GCS_PATH = f"gs://{BUCKET_NAME}"

# --- 2. Helper Function (Copy from Cell 2) ---
def load_and_flatten_name(filename, gcs_path=GCS_PATH, id_col='_key', name_col='name'):
    """Loads a JSONL file from GCS, flattens its 'name' column, and renames its ID."""
    print(f"Loading & flattening: {filename}...")
    try:
        df = pd.read_json(f"{gcs_path}/{filename}", lines=True)

        # Flatten the name column (e.g., name['en'])
        if name_col in df.columns:
            new_col_name = f"{filename.split('.')[0]}_name_en"
            df[new_col_name] = df[name_col].apply(
                lambda x: x.get('en') if isinstance(x, dict) else None
            )
            # For network graphs, we often prefer a single name column
            df[name_col] = df[new_col_name] # Overwrite 'name' with English version
            df = df.drop(columns=[new_col_name]) # Drop the _name_en if 'name' is overwritten

        # Flatten 'description' column if present
        if 'description' in df.columns and any(isinstance(x, dict) for x in df['description'].dropna()):
            df['description'] = df['description'].apply(
                lambda x: x.get('en') if isinstance(x, dict) else x
            )

        # Rename the primary key
        if id_col in df.columns:
            df = df.rename(columns={id_col: f'{filename.split(".")[0]}_id'})

        return df
    except Exception as e:
        print(f"FAILED to load {filename}. Error: {e}")
        return None

# --- 3. Run the Debug ---
print("--- Debugging DataFrame Schemas ---")

try:
    print("\n[INFO] df_factions:")
    df_factions = load_and_flatten_name("factions.jsonl", name_col='name')
    df_factions.info()

    print("\n[INFO] df_corporations:")
    df_corporations = load_and_flatten_name("npcCorporations.jsonl", name_col='name')
    df_corporations.info()

    print("\n[INFO] df_stations:")
    df_stations = load_and_flatten_name("npcStations.jsonl", name_col='name')
    df_stations.info()

except Exception as e:
    print(f"\n*** FAILED during debug. Error: {e} ***")

print("\n--- Debug Script Finished ---")

--- Debugging DataFrame Schemas ---

[INFO] df_factions:
Loading & flattening: factions.jsonl...
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   factions_id           27 non-null     int64
 1   corporationID         26 non-null     float64
 2   description           27 non-null     object
 3   flatLogo              18 non-null     object
 4   flatLogoWithName      6 non-null      object
 5   iconID                27 non-null     int64
 6   memberRaces           27 non-null     object
 7   militiaCorporationID  6 non-null      float64
 8   name                  27 non-null     object
 9   shortDescription      4 non-null      object
 10  sizeFactor            27 non-null     int64
 11  solarSystemID         27 non-null     int64
 12  uniqueName            27 non-null     bool
dtypes: bool(1), float64(2), int64(4), object(6)
memory usage: 2.7+ KB

[INFO] df_corporations:
Loading & flattening: npcCorporations.jsonl...
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 283 entries, 0 to 282
Data columns (total 33 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   npcCorporations_id          283 non-null    int64
 1   ceoID                       260 non-null    float64
 2   deleted                     283 non-null    bool
 3   description                 280 non-null    object
 4   extent                      283 non-null    object
 5   hasPlayerPersonnelManager   283 non-null    bool
 6   initialPrice                283 non-null    int64
 7   memberLimit                 283 non-null    int64
 8   minSecurity                 283 non-null    int64
 9   minimumJoinStanding         283 non-null    int64
 10  name                        283 non-null    object
 11  sendCharTerminationMessage  283 non-null    bool
 12  shares                      283 non-null    int64
 13  size                        283 non-null    object
 14  stationID                   262 non-null    float64
 15  taxRate                     283 non-null    float64
 16  tickerName                  283 non-null    object
 17  uniqueName                  283 non-null    bool
 18  allowedMemberRaces          212 non-null    object
 19  corporationTrades           184 non-null    object
 20  divisions                   118 non-null    object
 21  enemyID                     250 non-null    float64
 22  factionID                   273 non-null    float64
 23  friendID                    246 non-null    float64
 24  iconID                      252 non-null    float64
 25  investors                   227 non-null    object
 26  lpOfferTables               181 non-null    object
 27  mainActivityID              266 non-null    float64
 28  raceID                      257 non-null    float64
 29  sizeFactor                  189 non-null    float64
 30  solarSystemID               261 non-null    float64
 31  secondaryActivityID         34 non-null     float64
 32  exchangeRates               1 non-null      object
dtypes: bool(4), float64(12), int64(6), object(11)
memory usage: 65.4+ KB

[INFO] df_stations:
Loading & flattening: npcStations.jsonl...
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5154 entries, 0 to 5153
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   npcStations_id            5154 non-null   int64
 1   celestialIndex            5153 non-null   float64
 2   operationID               5154 non-null   int64
 3   orbitID                   5154 non-null   int64
 4   orbitIndex                3968 non-null   float64
 5   ownerID                   5154 non-null   int64
 6   position                  5154 non-null   object
 7   reprocessingEfficiency    5154 non-null   float64
 8   reprocessingHangarFlag    5154 non-null   int64
 9   reprocessingStationsTake  5154 non-null   float64
 10  solarSystemID             5154 non-null   int64
 11  typeID                    5154 non-null   int64
 12  useOperationName          5154 non-null   bool
dtypes: bool(1), float64(4), int64(7), object(1)
memory usage: 488.3+ KB

--- Debug Script Finished ---

In [ ]:
import pandas as pd
import sys
import time
import io

# --- Configuration (Global) ---
BUCKET_NAME = "eve-online-foundation-data"
GCS_PATH = f"gs://{BUCKET_NAME}"

def load_and_flatten_name(filename, gcs_path=GCS_PATH, id_col='_key', name_col='name'):
    """Loads a JSONL file from GCS, flattens its 'name' column, and renames its ID."""
    print(f"Loading & flattening: {filename}...")
    try:
        df = pd.read_json(f"{gcs_path}/{filename}", lines=True)

        # Flatten the name column (e.g., name['en'])
        if name_col in df.columns:
            df[f'{filename.split(".")[0]}_name_en'] = df[name_col].apply(
                lambda x: x.get('en') if isinstance(x, dict) else None
            )
            df = df.drop(columns=[name_col])

        # Rename the primary key
        if id_col in df.columns:
            df = df.rename(columns={id_col: f'{filename.split(".")[0]}_id'})

        return df
    except Exception as e:
        print(f"FAILED to load {filename}. Error: {e}")
        return None

def build_dogma_features(gcs_path, attribute_names_to_get):
    """Builds a pivoted feature table for item stats (Dogma)."""
    print("Building Dogma (stats) feature table...")
    try:
        # 1. Load attribute names
        print("Loading: dogmaAttributes.jsonl...")
        df_attr = pd.read_json(f"{gcs_path}/dogmaAttributes.jsonl", lines=True)
        df_attr = df_attr.rename(columns={'_key': 'attributeID'})
        df_attr = df_attr[['attributeID', 'name']] # Use the raw 'name' column

        # 2. Filter for ONLY the attributes we care about
        df_attr_filtered = df_attr[df_attr['name'].isin(attribute_names_to_get)]
        print(f"Filtered to {len(df_attr_filtered)} key attributes.")

        if len(df_attr_filtered) == 0:
            print("*** WARNING: Filtered to 0 attributes. Check your attribute list.")
            return pd.DataFrame(columns=['typeID']) # Return empty DF

        # 3. Load and un-nest the typeDogma data
        print("Loading and un-nesting typeDogma.jsonl...")
        df_dogma_nested = pd.read_json(f"{gcs_path}/typeDogma.jsonl", lines=True)
        df_dogma_nested = df_dogma_nested.rename(columns={'_key': 'typeID'})

        df_dogma_long = df_dogma_nested.explode('dogmaAttributes')
        df_dogma_long = df_dogma_long.dropna(subset=['dogmaAttributes'])

        df_dogma_attrs = pd.json_normalize(df_dogma_long['dogmaAttributes'])
        df_dogma_long = df_dogma_long.reset_index(drop=True)

        df_dogma_flat = pd.concat([df_dogma_long[['typeID']], df_dogma_attrs], axis=1)
        print("Successfully un-nested typeDogma data.")

        # 6. Merge dogma values with our filtered attribute names
        df_merged_dogma = pd.merge(
            df_dogma_flat,
            df_attr_filtered[['attributeID', 'name']],
            on='attributeID',
            how='inner'
        )

        # 7. Pivot the table!
        print("Pivoting Dogma table...")
        df_dogma_features = df_merged_dogma.pivot_table(
            index='typeID',
            columns='name',
            values='value',
            aggfunc='first'
        )

        df_dogma_features = df_dogma_features.add_prefix('dogma_')
        print("Dogma feature table built successfully.")
        return df_dogma_features.reset_index() # Make 'typeID' a column

    except Exception as e:
        print(f"FAILED to build dogma features. Error: {e}")
        return None

print("All helper functions defined.")

All helper functions defined.

# Feature Vectors

## Feature Engineering: Ship Stats Vector
Build Ship + Stats Vector

In [ ]:
# Set pandas options for nice output
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 2000)

def main_build_ship_vector():
    start_time = time.time()

    # 1. Define the features we want
    # --- FIX 1: 'basePrice' is REMOVED from this list ---
    SHIP_STATS_TO_GET = [
        'cpuOutput', 'powergridOutput', 'capacitorCapacity',
        'shieldCapacity', 'shieldEmDamageResonance', 'shieldThermalDamageResonance',
        'shieldKineticDamageResonance', 'shieldExplosiveDamageResonance',
        'armorHP', 'armorEmDamageResonance', 'armorThermalDamageResonance',
        'armorKineticDamageResonance', 'armorExplosiveDamageResonance',
        'structureHP', 'mass', 'volume', 'capacity'
    ]

    # 2. Build the Dogma (Stats) Feature Table
    dogma_features = build_dogma_features(GCS_PATH, SHIP_STATS_TO_GET)
    if dogma_features is None:
        sys.exit("Stopping due to dogma build failure.")

    # 3. Load dimension tables
    # 'basePrice' is loaded here from types.jsonl
    df_types = load_and_flatten_name("types.jsonl", GCS_PATH, "_key", "name")
    df_groups = load_and_flatten_name("groups.jsonl", GCS_PATH, "_key", "name")
    df_categories = load_and_flatten_name("categories.jsonl", GCS_PATH, "_key", "name")
    df_market_groups = load_and_flatten_name("marketGroups.jsonl", GCS_PATH, "_key", "name")

    # 4. Build the "Base Ship" DataFrame
    print("Building base ship table...")
    df_base = pd.merge(df_types, df_groups, left_on='groupID', right_on='groups_id', how='left')
    df_base = pd.merge(df_base, df_categories, left_on='categoryID', right_on='categories_id', how='left')

    df_ships = df_base[
        (df_base['categories_name_en'] == 'Ship') &
        (df_base['published'] == True)
    ].copy()
    print(f"Found {len(df_ships)} published ship types.")

    # 5. Join all feature tables
    print("Joining all feature tables...")
    df_final_vector = pd.merge(
        df_ships,
        df_market_groups[['marketGroups_id', 'marketGroups_name_en']],
        left_on='marketGroupID',
        right_on='marketGroups_id',
        how='left'
    )

    if 'typeID' in dogma_features.columns and len(dogma_features) > 0:
        df_final_vector = pd.merge(
            df_final_vector,
            dogma_features,
            left_on='types_id',
            right_on='typeID',
            how='left'
        )

    # 6. Clean and Report
    stat_cols = [col for col in df_final_vector.columns if col.startswith('dogma_')]
    df_final_vector[stat_cols] = df_final_vector[stat_cols].fillna(0)

    # --- FIX 2: 'basePrice' is ADDED to this list ---
    final_columns_to_keep = [
        'types_id', 'types_name_en', 'groups_name_en', 'categories_name_en',
        'marketGroups_name_en', 'basePrice' # <--- ADDED HERE
    ] + stat_cols

    final_columns_to_keep = [col for col in final_columns_to_keep if col in df_final_vector.columns]

    df_final_vector = df_final_vector[final_columns_to_keep].rename(columns={
        'types_id': 'ship_typeID',
        'types_name_en': 'ship_name',
        'groups_name_en': 'group_name',
        'categories_name_en': 'category_name',
        'marketGroups_name_en': 'market_group'
    })

    print(f"\n--- Feature Vector Build Complete! (Total time: {time.time() - start_time:.2f}s) ---")

    print("\n[INFO] Final Ship Feature Vector:")
    df_final_vector.info()

    print("\n[HEAD] Final Ship Feature Vector:")
    display(df_final_vector.head()) # 'display()' gives a nice HTML table in Colab

    return df_final_vector # Return the DataFrame for later use

# --- Run the analysis ---
ship_stats_vector = main_build_ship_vector()

Building Dogma (stats) feature table...
Loading: dogmaAttributes.jsonl...
Filtered to 15 key attributes.
Loading and un-nesting typeDogma.jsonl...
Successfully un-nested typeDogma data.
Pivoting Dogma table...
Dogma feature table built successfully.
Loading & flattening: types.jsonl...
Loading & flattening: groups.jsonl...
Loading & flattening: categories.jsonl...
Loading & flattening: marketGroups.jsonl...
Building base ship table...
Found 550 published ship types.
Joining all feature tables...

--- Feature Vector Build Complete! (Total time: 8.26s) ---

[INFO] Final Ship Feature Vector:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 20 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   ship_typeID                           550 non-null    int64
 1   ship_name                             550 non-null    object
 2   group_name                            550 non-null    object
 3   category_name                         550 non-null    object
 4   market_group                          407 non-null    object
 5   basePrice                             465 non-null    float64
 6   dogma_armorEmDamageResonance          550 non-null    float64
 7   dogma_armorExplosiveDamageResonance   550 non-null    float64
 8   dogma_armorHP                         550 non-null    float64
 9   dogma_armorKineticDamageResonance     550 non-null    float64
 10  dogma_armorThermalDamageResonance     550 non-null    float64
 11  dogma_capacitorCapacity               550 non-null    float64
 12  dogma_cpuOutput                       550 non-null    float64
 13  dogma_mass                            550 non-null    float64
 14  dogma_shieldCapacity                  550 non-null    float64
 15  dogma_shieldEmDamageResonance         550 non-null    float64
 16  dogma_shieldExplosiveDamageResonance  550 non-null    float64
 17  dogma_shieldKineticDamageResonance    550 non-null    float64
 18  dogma_shieldThermalDamageResonance    550 non-null    float64
 19  dogma_volume                          550 non-null    float64
dtypes: float64(15), int64(1), object(4)
memory usage: 86.1+ KB

[HEAD] Final Ship Feature Vector:

   ship_typeID ship_name group_name category_name market_group  basePrice  dogma_armorEmDamageResonance  dogma_armorExplosiveDamageResonance  dogma_armorHP  dogma_armorKineticDamageResonance  dogma_armorThermalDamageResonance  dogma_capacitorCapacity  dogma_cpuOutput  dogma_mass  dogma_shieldCapacity  dogma_shieldEmDamageResonance  dogma_shieldExplosiveDamageResonance  dogma_shieldKineticDamageResonance  dogma_shieldThermalDamageResonance  dogma_volume
0          582    Bantam    Frigate          Ship      Caldari   300000.0                           0.5                                  0.9          225.0                               0.75                               0.55                    615.0            200.0         0.0                 500.0                            1.0                                   0.5                                 0.6                                 0.8           0.0
1          583    Condor    Frigate          Ship      Caldari   400000.0                           0.5                                  0.9          250.0                               0.75                               0.55                    300.0            185.0         0.0                 400.0                            1.0                                   0.5                                 0.6                                 0.8           0.0
2          584   Griffin    Frigate          Ship      Caldari   300000.0                           0.5                                  0.9          250.0                               0.75                               0.55                    245.0            240.0         0.0                 400.0                            1.0                                   0.5                                 0.6                                 0.8           0.0
3          585   Slasher    Frigate          Ship     Minmatar   400000.0                           0.4                                  0.9          300.0                               0.75                               0.65                    240.0            140.0         0.0                 350.0                            1.0                                   0.5                                 0.6                                 0.8           0.0
4          586     Probe    Frigate          Ship     Minmatar   400000.0                           0.4                                  0.9          300.0                               0.75                               0.65                    235.0            240.0         0.0                 300.0                            1.0                                   0.5                                 0.6                                 0.8           0.0

## Feature Engineering: Manufacturing Vector

### Manufacturing Files

In [ ]:
print("--- 1. Understanding 'blueprints.jsonl' ---")
try:
    # Load just the first 5 rows to see the structure
    df_blueprints = pd.read_json(f"{GCS_PATH}/blueprints.jsonl", lines=True, nrows=5)

    print("\n[INFO] 'blueprints.jsonl':")
    df_blueprints.info()

    print("\n[HEAD] 'blueprints.jsonl':")
    display(df_blueprints.head())

except Exception as e:
    print(f"FAILED to load blueprints.jsonl. Error: {e}")

print("\n--- 2. Understanding 'typeMaterials.jsonl' ---")
try:
    # Load just the first 5 rows
    df_materials = pd.read_json(f"{GCS_PATH}/typeMaterials.jsonl", lines=True, nrows=5)

    print("\n[INFO] 'typeMaterials.jsonl':")
    df_materials.info()

    print("\n[HEAD] 'typeMaterials.jsonl':")
    display(df_materials.head())

except Exception as e:
    print(f"FAILED to load typeMaterials.jsonl. Error: {e}")

print("\n--- Debugging Script Finished ---")

--- 1. Understanding 'blueprints.jsonl' ---

[INFO] 'blueprints.jsonl':
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   _key                5 non-null      int64
 1   activities          5 non-null      object
 2   blueprintTypeID     5 non-null      int64
 3   maxProductionLimit  5 non-null      int64
dtypes: int64(3), object(1)
memory usage: 292.0+ bytes

[HEAD] 'blueprints.jsonl':

   _key                                         activities  blueprintTypeID  maxProductionLimit
0   681  {'copying': {'time': 480}, 'manufacturing': {'...              681                 300
1   682  {'copying': {'time': 480}, 'manufacturing': {'...              682                 300
2   683  {'copying': {'time': 4800}, 'invention': {'mat...              683                  30
3   684  {'copying': {'time': 4800}, 'invention': {'mat...              684                  30
4   685  {'copying': {'time': 4800}, 'invention': {'mat...              685                  30

--- 2. Understanding 'typeMaterials.jsonl' ---

[INFO] 'typeMaterials.jsonl':
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   _key       5 non-null      int64
 1   materials  5 non-null      object
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes

[HEAD] 'typeMaterials.jsonl':

   _key                                          materials
0    18  [{'materialTypeID': 34, 'quantity': 175}, {'ma...
1    19  [{'materialTypeID': 34, 'quantity': 48000}, {'...
2    20  [{'materialTypeID': 36, 'quantity': 60}, {'mat...
3    21  [{'materialTypeID': 35, 'quantity': 450}, {'ma...
4    22  [{'materialTypeID': 35, 'quantity': 3200}, {'m...

--- Debugging Script Finished ---

WARNING:root:Quickchart encountered unexpected dtypes in columns: "(['materials'],)"

from matplotlib import pyplot as plt
_df_0['_key'].plot(kind='hist', bins=20, title='_key')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['_key']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': '_key'}, axis=1)
              .sort_values('_key', ascending=True))
  xs = counted['_key']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_1.sort_values('_key', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('_key')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_2['_key'].plot(kind='line', figsize=(8, 4), title='_key')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
import pandas as pd
import json

GCS_PATH = f"gs://{BUCKET_NAME}"

print("--- Understanding 'blueprints.jsonl' activities column ---")
try:
    # Load just the Bantam Blueprint (typeID 681)
    df_blueprints = pd.read_json(f"{GCS_PATH}/blueprints.jsonl", lines=True)

    # Let's find the 'Bantam Blueprint' (blueprintTypeID 681)
    bantam_bp = df_blueprints[df_blueprints['blueprintTypeID'] == 681].iloc[0]

    print("\n[INFO] Full 'activities' data for 'Bantam Blueprint':\n")

    # Pretty-print the JSON from the 'activities' column
    print(json.dumps(bantam_bp['activities'], indent=2))

except Exception as e:
    print(f"FAILED to load and inspect blueprint. Error: {e}")

print("\n--- Debug Script Finished ---")

--- Understanding 'blueprints.jsonl' activities column ---

[INFO] Full 'activities' data for 'Bantam Blueprint':

{
  "copying": {
    "time": 480
  },
  "manufacturing": {
    "materials": [
      {
        "quantity": 86,
        "typeID": 38
      }
    ],
    "products": [
      {
        "quantity": 1,
        "typeID": 165
      }
    ],
    "time": 600
  },
  "research_material": {
    "time": 210
  },
  "research_time": {
    "time": 210
  }
}

--- Debug Script Finished ---

## Build Manufacturing Anomaly Report

In [ ]:
import pandas as pd
import sys
import time
import io

# Set pandas options for nice output
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 2000)

def main_build_mfg_vector():
    start_time = time.time()

    # --- 1. Load Base Ship & Type Data ---
    # We need df_types for material names later
    print("Loading base types, groups, and categories...")
    df_types = load_and_flatten_name("types.jsonl", GCS_PATH, "_key", "name")
    df_groups = load_and_flatten_name("groups.jsonl", GCS_PATH, "_key", "name")
    df_categories = load_and_flatten_name("categories.jsonl", GCS_PATH, "_key", "name")

    df_base = pd.merge(df_types, df_groups, left_on='groupID', right_on='groups_id', how='left')
    df_base = pd.merge(df_base, df_categories, left_on='categoryID', right_on='categories_id', how='left')

    df_ships = df_base[
        (df_base['categories_name_en'] == 'Ship') &
        (df_base['published'] == True)
    ][['types_id', 'types_name_en', 'groups_name_en']].rename(columns={
        'types_id': 'ship_typeID',
        'types_name_en': 'ship_name',
        'groups_name_en': 'ship_group'
    })
    print(f"Found {len(df_ships)} published ships.")

    # --- 2. Load and UN-NEST Blueprint Data ---
    print("Loading and un-nesting 'blueprints.jsonl'...")
    try:
        df_blueprints = pd.read_json(f"{GCS_PATH}/blueprints.jsonl", lines=True)
        df_blueprints = df_blueprints.rename(columns={'_key': 'blueprint_typeID'})

        # Normalize the 'activities' column to get 'manufacturing.products' and 'manufacturing.materials'
        df_activities = pd.json_normalize(df_blueprints['activities'])

        # Combine with the blueprint's ID
        df_blueprints_flat = pd.concat([df_blueprints[['blueprint_typeID']], df_activities], axis=1)

        # --- 2a. Process Products ---
        print("...processing manufacturing products.")
        # We must check if 'manufacturing.products' exists
        if 'manufacturing.products' not in df_blueprints_flat.columns:
            raise KeyError("Column 'manufacturing.products' not found.")

        df_bp_prod = df_blueprints_flat[['blueprint_typeID', 'manufacturing.products']].dropna(subset=['manufacturing.products'])
        df_bp_prod_exploded = df_bp_prod.explode('manufacturing.products')
        df_bp_prod_norm = pd.json_normalize(df_bp_prod_exploded['manufacturing.products'])

        # Our final product lookup table: [blueprint_typeID, productTypeID]
        df_bp_products_lookup = pd.concat([
            df_bp_prod_exploded[['blueprint_typeID']].reset_index(drop=True),
            df_bp_prod_norm[['typeID']]
        ], axis=1).rename(columns={'typeID': 'productTypeID'})

        # --- 2b. Process Materials ---
        print("...processing manufacturing materials.")
        if 'manufacturing.materials' not in df_blueprints_flat.columns:
            raise KeyError("Column 'manufacturing.materials' not found.")

        df_bp_mat = df_blueprints_flat[['blueprint_typeID', 'manufacturing.materials']].dropna(subset=['manufacturing.materials'])
        df_bp_mat_exploded = df_bp_mat.explode('manufacturing.materials')
        df_bp_mat_norm = pd.json_normalize(df_bp_mat_exploded['manufacturing.materials'])

        # Our final material lookup table: [blueprint_typeID, materialTypeID, quantity]
        df_bp_materials_long = pd.concat([
            df_bp_mat_exploded[['blueprint_typeID']].reset_index(drop=True),
            df_bp_mat_norm[['typeID', 'quantity']]
        ], axis=1).rename(columns={'typeID': 'materialTypeID'})

        print("Successfully un-nested blueprints.")

    except Exception as e:
        print(f"*** FAILED to un-nest 'blueprints.jsonl'. Error: {e}")
        return

    # --- 3. Pivot Material Costs ---
    print("Pivoting material costs...")

    # We need the *names* of the materials (e.g., "Tritanium") from the types table
    df_material_names = df_types[['types_id', 'types_name_en']].rename(columns={
        'types_id': 'materialTypeID',
        'types_name_en': 'material_name'
    })

    df_materials_named = pd.merge(df_bp_materials_long, df_material_names, on='materialTypeID', how='left')

    # Pivot the table to get columns like 'mfg_Tritanium', 'mfg_Pyerite'
    KEY_MINERALS = ['Tritanium', 'Pyerite', 'Mexallon', 'Isogen', 'Nocxium', 'Zydrine', 'Megacyte']
    df_materials_filtered = df_materials_named[df_materials_named['material_name'].isin(KEY_MINERALS)]

    df_mfg_features = df_materials_filtered.pivot_table(
        index='blueprint_typeID', # Use blueprint_typeID as the key
        columns='material_name',
        values='quantity',
        aggfunc='sum'
    ).add_prefix('mfg_')

    print("Manufacturing feature table built.")

    # --- 4. Join Features to Ship List ---
    print("Joining features to ship list...")

    # 1. Which ships have a blueprint? (Join ships with blueprint products)
    df_final = pd.merge(
        df_ships,
        df_bp_products_lookup,
        left_on='ship_typeID',
        right_on='productTypeID',
        how='left' # Keep all ships, even those with no blueprint
    )

    # 2. What are the costs for that blueprint?
    # (Join blueprint_typeID with the material cost table)
    df_final = pd.merge(
        df_final,
        df_mfg_features,
        on='blueprint_typeID', # This is now the common key
        how='left'
    )

    # --- 5. Clean and Report ---
    mfg_cols = [col for col in df_final.columns if col.startswith('mfg_')]
    df_final[mfg_cols] = df_final[mfg_cols].fillna(0) # Ships that don't need Tritanium

    # A 'NaN' blueprint_typeID means the ship cannot be built.
    df_final['is_buildable'] = df_final['blueprint_typeID'].notna()

    print(f"\n--- Augmentation Complete! (Total time: {time.time() - start_time:.2f}s) ---")

    print("\n[HEAD] Ships and their mineral costs:")
    display(df_final[df_final['is_buildable'] == True][['ship_name'] + mfg_cols].head())

    print("\n--- ANOMALY REPORT: Published Ships That Are NOT Buildable ---")
    anomaly_df = df_final[df_final['is_buildable'] == False][['ship_name', 'ship_group', 'is_buildable']]
    display(anomaly_df.head(20))

    return df_final, anomaly_df

# --- Run the analysis ---
mfg_vector, anomalies = main_build_mfg_vector()

Loading base types, groups, and categories...
Loading & flattening: types.jsonl...
Loading & flattening: groups.jsonl...
Loading & flattening: categories.jsonl...
Found 550 published ships.
Loading and un-nesting 'blueprints.jsonl'...
...processing manufacturing products.
...processing manufacturing materials.
Successfully un-nested blueprints.
Pivoting material costs...
Manufacturing feature table built.
Joining features to ship list...

--- Augmentation Complete! (Total time: 5.22s) ---

[HEAD] Ships and their mineral costs:

  ship_name  mfg_Isogen  mfg_Megacyte  mfg_Mexallon  mfg_Nocxium  mfg_Pyerite  mfg_Tritanium  mfg_Zydrine
0    Bantam       375.0           0.0        1875.0          0.0       4500.0        24000.0          0.0
1    Condor       500.0           0.0        2500.0          0.0       6000.0        32000.0          0.0
2   Griffin       375.0           0.0        1875.0          0.0       4500.0        24000.0          0.0
3   Slasher       500.0           0.0        2500.0          0.0       6000.0        32000.0          0.0
4     Probe       550.0           0.0        2750.0          0.0       6600.0        35200.0          0.0

--- ANOMALY REPORT: Published Ships That Are NOT Buildable ---

                         ship_name                  ship_group  is_buildable
6                           Reaper                    Corvette         False
13            Gallente Police Ship                     Frigate         False
14                        Impairor                    Corvette         False
19                            Ibis                    Corvette         False
23                         Velator                    Corvette         False
49               Opux Luxury Yacht                     Cruiser         False
68                         Capsule                     Capsule         False
71          Polaris Enigma Frigate                    Corvette         False
72          Concord Police Frigate                     Frigate         False
73            Concord SWAT Frigate                     Frigate         False
74            Concord Army Frigate                     Frigate         False
75     Concord Special Ops Frigate                     Frigate         False
76          Concord Police Cruiser                     Cruiser         False
77       Concord Police Battleship                  Battleship         False
78  Concord Special Ops Battleship                  Battleship         False
79         Concord SWAT Battleship                  Battleship         False
80         Concord Army Battleship                  Battleship         False
83                          Zephyr  Prototype Exploration Ship         False
87                          Primae                      Hauler         False
92                         Echelon                     Frigate         False

## Create Master Feature Vector

In [ ]:
import pandas as pd

# This cell assumes 'ship_stats_vector' (from Cell 3)
# and 'mfg_vector' (from Cell 4) are in memory.

print("--- 1. Creating Master Feature Vector ---")

# We only need the manufacturing columns from the mfg_vector
mfg_cols_to_merge = [
    'ship_typeID',
    'is_buildable',
    'blueprint_typeID'
] + [col for col in mfg_vector.columns if col.startswith('mfg_')]

# Merge the stats vector (Cell 3) with the mfg vector (Cell 4)
master_vector = pd.merge(
    ship_stats_vector,
    mfg_vector[mfg_cols_to_merge],
    on='ship_typeID',
    how='left'
)

# Fill NaNs created by the merge (e.g., non-buildable ships)
mfg_cols = [col for col in master_vector.columns if col.startswith('mfg_')]
master_vector[mfg_cols] = master_vector[mfg_cols].fillna(0)
master_vector['is_buildable'] = master_vector['is_buildable'].fillna(False)

print("Master vector created successfully.")

print("\n[INFO] Master Ship Feature Vector:")
master_vector.info()

print("\n[HEAD] Master Ship Feature Vector:")
display(master_vector.head())

--- 1. Creating Master Feature Vector ---
Master vector created successfully.

[INFO] Master Ship Feature Vector:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 29 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   ship_typeID                           550 non-null    int64
 1   ship_name                             550 non-null    object
 2   group_name                            550 non-null    object
 3   category_name                         550 non-null    object
 4   market_group                          407 non-null    object
 5   basePrice                             465 non-null    float64
 6   dogma_armorEmDamageResonance          550 non-null    float64
 7   dogma_armorExplosiveDamageResonance   550 non-null    float64
 8   dogma_armorHP                         550 non-null    float64
 9   dogma_armorKineticDamageResonance     550 non-null    float64
 10  dogma_armorThermalDamageResonance     550 non-null    float64
 11  dogma_capacitorCapacity               550 non-null    float64
 12  dogma_cpuOutput                       550 non-null    float64
 13  dogma_mass                            550 non-null    float64
 14  dogma_shieldCapacity                  550 non-null    float64
 15  dogma_shieldEmDamageResonance         550 non-null    float64
 16  dogma_shieldExplosiveDamageResonance  550 non-null    float64
 17  dogma_shieldKineticDamageResonance    550 non-null    float64
 18  dogma_shieldThermalDamageResonance    550 non-null    float64
 19  dogma_volume                          550 non-null    float64
 20  is_buildable                          550 non-null    bool
 21  blueprint_typeID                      503 non-null    float64
 22  mfg_Isogen                            550 non-null    float64
 23  mfg_Megacyte                          550 non-null    float64
 24  mfg_Mexallon                          550 non-null    float64
 25  mfg_Nocxium                           550 non-null    float64
 26  mfg_Pyerite                           550 non-null    float64
 27  mfg_Tritanium                         550 non-null    float64
 28  mfg_Zydrine                           550 non-null    float64
dtypes: bool(1), float64(23), int64(1), object(4)
memory usage: 121.0+ KB

[HEAD] Master Ship Feature Vector:

   ship_typeID ship_name group_name category_name market_group  basePrice  dogma_armorEmDamageResonance  dogma_armorExplosiveDamageResonance  dogma_armorHP  dogma_armorKineticDamageResonance  dogma_armorThermalDamageResonance  dogma_capacitorCapacity  dogma_cpuOutput  dogma_mass  dogma_shieldCapacity  dogma_shieldEmDamageResonance  dogma_shieldExplosiveDamageResonance  dogma_shieldKineticDamageResonance  dogma_shieldThermalDamageResonance  dogma_volume  is_buildable  blueprint_typeID  mfg_Isogen  mfg_Megacyte  mfg_Mexallon  mfg_Nocxium  mfg_Pyerite  mfg_Tritanium  mfg_Zydrine
0          582    Bantam    Frigate          Ship      Caldari   300000.0                           0.5                                  0.9          225.0                               0.75                               0.55                    615.0            200.0         0.0                 500.0                            1.0                                   0.5                                 0.6                                 0.8           0.0          True             683.0       375.0           0.0        1875.0          0.0       4500.0        24000.0          0.0
1          583    Condor    Frigate          Ship      Caldari   400000.0                           0.5                                  0.9          250.0                               0.75                               0.55                    300.0            185.0         0.0                 400.0                            1.0                                   0.5                                 0.6                                 0.8           0.0          True             684.0       500.0           0.0        2500.0          0.0       6000.0        32000.0          0.0
2          584   Griffin    Frigate          Ship      Caldari   300000.0                           0.5                                  0.9          250.0                               0.75                               0.55                    245.0            240.0         0.0                 400.0                            1.0                                   0.5                                 0.6                                 0.8           0.0          True             685.0       375.0           0.0        1875.0          0.0       4500.0        24000.0          0.0
3          585   Slasher    Frigate          Ship     Minmatar   400000.0                           0.4                                  0.9          300.0                               0.75                               0.65                    240.0            140.0         0.0                 350.0                            1.0                                   0.5                                 0.6                                 0.8           0.0          True             689.0       500.0           0.0        2500.0          0.0       6000.0        32000.0          0.0
4          586     Probe    Frigate          Ship     Minmatar   400000.0                           0.4                                  0.9          300.0                               0.75                               0.65                    235.0            240.0         0.0                 300.0                            1.0                                   0.5                                 0.6                                 0.8           0.0          True             690.0       550.0           0.0        2750.0          0.0       6600.0        35200.0          0.0

# Analyze Anomalies ("Design-Time" check)
It finds items that are statically imbalanced.

## Visualize Anomalies (EDA on the Master Vector)

In [ ]:
import plotly.express as px

# This cell assumes 'master_vector' is in memory

print("--- Visualizing Ship Features for Anomalies ---")

# Anomaly Plot 1: Cost vs. HP
# Hypothesis: More expensive ships (minerals) should have more HP.
fig = px.scatter(
    master_vector,
    x='dogma_armorHP',
    y='mfg_Tritanium',  # Tritanium is a good proxy for cost
    color='group_name', # See how Frigates, Cruisers, etc. cluster
    hover_name='ship_name',
    title='Anomaly Plot: Armor HP vs. Tritanium Cost',
    log_x=True, # Use log scale for HP
    log_y=True  # Use log scale for cost
)
fig.show()

# --- THIS PLOT IS NOW FIXED ---
# Anomaly Plot 2: CPU vs. Capacitor
# Hypothesis: Ships should have a balanced CPU and Capacitor.
fig2 = px.scatter(
    master_vector,
    x='dogma_cpuOutput',
    y='dogma_capacitorCapacity', # <-- CORRECTED: Was 'dogma_powergridOutput'
    color='group_name',
    hover_name='ship_name',
    title='Anomaly Plot: CPU vs. Capacitor'
)
fig2.show()

--- Visualizing Ship Features for Anomalies ---

## Build the Anomaly Detection Model (Unsupervised learning)

**Modeling (Scikit-learn):** We use an ***Isolation Forest*** model to "score" each ship based on how anomalous its features are.

In [ ]:
from sklearn.ensemble import IsolationForest
import numpy as np

# This cell assumes 'master_vector' is in memory

print("--- Building Anomaly Detection Model ---")

# 1. Select ONLY the numeric features for the model
# We can't model text, so we drop names, groups, etc.
features_to_model = [col for col in master_vector.columns if
                     col.startswith('dogma_') or col.startswith('mfg_')]

print(f"Modeling on {len(features_to_model)} features.")
X = master_vector[features_to_model]

# 2. Create and fit the model
# 'contamination' is your "guess" at what % of data is anomalous.
# Let's start by looking for the weirdest 1% (0.01)
model = IsolationForest(contamination=0.01, random_state=42)
model.fit(X)

# 3. Get the predictions
# The model gives a 'decision_function' score (lower is more anomalous)
# and a 'predict' score (-1 = anomaly, 1 = normal)
master_vector['anomaly_score'] = model.decision_function(X)
master_vector['is_anomaly'] = model.predict(X)

print("Model training complete. 'anomaly_score' and 'is_anomaly' added.")

# 4. Sort by the anomaly score to see the "weirdest" ships
df_anomalies = master_vector.sort_values(by='anomaly_score').reset_index()

print("\n--- Top 10 Most Anomalous Ships ---")
display(df_anomalies[df_anomalies['is_anomaly'] == -1][
    ['ship_name', 'group_name', 'anomaly_score']
].head(10))

--- Building Anomaly Detection Model ---
Modeling on 21 features.
Model training complete. 'anomaly_score' and 'is_anomaly' added.

--- Top 10 Most Anomalous Ships ---

      ship_name    group_name  anomaly_score
0     Cockroach       Frigate      -0.092350
1       Marshal     Black Ops      -0.063739
2       Monitor  Flag Cruiser      -0.044897
3  Thunderchild    Battleship      -0.022706
4        Nestor    Battleship      -0.004957

## Investigate a Top Anomaly

In [ ]:
# This cell assumes 'df_anomalies' is in memory

# Get the name of the #1 most anomalous ship
top_anomaly_name = df_anomalies.iloc[0]['ship_name']

print(f"--- Investigating Top Anomaly: {top_anomaly_name} ---")

# Get all features for that ship
anomaly_details = master_vector[
    master_vector['ship_name'] == top_anomaly_name
]

# Print all its stats
# .T (transpose) makes it easy to read
display(anomaly_details[features_to_model].T)

--- Investigating Top Anomaly: Cockroach ---

                                              112
dogma_armorEmDamageResonance                0.001
dogma_armorExplosiveDamageResonance         0.001
dogma_armorHP                         1000000.000
dogma_armorKineticDamageResonance           0.001
dogma_armorThermalDamageResonance           0.001
dogma_capacitorCapacity                100000.000
dogma_cpuOutput                         10000.000
dogma_mass                                  0.000
dogma_shieldCapacity                  5000000.000
dogma_shieldEmDamageResonance               0.001
dogma_shieldExplosiveDamageResonance        0.001
dogma_shieldKineticDamageResonance          0.001
dogma_shieldThermalDamageResonance          0.001
dogma_volume                                0.000
mfg_Isogen                                  0.000
mfg_Megacyte                                0.000
mfg_Mexallon                                0.000
mfg_Nocxium                                 0.000
mfg_Pyerite                                 0.000
mfg_Tritanium                               0.000
mfg_Zydrine                                 0.000

## "Game Health" Model (Filter for Player Ships)

In [ ]:
from sklearn.ensemble import IsolationForest
import numpy as np

# This cell assumes 'master_vector' is in memory

print("--- Building 'Game Health' Anomaly Model (Player Ships Only) ---")

# 1. Create a "clean" dataset: only ships that are buildable AND on the market
clean_vector = master_vector[
    (master_vector['is_buildable'] == True) &
    (master_vector['market_group'].notna())
].copy()

print(f"Original ship count: {len(master_vector)}. Filtered to {len(clean_vector)} buildable, marketable ships.")

# 2. Select features
features_to_model = [col for col in clean_vector.columns if
                     col.startswith('dogma_') or col.startswith('mfg_')]
X_clean = clean_vector[features_to_model]

# 3. Create and fit the new model
model_clean = IsolationForest(contamination=0.01, random_state=42)
model_clean.fit(X_clean)

# 4. Get predictions
clean_vector['anomaly_score'] = model_clean.decision_function(X_clean)
clean_vector['is_anomaly'] = model_clean.predict(X_clean)

# 5. Sort by the anomaly score
df_clean_anomalies = clean_vector.sort_values(by='anomaly_score').reset_index()

print("\n--- Top 10 'Player Ship' Anomalies ---")
display(df_clean_anomalies[df_clean_anomalies['is_anomaly'] == -1][
    ['ship_name', 'group_name', 'anomaly_score']
].head(10))

--- Building 'Game Health' Anomaly Model (Player Ships Only) ---
Original ship count: 550. Filtered to 385 buildable, marketable ships.

--- Top 10 'Player Ship' Anomalies ---

      ship_name    group_name  anomaly_score
0       Monitor  Flag Cruiser      -0.125228
1       Marshal     Black Ops      -0.101816
2  Thunderchild    Battleship      -0.047892
3        Leshak    Battleship      -0.005217

# Key Findings

**Model 1 (All Ships):** Successfully identified the "***Cockroach***" as the top anomaly—a "god-mode" admin frigate with millions of HP. This proves the model's ability to find statistical impossibilities.

**Model 2 (Player Ships):** After filtering out admin/unbuildable items, the model correctly identified rare, high-end ships like the "Marshal" and "Thunderchild" as the top outliers, proving it can find "edge cases" in the player economy.

# Save Feature Vectors

## Save Feature Vectors to GCS

In [ ]:
import pandas as pd

# This assumes 'master_vector' and 'clean_vector' are in memory
# and 'GCS_PATH' is defined.

print("--- Saving Feature Vectors to GCS ---")

# 1. Save the full 550-ship vector
try:
    master_vector.to_csv(f"{GCS_PATH}/all_ships_vector.csv", index=False)
    print(f"Successfully saved to: {GCS_PATH}/all_ships_vector.csv")

    # 2. Save the "clean" 385-ship vector for your game health model
    clean_vector.to_csv(f"{GCS_PATH}/player_ships_vector.csv", index=False)
    print(f"Successfully saved to: {GCS_PATH}/player_ships_vector.csv")

except Exception as e:
    print(f"*** FAILED to save vectors. Error: {e} ***")

--- Saving Feature Vectors to GCS ---
Successfully saved to: gs://eve-online-foundation-data/all_ships_vector.csv
Successfully saved to: gs://eve-online-foundation-data/player_ships_vector.csv

## Save Feature Vectors locally

In [ ]:
from google.colab import files
print("\n--- Downloading Master Vector Locally ---")
master_vector.to_csv('master_ship_vector.csv')
files.download('master_ship_vector.csv')
print("\n--- Downloading 385-ship vector for your game health model Locally ---")
clean_vector.to_csv('clean_player_ship_vector.csv')
files.download('clean_player_ship_vector.csv')

--- Downloading Master Vector Locally ---

--- Save the clean 385-ship vector for your game health model Locally ---